#!/usr/bin/env python3
"""
Comprehensive French translation script
Reads EN file, compares with FR file, and adds all missing translations
"""
import json
from pathlib import Path

def get_nested_value(obj, path):
    """Get value from nested dict using dot notation path"""
    keys = path.split('.')
    current = obj
    for key in keys:
        if isinstance(current, dict) and key in current:
            current = current[key]
        else:
            return None
    return current

def set_nested_value(obj, path, value):
    """Set value in nested dict using dot notation path"""
    keys = path.split('.')
    current = obj
    for key in keys[:-1]:
        if key not in current:
            current[key] = {}
        current = current[key]
    current[keys[-1]] = value

def get_all_keys(obj, prefix=''):
    """Get all keys from nested dict with dot notation paths"""
    keys = []
    for key, value in obj.items():
        full_key = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            keys.extend(get_all_keys(value, full_key))
        else:
            keys.append(full_key)
    return keys

def translate_to_french(text):
    """Translate English text to French with comprehensive coverage"""

    # Exact phrase translations (most specific)
    exact_translations = {
        # Complex phrases from the application
        "AI-powered tenant scoring and ranking system": "Système de notation et de classement des locataires alimenté par l'IA",
        "Automated application processing and filtering": "Traitement et filtrage automatisés des candidatures",
        "Casual renters, budget-conscious individuals, or first-time users exploring  AI capabilities": "Locataires occasionnels, personnes soucieuses du budget ou nouveaux utilisateurs explorant les capacités de l'IA",
        "Close to your workplace, includes a balcony (a stated preference), and has lower local taxes — perfect for your budget and lifestyle": "Proche de votre lieu de travail, comprend un balcon (une préférence déclarée) et bénéficie d'impôts locaux plus bas — parfait pour votre budget et votre style de vie",
        "Document generation and contract automation": "Génération de documents et automatisation des contrats",
        "Find Quality Tenants Faster Than Ever!": "Trouvez des locataires de qualité plus rapidement que jamais !",
        "Integrated messaging and notification system": "Système de messagerie et de notification intégré",
        "Let AI Handle Your Property Management": "Laissez l'IA gérer votre propriété",
        "Multi-channel communication management": "Gestion de communication multicanal",
        "Professional property listing enhancement": "Amélioration professionnelle des annonces immobilières",
        "Premium landlords and businesses needing advanced  AI features": "Propriétaires et entreprises premium nécessitant des fonctionnalités IA avancées",
        "Professionals managing multiple properties or seeking  AI-powered efficiency": "Professionnels gérant plusieurs propriétés ou recherchant l'efficacité alimentée par l'IA",
        "Custom reports tailored to your property portfolio": "Rapports personnalisés adaptés à votre portefeuille immobilier",
        "Manage multiple properties from a single dashboard": "Gérez plusieurs propriétés depuis un tableau de bord unique",
        "Download comprehensive property reports": "Téléchargez des rapports immobiliers complets",
        "Drag and drop to reorder your properties": "Glissez-déposez pour réorganiser vos propriétés",
        "Get more out of every rental": "Tirez le meilleur parti de chaque location",
        "Join thousands of successful landlords": "Rejoignez des milliers de propriétaires à succès",
        "Properties currently on the market": "Propriétés actuellement sur le marché",
        "Trust the AI to find your perfect home": "Faites confiance à l'IA pour trouver votre maison idéale",
        "Your AI-powered property companion": "Votre compagnon immobilier alimenté par l'IA",
        "Intelligent property search and matching": "Recherche et correspondance immobilière intelligente",
        "Compare properties side by side": "Comparez les propriétés côte à côte",
        "Set up alerts for new listings": "Configurez des alertes pour les nouvelles annonces",
        "Calculate your potential savings": "Calculez vos économies potentielles",
        "Mortgage calculator with AI insights": "Calculateur hypothécaire avec informations IA",
        "Tax benefits and deductions explained": "Avantages fiscaux et déductions expliqués",
        "Personalized recommendations based on your profile": "Recommandations personnalisées basées sur votre profil",
        "Market trends and neighborhood insights": "Tendances du marché et informations sur le quartier",
        "Property value appreciation forecast": "Prévision d'appréciation de la valeur immobilière",
        "Investment potential analysis": "Analyse du potentiel d'investissement",
        "Rental yield comparison": "Comparaison du rendement locatif",
        "Walkability score and local amenities": "Score de marchabilité et commodités locales",
        "School district ratings and information": "Notes et informations sur le district scolaire",
        "Crime statistics and safety ratings": "Statistiques de criminalité et notes de sécurité",
        "Transportation options and commute times": "Options de transport et temps de trajet",
        "Environmental factors and green spaces": "Facteurs environnementaux et espaces verts",
        "Historical price trends for the area": "Tendances historiques des prix pour la zone",
        "Future development plans nearby": "Plans de développement futurs à proximité",
        "HOA fees and community rules": "Frais HOA et règles communautaires",
        "Property inspection reports available": "Rapports d'inspection immobilière disponibles",
        "Virtual tours and 3D walkthroughs": "Visites virtuelles et parcours 3D",
        "Schedule viewing appointments easily": "Planifiez facilement des rendez-vous de visite",
        "Contact landlords directly through chat": "Contactez directement les propriétaires par chat",
        "Submit rental applications online": "Soumettez des candidatures de location en ligne",
        "Track your application status in real-time": "Suivez le statut de votre candidature en temps réel",
        "Receive instant notifications for updates": "Recevez des notifications instantanées pour les mises à jour",
        "Digital lease signing and document management": "Signature de bail numérique et gestion de documents",
        "Automated rent payment reminders": "Rappels de paiement de loyer automatisés",
        "Maintenance request tracking system": "Système de suivi des demandes de maintenance",
        "Tenant screening and background checks": "Vérification et vérifications des antécédents des locataires",
        "Credit score and rental history verification": "Vérification du score de crédit et de l'historique locatif",
        "Income and employment verification": "Vérification des revenus et de l'emploi",
        "Reference checks and contact validation": "Vérifications de références et validation de contact",
        "Automated lease agreement generation": "Génération automatisée d'accords de bail",
        "Rent collection and payment processing": "Collecte de loyers et traitement des paiements",
        "Late payment tracking and reminders": "Suivi des paiements en retard et rappels",
        "Security deposit management": "Gestion des dépôts de garantie",
        "Move-in and move-out inspection reports": "Rapports d'inspection d'entrée et de sortie",
        "Maintenance scheduling and vendor management": "Planification de la maintenance et gestion des fournisseurs",
        "Property performance metrics and KPIs": "Métriques de performance immobilière et KPI",
        "Financial reporting and tax documentation": "Rapports financiers et documentation fiscale",
        "Multi-property portfolio overview": "Aperçu du portefeuille multi-propriétés",
        "Vacancy rate tracking and analysis": "Suivi et analyse du taux de vacance",
        "Rental income optimization suggestions": "Suggestions d'optimisation des revenus locatifs",
        "Market rent comparison and pricing": "Comparaison et tarification des loyers du marché",
        "Tenant retention strategies and tips": "Stratégies et conseils de rétention des locataires",
        "Property marketing and advertising tools": "Outils de marketing et de publicité immobilière",
        "Social media integration for listings": "Intégration des réseaux sociaux pour les annonces",
        "Professional photography recommendations": "Recommandations de photographie professionnelle",
        "Listing optimization for search visibility": "Optimisation des annonces pour la visibilité de recherche",
        "Competitive analysis and market positioning": "Analyse concurrentielle et positionnement sur le marché",
        "Seasonal pricing recommendations": "Recommandations de tarification saisonnière",
        "Dynamic pricing based on market demand": "Tarification dynamique basée sur la demande du marché",
        "Automated response to tenant inquiries": "Réponse automatisée aux demandes des locataires",
        "Chatbot for frequently asked questions": "Chatbot pour les questions fréquemment posées",
        "Document upload and verification system": "Système de téléversement et de vérification de documents",
        "Secure cloud storage for all documents": "Stockage cloud sécurisé pour tous les documents",
        "Document expiration tracking and alerts": "Suivi des expirations de documents et alertes",
        "Compliance monitoring and updates": "Surveillance et mises à jour de la conformité",
        "Legal template library for contracts": "Bibliothèque de modèles juridiques pour les contrats",
        "E-signature integration for agreements": "Intégration de signature électronique pour les accords",
        "Audit trail for all transactions": "Piste d'audit pour toutes les transactions",
        "Data encryption and security measures": "Chiffrement des données et mesures de sécurité",
        "GDPR compliance and data protection": "Conformité RGPD et protection des données",
        "Two-factor authentication for account security": "Authentification à deux facteurs pour la sécurité du compte",
        "Role-based access control for teams": "Contrôle d'accès basé sur les rôles pour les équipes",
        "Activity log and user tracking": "Journal d'activité et suivi des utilisateurs",
        "Backup and disaster recovery systems": "Systèmes de sauvegarde et de reprise après sinistre",
        "99.9% uptime guarantee": "Garantie de disponibilité de 99,9%",
        "24/7 customer support and assistance": "Support client et assistance 24/7",
        "Live chat support during business hours": "Support par chat en direct pendant les heures d'ouverture",
        "Email support with 24-hour response time": "Support par e-mail avec temps de réponse de 24 heures",
        "Phone support for premium members": "Support téléphonique pour les membres premium",
        "Video tutorials and knowledge base": "Tutoriels vidéo et base de connaissances",
        "Webinars and training sessions": "Webinaires et sessions de formation",
        "Community forum for users": "Forum communautaire pour les utilisateurs",
        "Feature requests and feedback system": "Système de demandes de fonctionnalités et de commentaires",
        "Regular product updates and improvements": "Mises à jour et améliorations régulières du produit",
        "Beta testing opportunities for new features": "Opportunités de tests bêta pour les nouvelles fonctionnalités",
        "API documentation for developers": "Documentation API pour les développeurs",
        "Webhook support for integrations": "Support de webhook pour les intégrations",
        "Third-party app marketplace": "Marché d'applications tierces",
        "Custom integrations available": "Intégrations personnalisées disponibles",
        "Export data in multiple formats": "Exporter les données dans plusieurs formats",
        "Import data from other platforms": "Importer des données d'autres plateformes",
        "Bulk operations for efficiency": "Opérations en masse pour l'efficacité",
        "Advanced search and filtering options": "Options de recherche et de filtrage avancées",
        "Saved searches and smart alerts": "Recherches sauvegardées et alertes intelligentes",
        "Customizable dashboard layouts": "Mises en page de tableau de bord personnalisables",
        "Widget library for dashboard": "Bibliothèque de widgets pour le tableau de bord",
        "Mobile app for iOS and Android": "Application mobile pour iOS et Android",
        "Offline mode for mobile app": "Mode hors ligne pour l'application mobile",
        "Push notifications for important events": "Notifications push pour les événements importants",
        "Biometric login for mobile security": "Connexion biométrique pour la sécurité mobile",
        "QR code scanning for property visits": "Scan de code QR pour les visites de propriétés",
        "Location-based property search": "Recherche de propriété basée sur la localisation",
        "Map view with property clusters": "Vue carte avec clusters de propriétés",
        "Street view integration": "Intégration de la vue rue",
        "Augmented reality property preview": "Aperçu de propriété en réalité augmentée",
        "Virtual staging for empty properties": "Mise en scène virtuelle pour les propriétés vides",
        "360-degree photo tours": "Visites photo à 360 degrés",
        "Drone footage integration": "Intégration de séquences de drone",
        "Floor plan creator and editor": "Créateur et éditeur de plan d'étage",
        "Property comparison tool": "Outil de comparaison de propriétés",
        "Favorites and wishlist management": "Gestion des favoris et de la liste de souhaits",
        "Sharing properties with family/friends": "Partage de propriétés avec famille/amis",
        "Private notes on properties": "Notes privées sur les propriétés",
        "Property rating and review system": "Système de notation et d'avis sur les propriétés",
        "Landlord rating and reviews": "Notation et avis sur les propriétaires",
        "Neighborhood reviews and insights": "Avis et informations sur le quartier",
        "Moving checklist and planning tools": "Liste de contrôle de déménagement et outils de planification",
        "Utility setup assistance": "Assistance à la configuration des services publics",
        "Furniture calculator for space planning": "Calculateur de meubles pour la planification de l'espace",
        "Budget calculator for moving costs": "Calculateur de budget pour les frais de déménagement",
        "Packing tips and recommendations": "Conseils et recommandations d'emballage",
        "Moving company recommendations": "Recommandations d'entreprises de déménagement",
        "Change of address notifications": "Notifications de changement d'adresse",
        "Mail forwarding setup guide": "Guide de configuration de réexpédition du courrier",
        "Pet-friendly properties filter": "Filtre de propriétés acceptant les animaux",
        "Wheelchair accessible properties": "Propriétés accessibles en fauteuil roulant",
        "Senior living options": "Options de logement pour seniors",
        "Student housing recommendations": "Recommandations de logement étudiant",
        "Corporate housing solutions": "Solutions de logement d'entreprise",
        "Short-term rental options": "Options de location à court terme",
        "Vacation rental management": "Gestion de location de vacances",
        "Furnished vs unfurnished options": "Options meublées vs non meublées",
        "Utilities included filter": "Filtre services inclus",
        "Parking availability information": "Informations sur la disponibilité du stationnement",
        "Pet policy and restrictions": "Politique et restrictions concernant les animaux",
        "Smoking policy information": "Informations sur la politique de tabagisme",
        "Guest policy and overnight visitors": "Politique des invités et visiteurs de nuit",
        "Subletting and roommate policies": "Politiques de sous-location et de colocation",
        "Lease terms and conditions explained": "Conditions générales du bail expliquées",
        "Renewal options and procedures": "Options et procédures de renouvellement",
        "Breaking lease information and fees": "Informations et frais de rupture de bail",
        "Early termination options": "Options de résiliation anticipée",
        "Transfer and relocation assistance": "Assistance au transfert et à la relocalisation",
        "Rent negotiation tips and strategies": "Conseils et stratégies de négociation de loyer",
        "Move-in specials and promotions": "Offres spéciales et promotions d'emménagement",
        "Referral program for tenants": "Programme de parrainage pour les locataires",
        "Loyalty rewards for long-term tenants": "Récompenses de fidélité pour les locataires à long terme",
        "Rent payment methods accepted": "Modes de paiement de loyer acceptés",
        "Auto-pay setup and management": "Configuration et gestion du paiement automatique",
        "Payment history and receipts": "Historique des paiements et reçus",
        "Rent increase notification system": "Système de notification d'augmentation de loyer",
        "Security deposit return process": "Processus de restitution du dépôt de garantie",
        "Damage claim procedures": "Procédures de réclamation pour dommages",
        "Insurance requirements and options": "Exigences et options d'assurance",
        "Renters insurance recommendations": "Recommandations d'assurance locataire",
        "Property insurance for landlords": "Assurance habitation pour les propriétaires",
        "Liability coverage information": "Informations sur la couverture de responsabilité",
        "Emergency contact management": "Gestion des contacts d'urgence",
        "Emergency repair procedures": "Procédures de réparation d'urgence",
        "After-hours maintenance support": "Support de maintenance en dehors des heures",
        "Preventive maintenance scheduling": "Planification de la maintenance préventive",
        "Service provider directory": "Répertoire de fournisseurs de services",
        "Maintenance cost tracking": "Suivi des coûts de maintenance",
        "Work order management system": "Système de gestion des ordres de travail",
        "Contractor rating and reviews": "Notation et avis sur les entrepreneurs",
        "Before and after maintenance photos": "Photos avant et après maintenance",
        "Warranty and guarantee tracking": "Suivi des garanties",
        "Appliance manuals and guides": "Manuels et guides d'appareils",
        "Home improvement project ideas": "Idées de projets d'amélioration domiciliaire",
        "Energy efficiency tips and savings": "Conseils et économies d'efficacité énergétique",
        "Smart home integration options": "Options d'intégration de maison intelligente",
        "IoT device compatibility": "Compatibilité des appareils IoT",
        "Security system recommendations": "Recommandations de systèmes de sécurité",
        "Keyless entry solutions": "Solutions d'entrée sans clé",
        "Smart lock management": "Gestion de serrures intelligentes",
        "Package delivery notifications": "Notifications de livraison de colis",
        "Visitor management system": "Système de gestion des visiteurs",
        "Community events and announcements": "Événements communautaires et annonces",
        "Neighborhood news and updates": "Nouvelles et mises à jour du quartier",
        "Local business recommendations": "Recommandations d'entreprises locales",
        "Restaurant and dining suggestions": "Suggestions de restaurants et de restauration",
        "Entertainment and activities nearby": "Divertissement et activités à proximité",
        "Parks and recreation facilities": "Parcs et installations de loisirs",
        "Fitness centers and gyms nearby": "Centres de fitness et salles de sport à proximité",
        "Healthcare facilities and hospitals": "Établissements de santé et hôpitaux",
        "Shopping centers and malls": "Centres commerciaux et galeries marchandes",
        "Public transportation routes": "Itinéraires de transport en commun",
        "Bike lanes and cycling routes": "Pistes cyclables et itinéraires cyclistes",
        "Car sharing and ride-sharing options": "Options de covoiturage et d'autopartage",
        "Parking garage locations and rates": "Emplacements et tarifs des parkings",
        "Electric vehicle charging stations": "Stations de recharge pour véhicules électriques",
        "Weather forecasts for the area": "Prévisions météorologiques pour la région",
        "Air quality monitoring": "Surveillance de la qualité de l'air",
        "Noise level measurements": "Mesures du niveau sonore",
        "Natural disaster risk assessment": "Évaluation des risques de catastrophe naturelle",
        "Flood zone information": "Informations sur les zones inondables",
        "Earthquake preparedness": "Préparation aux tremblements de terre",
        "Hurricane and storm safety": "Sécurité contre les ouragans et les tempêtes",
        "Fire safety and evacuation plans": "Sécurité incendie et plans d'évacuation",
        "Building codes and regulations": "Codes et réglementations du bâtiment",
        "Zoning laws and restrictions": "Lois et restrictions de zonage",
        "Historical preservation status": "Statut de préservation historique",
        "Property tax information and rates": "Informations et taux d'impôt foncier",
        "Tax assessment and appeals": "Évaluation fiscale et appels",
        "Property tax payment options": "Options de paiement de l'impôt foncier",
        "Tax exemptions and credits available": "Exemptions et crédits fiscaux disponibles",
        "Homestead exemption information": "Informations sur l'exemption d'homestead",
        "Senior citizen tax benefits": "Avantages fiscaux pour les personnes âgées",
        "Veterans tax benefits": "Avantages fiscaux pour les anciens combattants",
        "Disabled person tax benefits": "Avantages fiscaux pour les personnes handicapées",
        "First-time homebuyer programs": "Programmes pour les primo-accédants",
        "Down payment assistance": "Aide pour l'acompte",
        "Mortgage pre-approval process": "Processus de pré-approbation hypothécaire",
        "Loan comparison and rates": "Comparaison de prêts et taux",
        "Fixed vs variable rate mortgages": "Hypothèques à taux fixe vs variable",
        "Refinancing opportunities": "Opportunités de refinancement",
        "Home equity loans and lines of credit": "Prêts sur valeur domiciliaire et lignes de crédit",
        "Closing cost calculator": "Calculateur des frais de clôture",
        "Amortization schedule": "Tableau d'amortissement",
        "Prepayment and extra payment options": "Options de paiement anticipé et de paiement supplémentaire",
        "Escrow account management": "Gestion du compte séquestre",
        "Title insurance information": "Informations sur l'assurance titre",
        "Home warranty options": "Options de garantie habitation",
        "Home inspection checklist": "Liste de contrôle d'inspection domiciliaire",
        "Appraisal process and valuation": "Processus d'évaluation et valorisation",
        "Comparative market analysis": "Analyse comparative du marché",
        "Property condition disclosure": "Divulgation de l'état de la propriété",
        "Lead paint disclosure": "Divulgation de peinture au plomb",
        "Asbestos and hazardous materials": "Amiante et matériaux dangereux",
        "Radon testing and mitigation": "Test et atténuation du radon",
        "Mold inspection and remediation": "Inspection et remédiation de moisissures",
        "Pest control and treatment": "Contrôle et traitement des parasites",
        "Termite inspection reports": "Rapports d'inspection de termites",
        "Roof condition assessment": "Évaluation de l'état du toit",
        "Foundation inspection": "Inspection de la fondation",
        "Plumbing system evaluation": "Évaluation du système de plomberie",
        "Electrical system inspection": "Inspection du système électrique",
        "HVAC system condition": "État du système CVC",
        "Water heater inspection": "Inspection du chauffe-eau",
        "Septic system information": "Informations sur le système septique",
        "Well water testing": "Test de l'eau de puits",
        "Sewer line inspection": "Inspection de la ligne d'égout",
        "Landscaping and yard maintenance": "Aménagement paysager et entretien de la cour",
        "Irrigation system details": "Détails du système d'irrigation",
        "Pool and spa maintenance": "Entretien de la piscine et du spa",
        "Deck and patio condition": "État de la terrasse et du patio",
        "Fence and gate inspection": "Inspection de la clôture et du portail",
        "Driveway and walkway condition": "État de l'allée et du trottoir",
        "Garage door operation": "Fonctionnement de la porte de garage",
        "Window and door condition": "État des fenêtres et des portes",
        "Insulation and energy efficiency": "Isolation et efficacité énergétique",
        "Ventilation system assessment": "Évaluation du système de ventilation",
        "Drainage and grading evaluation": "Évaluation du drainage et du nivellement",
        "Exterior siding and paint": "Revêtement extérieur et peinture",
        "Gutters and downspouts": "Gouttières et descentes pluviales",
        "Chimney and fireplace inspection": "Inspection de la cheminée et du foyer",
        "Attic and crawl space access": "Accès au grenier et au vide sanitaire",
        "Basement waterproofing": "Imperméabilisation du sous-sol",
        "Carbon monoxide detector": "Détecteur de monoxyde de carbone",
        "Smoke detector placement": "Placement du détecteur de fumée",
        "Fire extinguisher locations": "Emplacements des extincteurs",
        "Security alarm system": "Système d'alarme de sécurité",
        "Camera surveillance system": "Système de surveillance par caméra",
        "Motion sensor lights": "Lumières à capteur de mouvement",
        "Outdoor lighting assessment": "Évaluation de l'éclairage extérieur",
        "Mailbox and address visibility": "Visibilité de la boîte aux lettres et de l'adresse",
        "Accessibility features present": "Fonctionnalités d'accessibilité présentes",
        "Grab bars and safety rails": "Barres d'appui et rampes de sécurité",
        "Wheelchair ramps and lifts": "Rampes et ascenseurs pour fauteuils roulants",
        "Door width measurements": "Mesures de largeur de porte",
        "Bathroom modifications available": "Modifications de salle de bain disponibles",
        "Kitchen accessibility features": "Fonctionnalités d'accessibilité de cuisine",
        "Elevator or lift present": "Ascenseur ou monte-charge présent",
        "Stair lift installation possible": "Installation de monte-escalier possible",
        "Service animal accommodations": "Aménagements pour animaux d'assistance",
        "Medical alert system compatible": "Compatible avec le système d'alerte médicale",
        "Emergency call buttons": "Boutons d'appel d'urgence",
        "Visiting nurse services available": "Services d'infirmière visiteuse disponibles",
        "Assisted living amenities": "Commodités de vie assistée",
        "Memory care features": "Fonctionnalités de soins de la mémoire",
        "Age-restricted community": "Communauté à restriction d'âge",
        "Active adult community": "Communauté d'adultes actifs",
        "55+ community amenities": "Commodités de communauté 55+",
        "Senior center proximity": "Proximité du centre pour seniors",
        "Healthcare services nearby": "Services de santé à proximité",
        "Pharmacy locations": "Emplacements de pharmacie",
        "Grocery delivery services": "Services de livraison d'épicerie",
        "Meal delivery options": "Options de livraison de repas",
        "Transportation services for seniors": "Services de transport pour seniors",
        "Social activities and programs": "Activités sociales et programmes",
        "Educational opportunities": "Opportunités éducatives",
        "Volunteer opportunities": "Opportunités de bénévolat",
        "Library access and services": "Accès et services de bibliothèque",
        "Computer lab and internet access": "Laboratoire informatique et accès Internet",
        "Laundry facilities on-site": "Installations de blanchisserie sur place",
        "Storage units available": "Unités de stockage disponibles",
        "Bike storage options": "Options de stockage de vélos",
        "Recycling program details": "Détails du programme de recyclage",
        "Trash collection schedule": "Calendrier de collecte des ordures",
        "Composting facilities": "Installations de compostage",
        "Green building certifications": "Certifications de bâtiment écologique",
        "Solar panels installed": "Panneaux solaires installés",
        "Energy-efficient appliances": "Appareils économes en énergie",
        "Water conservation features": "Fonctionnalités de conservation de l'eau",
        "Low-flow fixtures": "Accessoires à faible débit",
        "Rainwater harvesting system": "Système de récupération des eaux de pluie",
        "Geothermal heating/cooling": "Chauffage/refroidissement géothermique",
        "LED lighting throughout": "Éclairage LED partout",
        "Smart thermostat included": "Thermostat intelligent inclus",
        "Programmable thermostats": "Thermostats programmables",
        "Ceiling fans in rooms": "Ventilateurs de plafond dans les pièces",
        "Air purification system": "Système de purification d'air",
        "Water filtration system": "Système de filtration de l'eau",
        "Soft water system": "Système d'eau adoucie",
        "Central vacuum system": "Système d'aspirateur central",
        "Built-in speakers": "Haut-parleurs intégrés",
        "Home theater pre-wiring": "Pré-câblage pour home cinéma",
        "Network wiring throughout": "Câblage réseau partout",
        "Fiber optic internet available": "Internet par fibre optique disponible",
        "Cable TV hookups": "Branchements TV par câble",
        "Satellite dish allowed": "Antenne parabolique autorisée",
        "Streaming service compatibility": "Compatibilité avec les services de streaming",
        "Smart home hub compatible": "Compatible avec le hub de maison intelligente",
        "Voice control integration": "Intégration du contrôle vocal",
        "Alexa/Google Home compatible": "Compatible Alexa/Google Home",
        "Smart lighting controls": "Contrôles d'éclairage intelligents",
        "Motorized window treatments": "Traitements de fenêtre motorisés",
        "Smart appliance compatibility": "Compatibilité avec les appareils intelligents",
        "Refrigerator with smart features": "Réfrigérateur avec fonctionnalités intelligentes",
        "Smart oven and cooktop": "Four et plaque de cuisson intelligents",
        "Dishwasher with wifi": "Lave-vaisselle avec wifi",
        "Washer and dryer smart models": "Laveuse et sécheuse modèles intelligents",
        "In-unit laundry hookups": "Branchements de buanderie dans l'unité",
        "Stackable washer/dryer space": "Espace pour laveuse/sécheuse empilables",
        "Walk-in closets": "Garde-robes de plain-pied",
        "Custom closet systems": "Systèmes de garde-robe personnalisés",
        "Hardwood flooring": "Plancher de bois franc",
        "Tile flooring": "Plancher de carreaux",
        "Carpet in bedrooms": "Tapis dans les chambres",
        "Vinyl plank flooring": "Plancher de planches de vinyle",
        "Laminate flooring": "Plancher stratifié",
        "Radiant floor heating": "Chauffage par le sol radiant",
        "Vaulted ceilings": "Plafonds voûtés",
        "Crown molding throughout": "Moulures couronnées partout",
        "Recessed lighting": "Éclairage encastré",
        "Track lighting": "Éclairage sur rail",
        "Pendant light fixtures": "Luminaires suspendus",
        "Chandelier in dining room": "Lustre dans la salle à manger",
        "Under-cabinet lighting": "Éclairage sous les armoires",
        "Granite countertops": "Comptoirs en granit",
        "Quartz countertops": "Comptoirs en quartz",
        "Marble countertops": "Comptoirs en marbre",
        "Butcher block counters": "Comptoirs en bloc de boucher",
        "Stainless steel appliances": "Appareils en acier inoxydable",
        "Gas range and oven": "Cuisinière et four à gaz",
        "Electric range and oven": "Cuisinière et four électriques",
        "Induction cooktop": "Plaque de cuisson à induction",
        "Double oven": "Four double",
        "Convection oven": "Four à convection",
        "Built-in microwave": "Micro-ondes encastré",
        "Range hood with ventilation": "Hotte de cuisinière avec ventilation",
        "Garbage disposal": "Broyeur d'ordures",
        "Instant hot water dispenser": "Distributeur d'eau chaude instantanée",
        "Wine refrigerator": "Réfrigérateur à vin",
        "Beverage refrigerator": "Réfrigérateur à boissons",
        "Ice maker": "Machine à glaçons",
        "Water dispenser in door": "Distributeur d'eau dans la porte",
        "French door refrigerator": "Réfrigérateur à portes françaises",
        "Side-by-side refrigerator": "Réfrigérateur côte à côte",
        "Bottom freezer model": "Modèle avec congélateur en bas",
        "Kitchen island with seating": "Îlot de cuisine avec sièges",
        "Breakfast bar": "Bar pour petit-déjeuner",
        "Breakfast nook": "Coin repas",
        "Formal dining room": "Salle à manger formelle",
        "Open floor plan": "Plan d'étage ouvert",
        "Split bedroom layout": "Disposition de chambre séparée",
        "Master suite with sitting area": "Suite principale avec coin salon",
        "Walk-in shower": "Douche de plain-pied",
        "Soaking tub": "Baignoire de trempage",
        "Jetted tub": "Baignoire à jets",
        "Dual vanity": "Double vasque",
        "Vessel sinks": "Éviers à vasque",
        "Rainfall showerhead": "Pomme de douche effet pluie",
        "Handheld shower wand": "Douchette à main",
        "Frameless glass shower": "Douche en verre sans cadre",
        "Heated bathroom floors": "Planchers de salle de bain chauffants",
        "Linen closet in bathroom": "Placard à linge dans la salle de bain",
        "Exhaust fan with timer": "Ventilateur d'extraction avec minuterie",
        "Skylight in bathroom": "Puits de lumière dans la salle de bain",
        "Window in bathroom": "Fenêtre dans la salle de bain",
        "Privacy glass in bathroom": "Verre intimité dans la salle de bain",
        "Heated towel rack": "Porte-serviettes chauffant",
        "Medicine cabinet with lights": "Armoire à pharmacie avec lumières",
        "Makeup vanity area": "Espace coiffeuse",
        "Bidet or bidet seat": "Bidet ou siège de bidet",
        "Comfort height toilets": "Toilettes de hauteur confort",
        "Water-efficient toilets": "Toilettes économes en eau",
        "Motion sensor faucets": "Robinets à capteur de mouvement",
        "Touchless soap dispensers": "Distributeurs de savon sans contact",
        "Heated toilet seat": "Siège de toilette chauffant",
        "Japanese style toilet": "Toilette de style japonais",
        "Pocket door to bathroom": "Porte escamotable vers la salle de bain",
        "Barn door to bathroom": "Porte de grange vers la salle de bain",
        "Jack and Jill bathroom": "Salle de bain Jack et Jill",
        "En-suite bathroom": "Salle de bain attenante",
        "Powder room": "Salle d'eau",
        "Half bath": "Demi-salle de bain",
        "Three-quarter bath": "Trois quarts de salle de bain",
        "Full bath": "Salle de bain complète",
        "Number of bathrooms": "Nombre de salles de bain",
        "Number of bedrooms": "Nombre de chambres",
        "Number of floors": "Nombre d'étages",
        "Square footage": "Superficie en pieds carrés",
        "Lot size": "Superficie du terrain",
        "Year built": "Année de construction",
        "Recent renovations": "Rénovations récentes",
        "Move-in ready": "Prêt à emménager",
        "Fixer-upper": "À rénover",
        "New construction": "Construction neuve",
        "Pre-construction": "Pré-construction",
        "Under construction": "En construction",
        "Coming soon": "Bientôt disponible",
        "Just listed": "Nouvellement inscrit",
        "Price reduced": "Prix réduit",
        "Open house scheduled": "Journée portes ouvertes prévue",
        "Virtual tour available": "Visite virtuelle disponible",
        "Video walkthrough": "Vidéo de visite",
        "3D tour": "Visite 3D",
        "Floor plan available": "Plan d'étage disponible",
        "Recent photos": "Photos récentes",
        "Professional photos": "Photos professionnelles",
        "Aerial photos": "Photos aériennes",
        "Neighborhood photos": "Photos du quartier",
        "Seasonal photos": "Photos saisonnières",
        "Day and night photos": "Photos de jour et de nuit",
        "Interior photos": "Photos intérieures",
        "Exterior photos": "Photos extérieures",
        "Backyard photos": "Photos de cour arrière",
        "Front yard photos": "Photos de cour avant",
        "Kitchen photos": "Photos de cuisine",
        "Bathroom photos": "Photos de salle de bain",
        "Bedroom photos": "Photos de chambre",
        "Living room photos": "Photos de salon",
        "Dining room photos": "Photos de salle à manger",
        "Basement photos": "Photos de sous-sol",
        "Attic photos": "Photos de grenier",
        "Garage photos": "Photos de garage",
        "Laundry room photos": "Photos de buanderie",
        "Office photos": "Photos de bureau",
        "Bonus room photos": "Photos de pièce bonus",
        "Recreation room photos": "Photos de salle de loisirs",
        "Home gym photos": "Photos de gym maison",
        "Home theater photos": "Photos de cinéma maison",
        "Wine cellar photos": "Photos de cave à vin",
        "Mudroom photos": "Photos de vestibule",
        "Pantry photos": "Photos de garde-manger",
        "Closet photos": "Photos de garde-robe",
        "Balcony photos": "Photos de balcon",
        "Patio photos": "Photos de patio",
        "Deck photos": "Photos de terrasse",
        "Porch photos": "Photos de porche",
        "Screened porch": "Porche grillagé",
        "Sunroom": "Véranda",
        "Four seasons room": "Pièce quatre saisons",
        "Florida room": "Pièce Florida",
        "Conservatory": "Conservatoire",
        "Greenhouse": "Serre",
        "Garden area": "Espace jardin",
        "Vegetable garden": "Jardin potager",
        "Herb garden": "Jardin d'herbes",
        "Flower beds": "Plates-bandes",
        "Mature trees": "Arbres matures",
        "Fruit trees": "Arbres fruitiers",
        "Shade trees": "Arbres d'ombrage",
        "Privacy fence": "Clôture d'intimité",
        "Chain link fence": "Clôture en grillage",
        "Vinyl fence": "Clôture en vinyle",
        "Wood fence": "Clôture en bois",
        "Wrought iron fence": "Clôture en fer forgé",
        "Stone wall": "Mur de pierre",
        "Retaining wall": "Mur de soutènement",
        "Gate with lock": "Portail avec serrure",
        "Automatic gate": "Portail automatique",
        "Security gate": "Portail de sécurité",
        "Gated community": "Communauté fermée",
        "HOA community": "Communauté HOA",
        "Condo association": "Association de copropriété",
        "Townhouse community": "Communauté de maisons en rangée",
        "Master-planned community": "Communauté planifiée",
        "Resort-style amenities": "Commodités de style resort",
        "Clubhouse access": "Accès au club-house",
        "Community pool": "Piscine communautaire",
        "Tennis courts": "Courts de tennis",
        "Basketball court": "Terrain de basketball",
        "Playground": "Aire de jeux",
        "Dog park": "Parc pour chiens",
        "Walking trails": "Sentiers de promenade",
        "Jogging path": "Piste de jogging",
        "Nature preserve": "Réserve naturelle",
        "Lake access": "Accès au lac",
        "Beach access": "Accès à la plage",
        "Waterfront property": "Propriété en bord de l'eau",
        "Water view": "Vue sur l'eau",
        "Ocean view": "Vue sur l'océan",
        "Lake view": "Vue sur le lac",
        "River view": "Vue sur la rivière",
        "Mountain view": "Vue sur les montagnes",
        "City view": "Vue sur la ville",
        "Park view": "Vue sur le parc",
        "Golf course view": "Vue sur le terrain de golf",
        "Garden view": "Vue sur le jardin",
        "Courtyard view": "Vue sur la cour",
        "Scenic view": "Vue panoramique",
        "Panoramic view": "Vue panoramique",
        "Unobstructed view": "Vue dégagée",
        "Corner unit": "Unité de coin",
        "End unit": "Unité d'extrémité",
        "Penthouse": "Penthouse",
        "Loft": "Loft",
        "Studio": "Studio",
        "Junior one bedroom": "Junior une chambre",
        "One bedroom": "Une chambre",
        "One bedroom plus den": "Une chambre plus bureau",
        "Two bedroom": "Deux chambres",
        "Two bedroom plus den": "Deux chambres plus bureau",
        "Three bedroom": "Trois chambres",
        "Four bedroom": "Quatre chambres",
        "Five bedroom or more": "Cinq chambres ou plus",
        "Split level": "Niveau séparé",
        "Bi-level": "Bi-niveau",
        "Tri-level": "Tri-niveau",
        "Ranch style": "Style ranch",
        "Cape Cod style": "Style Cape Cod",
        "Colonial style": "Style colonial",
        "Victorian style": "Style victorien",
        "Tudor style": "Style Tudor",
        "Mediterranean style": "Style méditerranéen",
        "Spanish style": "Style espagnol",
        "Mission style": "Style mission",
        "Craftsman style": "Style artisan",
        "Bungalow": "Bungalow",
        "Cottage": "Chalet",
        "Cabin": "Cabane",
        "Contemporary": "Contemporain",
        "Modern": "Moderne",
        "Traditional": "Traditionnel",
        "Transitional": "Transitionnel",
        "Mid-century modern": "Moderne du milieu du siècle",
        "Art Deco": "Art déco",
        "Industrial loft": "Loft industriel",
        "Converted warehouse": "Entrepôt converti",
        "Brownstone": "Maison en grès brun",
        "Row house": "Maison en rangée",
        "Townhouse": "Maison en rangée",
        "Duplex": "Duplex",
        "Triplex": "Triplex",
        "Fourplex": "Quadruplex",
        "Apartment": "Appartement",
        "Condominium": "Copropriété",
        "Co-op": "Coopérative",
        "Single family home": "Maison unifamiliale",
        "Multi-family home": "Maison multifamiliale",
        "Mobile home": "Maison mobile",
        "Manufactured home": "Maison manufacturée",
        "Modular home": "Maison modulaire",
        "Tiny house": "Micro-maison",
        "Container home": "Maison conteneur",
        "Prefab home": "Maison préfabriquée",
        "Custom built home": "Maison construite sur mesure",
        "Spec home": "Maison spéculative",
        "Model home": "Maison modèle",
        "Foreclosure": "Saisie",
        "Short sale": "Vente à découvert",
        "REO property": "Propriété REO",
        "Bank owned": "Propriété de la banque",
        "As-is sale": "Vente tel quel",
        "Estate sale": "Vente de succession",
        "Probate sale": "Vente de succession",
        "Investment property": "Propriété d'investissement",
        "Rental property": "Propriété locative",
        "Vacation home": "Maison de vacances",
        "Second home": "Résidence secondaire",
        "Primary residence": "Résidence principale",
        "Owner occupied": "Occupé par le propriétaire",
        "Tenant occupied": "Occupé par un locataire",
        "Vacant": "Vacant",
        "Immediately available": "Immédiatement disponible",
        "Available date": "Date de disponibilité",
        "Flexible move-in date": "Date d'emménagement flexible",
        "Long-term lease": "Bail à long terme",
        "Short-term lease": "Bail à court terme",
        "Month-to-month": "Mois par mois",
        "Annual lease": "Bail annuel",
        "Multi-year lease": "Bail pluriannuel",
        "Lease with option to buy": "Bail avec option d'achat",
        "Rent-to-own": "Location-accession",
        "Lease purchase": "Achat-location",
        "Assumable lease": "Bail transférable",
        "Sublease allowed": "Sous-location autorisée",
        "No subletting": "Pas de sous-location",
        "Roommates allowed": "Colocataires autorisés",
        "Single occupant only": "Occupant unique seulement",
        "Maximum occupancy": "Occupation maximale",
        "Income requirement": "Exigence de revenu",
        "Credit score requirement": "Exigence de score de crédit",
        "Employment verification": "Vérification de l'emploi",
        "Reference check required": "Vérification de références requise",
        "Background check required": "Vérification des antécédents requise",
        "No credit check": "Pas de vérification de crédit",
        "Bad credit okay": "Mauvais crédit acceptable",
        "No income verification": "Pas de vérification de revenu",
        "Guarantor accepted": "Garant accepté",
        "Co-signer allowed": "Cosignataire autorisé",
        "First month free": "Premier mois gratuit",
        "Last month free": "Dernier mois gratuit",
        "No security deposit": "Pas de dépôt de garantie",
        "Reduced security deposit": "Dépôt de garantie réduit",
        "Pet deposit required": "Dépôt pour animal requis",
        "Pet rent": "Loyer pour animal",
        "Non-refundable pet fee": "Frais pour animal non remboursables",
        "Pet restrictions": "Restrictions pour animaux",
        "Dogs allowed": "Chiens autorisés",
        "Cats allowed": "Chats autorisés",
        "Small pets only": "Petits animaux seulement",
        "Large dogs allowed": "Grands chiens autorisés",
        "Weight limit for pets": "Limite de poids pour les animaux",
        "Breed restrictions": "Restrictions de race",
        "Number of pets allowed": "Nombre d'animaux autorisés",
        "Pet interview required": "Entretien pour animal requis",
        "Service animals welcome": "Animaux d'assistance bienvenus",
        "Emotional support animals": "Animaux de soutien émotionnel",
        "No pets allowed": "Animaux non autorisés",
        "Pet-free property": "Propriété sans animaux",
        "Allergy-friendly": "Adapté aux allergies",
        "Non-smoking property": "Propriété non-fumeur",
        "Smoking allowed": "Fumeur autorisé",
        "Smoking outside only": "Fumeur à l'extérieur seulement",
        "Designated smoking area": "Zone fumeur désignée",
        "Cannabis friendly": "Accepte le cannabis",
        "Cannabis prohibited": "Cannabis interdit",
        "No illegal activities": "Pas d'activités illégales",
        "Quiet hours enforced": "Heures de silence appliquées",
        "Noise restrictions": "Restrictions de bruit",
        "Party policy": "Politique de fête",
        "Guest parking available": "Stationnement pour invités disponible",
        "Visitor parking": "Stationnement pour visiteurs",
        "Assigned parking space": "Place de stationnement assignée",
        "Covered parking": "Stationnement couvert",
        "Underground parking": "Stationnement souterrain",
        "Street parking": "Stationnement de rue",
        "Permit parking": "Stationnement avec permis",
        "Parking included": "Stationnement inclus",
        "Additional parking fee": "Frais de stationnement supplémentaires",
        "One car garage": "Garage pour une voiture",
        "Two car garage": "Garage pour deux voitures",
        "Three car garage": "Garage pour trois voitures",
        "Attached garage": "Garage attenant",
        "Detached garage": "Garage détaché",
        "Carport": "Abri d'auto",
        "Tandem parking": "Stationnement en tandem",
        "Parallel parking": "Stationnement parallèle",
        "RV parking": "Stationnement pour VR",
        "Boat parking": "Stationnement pour bateau",
        "Motorcycle parking": "Stationnement pour moto",
        "EV charging station": "Station de recharge VE",
        "Garage door opener": "Ouvre-porte de garage",
        "Workshop in garage": "Atelier dans le garage",
        "Storage in garage": "Rangement dans le garage",
        "Finished garage": "Garage fini",
        "Heated garage": "Garage chauffé",
    }

    if english_text in exact_translations:
        return exact_translations[english_text]

    # Common patterns
    text_lower = english_text.lower()