#!/usr/bin/env python3
"""
Compare en/translation.json with it/translation.json and add missing Italian translations.
"""

import json
import os
from pathlib import Path

# Translation dictionary for common terms
TRANSLATIONS = {
    # Common UI elements
    "Save": "Salva",
    "Cancel": "Annulla",
    "Delete": "Elimina",
    "Edit": "Modifica",
    "Add": "Aggiungi",
    "Remove": "Rimuovi",
    "Close": "Chiudi",
    "Open": "Apri",
    "Submit": "Invia",
    "Continue": "Continua",
    "Back": "Indietro",
    "Next": "Avanti",
    "Previous": "Precedente",
    "Finish": "Completa",
    "Done": "Fatto",
    "Yes": "Sì",
    "No": "No",
    "OK": "OK",
    "Search": "Cerca",
    "Filter": "Filtra",
    "Sort": "Ordina",
    "View": "Visualizza",
    "Download": "Scarica",
    "Upload": "Carica",
    "Export": "Esporta",
    "Import": "Importa",
    "Print": "Stampa",
    "Share": "Condividi",
    "Copy": "Copia",
    "Paste": "Incolla",
    "Cut": "Taglia",
    "Select": "Seleziona",
    "Clear": "Cancella",
    "Reset": "Ripristina",
    "Refresh": "Aggiorna",
    "Reload": "Ricarica",
    "Loading": "Caricamento",
    "Loading...": "Caricamento...",
    "Please wait...": "Attendere prego...",
    "Processing": "Elaborazione",
    "Processing...": "Elaborazione...",
    "Success": "Successo",
    "Error": "Errore",
    "Warning": "Avviso",
    "Info": "Informazione",
    "Confirm": "Conferma",
    "Settings": "Impostazioni",
    "Profile": "Profilo",
    "Account": "Account",
    "Dashboard": "Pannello di controllo",
    "Home": "Home",
    "Help": "Aiuto",
    "About": "Informazioni",
    "Contact": "Contatto",
    "Support": "Supporto",
    "Terms": "Termini",
    "Privacy": "Privacy",
    "Policy": "Politica",
    "Cookie Policy": "Politica sui Cookie",
    "Logout": "Disconnetti",
    "Login": "Accedi",
    "Sign In": "Accedi",
    "Sign Up": "Registrati",
    "Register": "Registrati",
    "Email": "Email",
    "Password": "Password",
    "Username": "Nome utente",
    "Name": "Nome",
    "First Name": "Nome",
    "Last Name": "Cognome",
    "Phone": "Telefono",
    "Address": "Indirizzo",
    "City": "Città",
    "Country": "Paese",
    "State": "Stato",
    "Zip Code": "CAP",
    "Date": "Data",
    "Time": "Ora",
    "Status": "Stato",
    "Type": "Tipo",
    "Category": "Categoria",
    "Description": "Descrizione",
    "Details": "Dettagli",
    "Comments": "Commenti",
    "Notes": "Note",
    "Tags": "Tag",
    "Actions": "Azioni",
    "Options": "Opzioni",
    "Preferences": "Preferenze",
    "Language": "Lingua",
    "Notifications": "Notifiche",
    "Messages": "Messaggi",
    "All": "Tutti",
    "None": "Nessuno",
    "Other": "Altro",
    "More": "Altro",
    "Less": "Meno",
    "Show": "Mostra",
    "Hide": "Nascondi",
    "Expand": "Espandi",
    "Collapse": "Comprimi",
    "New": "Nuovo",
    "Recent": "Recente",
    "Active": "Attivo",
    "Inactive": "Inattivo",
    "Enabled": "Abilitato",
    "Disabled": "Disabilitato",
    "Required": "Obbligatorio",
    "Optional": "Facoltativo",
    "Available": "Disponibile",
    "Unavailable": "Non disponibile",
    "Online": "Online",
    "Offline": "Offline",
    "Public": "Pubblico",
    "Private": "Privato",
    "Draft": "Bozza",
    "Published": "Pubblicato",
    "Pending": "In attesa",
    "Approved": "Approvato",
    "Rejected": "Rifiutato",
    "Cancelled": "Annullato",
    "Completed": "Completato",
    "Failed": "Fallito",
    "Total": "Totale",
    "Subtotal": "Subtotale",
    "Tax": "Imposta",
    "Amount": "Importo",
    "Price": "Prezzo",
    "Cost": "Costo",
    "Free": "Gratuito",
    "Paid": "Pagato",
    "Unpaid": "Non pagato",
    "Payment": "Pagamento",
    "Invoice": "Fattura",
    "Receipt": "Ricevuta",
    "Order": "Ordine",
    "Product": "Prodotto",
    "Service": "Servizio",
    "Quantity": "Quantità",
    "Quality": "Qualità",
    "Size": "Dimensione",
    "Color": "Colore",
    "Weight": "Peso",
    "Height": "Altezza",
    "Width": "Larghezza",
    "Length": "Lunghezza",
    "Depth": "Profondità",
    "Area": "Area",
    "Volume": "Volume",
    "Distance": "Distanza",
    "Duration": "Durata",
    "Start": "Inizio",
    "End": "Fine",
    "From": "Da",
    "To": "A",
    "Created": "Creato",
    "Updated": "Aggiornato",
    "Modified": "Modificato",
    "Deleted": "Eliminato",
    "Created At": "Creato il",
    "Updated At": "Aggiornato il",
    "Created By": "Creato da",
    "Updated By": "Aggiornato da",
    "Owner": "Proprietario",
    "Author": "Autore",
    "User": "Utente",
    "Users": "Utenti",
    "Role": "Ruolo",
    "Roles": "Ruoli",
    "Permission": "Permesso",
    "Permissions": "Permessi",
    "Group": "Gruppo",
    "Groups": "Gruppi",
    "Team": "Team",
    "Teams": "Team",
    "Organization": "Organizzazione",
    "Company": "Azienda",
    "Department": "Dipartimento",
    "Project": "Progetto",
    "Projects": "Progetti",
    "Task": "Attività",
    "Tasks": "Attività",
    "Event": "Evento",
    "Events": "Eventi",
    "Calendar": "Calendario",
    "Schedule": "Programma",
    "Appointment": "Appuntamento",
    "Meeting": "Riunione",
    "Report": "Rapporto",
    "Reports": "Rapporti",
    "Analytics": "Analisi",
    "Statistics": "Statistiche",
    "Chart": "Grafico",
    "Graph": "Grafico",
    "Table": "Tabella",
    "List": "Elenco",
    "Grid": "Griglia",
    "Map": "Mappa",
    "Image": "Immagine",
    "Images": "Immagini",
    "Photo": "Foto",
    "Photos": "Foto",
    "Video": "Video",
    "Videos": "Video",
    "Audio": "Audio",
    "File": "File",
    "Files": "File",
    "Folder": "Cartella",
    "Folders": "Cartelle",
    "Document": "Documento",
    "Documents": "Documenti",
    "Attachment": "Allegato",
    "Attachments": "Allegati",
    "Link": "Link",
    "Links": "Link",
    "URL": "URL",
    "Page": "Pagina",
    "Pages": "Pagine",
    "Article": "Articolo",
    "Articles": "Articoli",
    "Post": "Post",
    "Posts": "Post",
    "Blog": "Blog",
    "News": "Notizie",
    "Feed": "Feed",
    "Archive": "Archivio",
    "History": "Cronologia",
    "Activity": "Attività",
    "Log": "Registro",
    "Logs": "Registri",
    "Audit": "Audit",
    "Version": "Versione",
    "Versions": "Versioni",
    "Backup": "Backup",
    "Restore": "Ripristina",
    "Update": "Aggiorna",
    "Upgrade": "Aggiorna",
    "Install": "Installa",
    "Uninstall": "Disinstalla",
    "Configure": "Configura",
    "Configuration": "Configurazione",
    "Setup": "Configurazione",
    "Wizard": "Procedura guidata",
    "Tutorial": "Tutorial",
    "Guide": "Guida",
    "Documentation": "Documentazione",
    "FAQ": "FAQ",
    "Question": "Domanda",
    "Questions": "Domande",
    "Answer": "Risposta",
    "Answers": "Risposte",
    "Feedback": "Feedback",
    "Review": "Recensione",
    "Reviews": "Recensioni",
    "Rating": "Valutazione",
    "Ratings": "Valutazioni",
    "Comment": "Commento",
    "Reply": "Rispondi",
    "Like": "Mi piace",
    "Dislike": "Non mi piace",
    "Favorite": "Preferito",
    "Favorites": "Preferiti",
    "Bookmark": "Segnalibro",
    "Bookmarks": "Segnalibri",
    "Subscribe": "Iscriviti",
    "Unsubscribe": "Disiscriviti",
    "Subscription": "Abbonamento",
    "Subscriptions": "Abbonamenti",
    "Plan": "Piano",
    "Plans": "Piani",
    "Feature": "Funzionalità",
    "Features": "Funzionalità",
    "Benefit": "Beneficio",
    "Benefits": "Benefici",
    "Pricing": "Prezzi",
    "Discount": "Sconto",
    "Coupon": "Coupon",
    "Promotion": "Promozione",
    "Offer": "Offerta",
    "Deal": "Offerta",
    "Sale": "Vendita",
    "Sold": "Venduto",
    "Available": "Disponibile",
    "Stock": "Scorta",
    "In Stock": "Disponibile",
    "Out of Stock": "Esaurito",
    "Shipping": "Spedizione",
    "Delivery": "Consegna",
    "Pickup": "Ritiro",
    "Return": "Reso",
    "Refund": "Rimborso",
    "Exchange": "Scambio",
    "Cart": "Carrello",
    "Checkout": "Checkout",
    "Billing": "Fatturazione",
    "Billing Address": "Indirizzo di fatturazione",
    "Shipping Address": "Indirizzo di spedizione",
    "Credit Card": "Carta di credito",
    "Debit Card": "Carta di debito",
    "Bank Account": "Conto bancario",
    "PayPal": "PayPal",
    "Cash": "Contanti",
    "Check": "Assegno",
    "Wire Transfer": "Bonifico bancario",
    "Transaction": "Transazione",
    "Transactions": "Transazioni",
    "Balance": "Saldo",
    "Credit": "Credito",
    "Debit": "Debito",
    "Income": "Reddito",
    "Expense": "Spesa",
    "Expenses": "Spese",
    "Revenue": "Entrate",
    "Profit": "Profitto",
    "Loss": "Perdita",
    "Budget": "Budget",
    "Forecast": "Previsione",
    "Estimate": "Stima",
    "Actual": "Effettivo",
    "Target": "Obiettivo",
    "Goal": "Obiettivo",
    "Goals": "Obiettivi",
    "Objective": "Obiettivo",
    "Objectives": "Obiettivi",
    "Milestone": "Traguardo",
    "Milestones": "Traguardi",
    "Progress": "Progresso",
    "Performance": "Prestazioni",
    "Result": "Risultato",
    "Results": "Risultati",
    "Outcome": "Risultato",
    "Output": "Output",
    "Input": "Input",
    "Data": "Dati",
    "Information": "Informazioni",
    "Content": "Contenuto",
    "Text": "Testo",
    "Title": "Titolo",
    "Subtitle": "Sottotitolo",
    "Heading": "Intestazione",
    "Paragraph": "Paragrafo",
    "Line": "Riga",
    "Word": "Parola",
    "Character": "Carattere",
    "Number": "Numero",
    "Value": "Valore",
    "Label": "Etichetta",
    "Placeholder": "Segnaposto",
    "Icon": "Icona",
    "Button": "Pulsante",
    "Menu": "Menu",
    "Navigation": "Navigazione",
    "Sidebar": "Barra laterale",
    "Header": "Intestazione",
    "Footer": "Piè di pagina",
    "Content": "Contenuto",
    "Main": "Principale",
    "Section": "Sezione",
    "Item": "Elemento",
    "Items": "Elementi",
    "Entry": "Voce",
    "Entries": "Voci",
    "Record": "Record",
    "Records": "Record",
    "Row": "Riga",
    "Rows": "Righe",
    "Column": "Colonna",
    "Columns": "Colonne",
    "Cell": "Cella",
    "Field": "Campo",
    "Fields": "Campi",
    "Form": "Modulo",
    "Forms": "Moduli",
    "Input": "Input",
    "Checkbox": "Casella di controllo",
    "Radio": "Pulsante radio",
    "Dropdown": "Menu a discesa",
    "Select": "Seleziona",
    "Multiselect": "Selezione multipla",
    "Textarea": "Area di testo",
    "Editor": "Editor",
    "Picker": "Selettore",
    "Slider": "Cursore",
    "Toggle": "Interruttore",
    "Switch": "Interruttore",
    "Tab": "Scheda",
    "Tabs": "Schede",
    "Accordion": "Fisarmonica",
    "Modal": "Modale",
    "Dialog": "Finestra di dialogo",
    "Popup": "Popup",
    "Tooltip": "Suggerimento",
    "Alert": "Avviso",
    "Notification": "Notifica",
    "Message": "Messaggio",
    "Banner": "Banner",
    "Badge": "Badge",
    "Tag": "Tag",
    "Chip": "Chip",
    "Avatar": "Avatar",
    "Thumbnail": "Miniatura",
    "Preview": "Anteprima",
    "Gallery": "Galleria",
    "Carousel": "Carosello",
    "Slideshow": "Presentazione",
    "Player": "Lettore",
    "Control": "Controllo",
    "Controls": "Controlli",
    "Toolbar": "Barra degli strumenti",
    "Panel": "Pannello",
    "Widget": "Widget",
    "Component": "Componente",
    "Module": "Modulo",
    "Plugin": "Plugin",
    "Extension": "Estensione",
    "Theme": "Tema",
    "Style": "Stile",
    "Layout": "Layout",
    "Template": "Modello",
    "Format": "Formato",
    "Alignment": "Allineamento",
    "Position": "Posizione",
    "Margin": "Margine",
    "Padding": "Riempimento",
    "Border": "Bordo",
    "Background": "Sfondo",
    "Foreground": "Primo piano",
    "Opacity": "Opacità",
    "Visibility": "Visibilità",
    "Display": "Visualizzazione",
    "Responsive": "Responsive",
    "Mobile": "Mobile",
    "Tablet": "Tablet",
    "Desktop": "Desktop",
    "Device": "Dispositivo",
    "Browser": "Browser",
    "Platform": "Piattaforma",
    "Operating System": "Sistema operativo",
    "Application": "Applicazione",
    "Software": "Software",
    "Program": "Programma",
    "App": "App",
    "Website": "Sito web",
    "Web Page": "Pagina web",
    "Homepage": "Homepage",
    "Landing Page": "Landing page",
    "Portal": "Portale",
    "Interface": "Interfaccia",
    "UI": "UI",
    "UX": "UX",
    "Design": "Design",
    "Development": "Sviluppo",
    "Code": "Codice",
    "Script": "Script",
    "Function": "Funzione",
    "Method": "Metodo",
    "Class": "Classe",
    "Object": "Oggetto",
    "Variable": "Variabile",
    "Constant": "Costante",
    "Parameter": "Parametro",
    "Argument": "Argomento",
    "Return": "Ritorna",
    "Call": "Chiama",
    "Execute": "Esegui",
    "Run": "Esegui",
    "Build": "Compila",
    "Compile": "Compila",
    "Debug": "Debug",
    "Test": "Test",
    "Deploy": "Distribuisci",
    "Release": "Rilascio",
    "Production": "Produzione",
    "Development": "Sviluppo",
    "Staging": "Staging",
    "Environment": "Ambiente",
    "Server": "Server",
    "Client": "Client",
    "Database": "Database",
    "API": "API",
    "Endpoint": "Endpoint",
    "Request": "Richiesta",
    "Response": "Risposta",
    "Query": "Query",
    "Command": "Comando",
    "Operation": "Operazione",
    "Action": "Azione",
    "Event": "Evento",
    "Handler": "Gestore",
    "Listener": "Ascoltatore",
    "Callback": "Callback",
    "Promise": "Promise",
    "Async": "Asincrono",
    "Sync": "Sincrono",
    "Load": "Carica",
    "Fetch": "Recupera",
    "Get": "Ottieni",
    "Post": "Invia",
    "Put": "Aggiorna",
    "Patch": "Patch",
    "Delete": "Elimina",
    "Create": "Crea",
    "Read": "Leggi",
    "Write": "Scrivi",
    "Update": "Aggiorna",
    "Destroy": "Distruggi",
    "Insert": "Inserisci",
    "Select": "Seleziona",
    "Where": "Dove",
    "Join": "Unisci",
    "Group": "Raggruppa",
    "Order": "Ordina",
    "Limit": "Limite",
    "Offset": "Offset",
    "Count": "Conta",
    "Sum": "Somma",
    "Average": "Media",
    "Min": "Min",
    "Max": "Max",
    "First": "Primo",
    "Last": "Ultimo",
    "Unique": "Unico",
    "Distinct": "Distinto",
    "Duplicate": "Duplica",
    "Clone": "Clona",
    "Move": "Sposta",
    "Rename": "Rinomina",
    "Replace": "Sostituisci",
    "Find": "Trova",
    "Match": "Corrispondenza",
    "Contains": "Contiene",
    "Starts With": "Inizia con",
    "Ends With": "Termina con",
    "Empty": "Vuoto",
    "Null": "Nullo",
    "Undefined": "Non definito",
    "True": "Vero",
    "False": "Falso",
    "And": "E",
    "Or": "O",
    "Not": "Non",
    "If": "Se",
    "Else": "Altrimenti",
    "Then": "Poi",
    "When": "Quando",
    "While": "Mentre",
    "For": "Per",
    "Each": "Ciascuno",
    "Break": "Interrompi",
    "Continue": "Continua",
    "Return": "Ritorna",
    "Try": "Prova",
    "Catch": "Cattura",
    "Finally": "Infine",
    "Throw": "Lancia",
    "Exception": "Eccezione",
    "Error": "Errore",
    "Warning": "Avviso",
    "Notice": "Avviso",
    "Debug": "Debug",
    "Trace": "Traccia",
    "Stack": "Stack",
    "Memory": "Memoria",
    "CPU": "CPU",
    "Storage": "Archiviazione",
    "Cache": "Cache",
    "Session": "Sessione",
    "Cookie": "Cookie",
    "Token": "Token",
    "Key": "Chiave",
    "Secret": "Segreto",
    "Hash": "Hash",
    "Encrypt": "Crittografa",
    "Decrypt": "Decrittografa",
    "Encode": "Codifica",
    "Decode": "Decodifica",
    "Compress": "Comprimi",
    "Decompress": "Decomprimi",
    "Archive": "Archivia",
    "Extract": "Estrai",
    "Serialize": "Serializza",
    "Deserialize": "Deserializza",
    "Parse": "Analizza",
    "Format": "Formatta",
    "Validate": "Valida",
    "Sanitize": "Sanitizza",
    "Escape": "Escape",
    "Unescape": "Unescape",
    "Trim": "Taglia",
    "Split": "Dividi",
    "Join": "Unisci",
    "Merge": "Unisci",
    "Concat": "Concatena",
    "Append": "Aggiungi",
    "Prepend": "Anteponi",
    "Push": "Push",
    "Pop": "Pop",
    "Shift": "Shift",
    "Unshift": "Unshift",
    "Slice": "Affetta",
    "Splice": "Splice",
    "Reverse": "Inverti",
    "Sort": "Ordina",
    "Shuffle": "Mescola",
    "Random": "Casuale",
    "Generate": "Genera",
    "Calculate": "Calcola",
    "Convert": "Converti",
    "Transform": "Trasforma",
    "Map": "Mappa",
    "Filter": "Filtra",
    "Reduce": "Riduci",
    "Apply": "Applica",
    "Execute": "Esegui",
    "Invoke": "Invoca",
    "Trigger": "Attiva",
    "Emit": "Emetti",
    "Broadcast": "Trasmetti",
    "Publish": "Pubblica",
    "Subscribe": "Iscriviti",
    "Unsubscribe": "Disiscriviti",
    "Connect": "Connetti",
    "Disconnect": "Disconnetti",
    "Reconnect": "Riconnetti",
    "Bind": "Associa",
    "Unbind": "Dissocia",
    "Attach": "Allega",
    "Detach": "Stacca",
    "Mount": "Monta",
    "Unmount": "Smonta",
    "Initialize": "Inizializza",
    "Destroy": "Distruggi",
    "Dispose": "Disponi",
    "Clean": "Pulisci",
    "Clear": "Cancella",
    "Flush": "Svuota",
    "Sync": "Sincronizza",
    "Refresh": "Aggiorna",
    "Reload": "Ricarica",
    "Restart": "Riavvia",
    "Pause": "Pausa",
    "Resume": "Riprendi",
    "Stop": "Ferma",
    "Start": "Avvia",
    "Play": "Riproduci",
    "Record": "Registra",
    "Capture": "Cattura",
    "Screenshot": "Screenshot",
    "Snapshot": "Istantanea",
    "Render": "Renderizza",
    "Draw": "Disegna",
    "Paint": "Dipingi",
    "Fill": "Riempi",
    "Stroke": "Tratto",
    "Animate": "Anima",
    "Transition": "Transizione",
    "Effect": "Effetto",
    "Filter": "Filtro",
    "Blur": "Sfocatura",
    "Shadow": "Ombra",
    "Gradient": "Gradiente",
    "Pattern": "Modello",
    "Texture": "Texture",
    "Material": "Materiale",
    "Light": "Luce",
    "Dark": "Scuro",
    "Brightness": "Luminosità",
    "Contrast": "Contrasto",
    "Saturation": "Saturazione",
    "Hue": "Tonalità",
    "Red": "Rosso",
    "Green": "Verde",
    "Blue": "Blu",
    "Yellow": "Giallo",
    "Orange": "Arancione",
    "Purple": "Viola",
    "Pink": "Rosa",
    "Brown": "Marrone",
    "Gray": "Grigio",
    "Black": "Nero",
    "White": "Bianco",
    "Transparent": "Trasparente",
    "Visible": "Visibile",
    "Hidden": "Nascosto",
    "Show": "Mostra",
    "Hide": "Nascondi",
    "Toggle": "Attiva/Disattiva",
    "Enable": "Abilita",
    "Disable": "Disabilita",
    "Activate": "Attiva",
    "Deactivate": "Disattiva",
    "Turn On": "Accendi",
    "Turn Off": "Spegni",
    "Lock": "Blocca",
    "Unlock": "Sblocca",
    "Secure": "Proteggi",
    "Protect": "Proteggi",
    "Allow": "Consenti",
    "Deny": "Nega",
    "Grant": "Concedi",
    "Revoke": "Revoca",
    "Authorize": "Autorizza",
    "Authenticate": "Autentica",
    "Verify": "Verifica",
    "Validate": "Valida",
    "Check": "Controlla",
    "Confirm": "Conferma",
    "Approve": "Approva",
    "Reject": "Rifiuta",
    "Accept": "Accetta",
    "Decline": "Declina",
    "Agree": "Accetta",
    "Disagree": "Non accetta",
    "Consent": "Consenso",
    "Opt In": "Accetta",
    "Opt Out": "Rifiuta",
    "Sign": "Firma",
    "Signature": "Firma",
    "Seal": "Sigillo",
    "Stamp": "Timbro",
    "Mark": "Segna",
    "Flag": "Segnala",
    "Highlight": "Evidenzia",
    "Pin": "Fissa",
    "Unpin": "Sblocca",
    "Star": "Stella",
    "Unstar": "Rimuovi stella",
    "Follow": "Segui",
    "Unfollow": "Smetti di seguire",
    "Watch": "Osserva",
    "Unwatch": "Non osservare",
    "Mute": "Silenzia",
    "Unmute": "Riattiva audio",
    "Block": "Blocca",
    "Unblock": "Sblocca",
    "Report": "Segnala",
    "Spam": "Spam",
    "Archive": "Archivia",
    "Unarchive": "Disarchivia",
    "Trash": "Cestino",
    "Restore": "Ripristina",
    "Permanent": "Permanente",
    "Temporary": "Temporaneo",
    "Draft": "Bozza",
    "Final": "Finale",
    "Original": "Originale",
    "Copy": "Copia",
    "Version": "Versione",
    "Revision": "Revisione",
    "Change": "Modifica",
    "Difference": "Differenza",
    "Compare": "Confronta",
    "Merge": "Unisci",
    "Conflict": "Conflitto",
    "Resolve": "Risolvi",
    "Undo": "Annulla",
    "Redo": "Ripeti",
    "Revert": "Ripristina",
    "Rollback": "Rollback",
    "Branch": "Ramo",
    "Fork": "Fork",
    "Pull": "Pull",
    "Push": "Push",
    "Commit": "Commit",
    "Checkout": "Checkout",
    "Tag": "Tag",
    "Release": "Rilascio",
    "Deploy": "Distribuisci",
    "Build": "Compila",
    "Compile": "Compila",
    "Package": "Pacchetto",
    "Bundle": "Bundle",
    "Minify": "Minifica",
    "Optimize": "Ottimizza",
    "Improve": "Migliora",
    "Enhance": "Migliora",
    "Fix": "Correggi",
    "Bug": "Bug",
    "Issue": "Problema",
    "Problem": "Problema",
    "Solution": "Soluzione",
    "Workaround": "Soluzione alternativa",
    "Patch": "Patch",
    "Hotfix": "Hotfix",
    "Maintenance": "Manutenzione",
    "Support": "Supporto",
    "Service": "Servizio",
    "Assistance": "Assistenza",
    "Help": "Aiuto",
    "Guide": "Guida",
    "Tutorial": "Tutorial",
    "Documentation": "Documentazione",
    "Manual": "Manuale",
    "Handbook": "Manuale",
    "Reference": "Riferimento",
    "Resource": "Risorsa",
    "Resources": "Risorse",
    "Tool": "Strumento",
    "Tools": "Strumenti",
    "Utility": "Utilità",
    "Utilities": "Utilità",
    "Helper": "Helper",
    "Assistant": "Assistente",
    "Agent": "Agente",
    "Bot": "Bot",
    "Robot": "Robot",
    "AI": "IA",
    "Artificial Intelligence": "Intelligenza Artificiale",
    "Machine Learning": "Machine Learning",
    "Deep Learning": "Deep Learning",
    "Neural Network": "Rete Neurale",
    "Algorithm": "Algoritmo",
    "Model": "Modello",
    "Train": "Addestra",
    "Predict": "Prevedi",
    "Classify": "Classifica",
    "Cluster": "Raggruppa",
    "Analyze": "Analizza",
    "Process": "Elabora",
    "Compute": "Calcola",
    "Calculate": "Calcola",
    "Measure": "Misura",
    "Evaluate": "Valuta",
    "Assess": "Valuta",
    "Score": "Punteggio",
    "Rate": "Valuta",
    "Rank": "Classifica",
    "Grade": "Voto",
    "Level": "Livello",
    "Tier": "Livello",
    "Priority": "Priorità",
    "Importance": "Importanza",
    "Urgency": "Urgenza",
    "Severity": "Gravità",
    "Impact": "Impatto",
    "Risk": "Rischio",
    "Threat": "Minaccia",
    "Vulnerability": "Vulnerabilità",
    "Security": "Sicurezza",
    "Safety": "Sicurezza",
    "Protection": "Protezione",
    "Defense": "Difesa",
    "Guard": "Guardia",
    "Shield": "Scudo",
    "Firewall": "Firewall",
    "Antivirus": "Antivirus",
    "Scan": "Scansiona",
    "Detect": "Rileva",
    "Identify": "Identifica",
    "Recognize": "Riconosci",
    "Discover": "Scopri",
    "Explore": "Esplora",
    "Search": "Cerca",
    "Find": "Trova",
    "Locate": "Individua",
    "Track": "Traccia",
    "Monitor": "Monitora",
    "Watch": "Osserva",
    "Observe": "Osserva",
    "Inspect": "Ispeziona",
    "Examine": "Esamina",
    "Review": "Rivedi",
    "Audit": "Controlla",
    "Verify": "Verifica",
    "Test": "Testa",
    "Try": "Prova",
    "Experiment": "Esperimento",
    "Demo": "Demo",
    "Sample": "Esempio",
    "Example": "Esempio",
    "Instance": "Istanza",
    "Case": "Caso",
    "Scenario": "Scenario",
    "Situation": "Situazione",
    "Condition": "Condizione",
    "State": "Stato",
    "Mode": "Modalità",
    "Option": "Opzione",
    "Choice": "Scelta",
    "Alternative": "Alternativa",
    "Possibility": "Possibilità",
    "Opportunity": "Opportunità",
    "Chance": "Possibilità",
    "Probability": "Probabilità",
    "Likelihood": "Probabilità",
    "Frequency": "Frequenza",
    "Rate": "Tasso",
    "Ratio": "Rapporto",
    "Percentage": "Percentuale",
    "Proportion": "Proporzione",
    "Share": "Quota",
    "Part": "Parte",
    "Portion": "Porzione",
    "Segment": "Segmento",
    "Fragment": "Frammento",
    "Piece": "Pezzo",
    "Unit": "Unità",
    "Component": "Componente",
    "Element": "Elemento",
    "Factor": "Fattore",
    "Aspect": "Aspetto",
    "Feature": "Caratteristica",
    "Property": "Proprietà",
    "Attribute": "Attributo",
    "Characteristic": "Caratteristica",
    "Trait": "Tratto",
    "Quality": "Qualità",
    "Standard": "Standard",
    "Criteria": "Criteri",
    "Requirement": "Requisito",
    "Specification": "Specifica",
    "Definition": "Definizione",
    "Description": "Descrizione",
    "Explanation": "Spiegazione",
    "Instruction": "Istruzione",
    "Direction": "Direzione",
    "Guidance": "Guida",
    "Advice": "Consiglio",
    "Recommendation": "Raccomandazione",
    "Suggestion": "Suggerimento",
    "Tip": "Suggerimento",
    "Hint": "Suggerimento",
    "Clue": "Indizio",
    "Note": "Nota",
    "Remark": "Osservazione",
    "Observation": "Osservazione",
    "Insight": "Intuizione",
    "Understanding": "Comprensione",
    "Knowledge": "Conoscenza",
    "Expertise": "Competenza",
    "Skill": "Abilità",
    "Ability": "Capacità",
    "Capability": "Capacità",
    "Capacity": "Capacità",
    "Power": "Potere",
    "Strength": "Forza",
    "Weakness": "Debolezza",
    "Advantage": "Vantaggio",
    "Disadvantage": "Svantaggio",
    "Pro": "Pro",
    "Con": "Contro",
    "Benefit": "Beneficio",
    "Cost": "Costo",
    "Value": "Valore",
    "Worth": "Valore",
    "Merit": "Merito",
    "Quality": "Qualità",
    "Excellence": "Eccellenza",
    "Superior": "Superiore",
    "Inferior": "Inferiore",
    "Better": "Migliore",
    "Worse": "Peggiore",
    "Best": "Migliore",
    "Worst": "Peggiore",
    "Good": "Buono",
    "Bad": "Cattivo",
    "Great": "Ottimo",
    "Poor": "Scarso",
    "Excellent": "Eccellente",
    "Terrible": "Terribile",
    "Amazing": "Straordinario",
    "Awful": "Terribile",
    "Fantastic": "Fantastico",
    "Horrible": "Orribile",
    "Wonderful": "Meraviglioso",
    "Perfect": "Perfetto",
    "Ideal": "Ideale",
    "Optimal": "Ottimale",
    "Maximum": "Massimo",
    "Minimum": "Minimo",
    "High": "Alto",
    "Low": "Basso",
    "Top": "Alto",
    "Bottom": "Basso",
    "Upper": "Superiore",
    "Lower": "Inferiore",
    "Left": "Sinistra",
    "Right": "Destra",
    "Center": "Centro",
    "Middle": "Mezzo",
    "Inside": "Interno",
    "Outside": "Esterno",
    "Internal": "Interno",
    "External": "Esterno",
    "Inner": "Interno",
    "Outer": "Esterno",
    "Front": "Fronte",
    "Back": "Retro",
    "Forward": "Avanti",
    "Backward": "Indietro",
    "Up": "Su",
    "Down": "Giù",
    "Above": "Sopra",
    "Below": "Sotto",
    "Over": "Sopra",
    "Under": "Sotto",
    "Before": "Prima",
    "After": "Dopo",
    "Prior": "Precedente",
    "Previous": "Precedente",
    "Next": "Successivo",
    "Following": "Seguente",
    "Earlier": "Precedente",
    "Later": "Successivo",
    "Soon": "Presto",
    "Now": "Ora",
    "Today": "Oggi",
    "Yesterday": "Ieri",
    "Tomorrow": "Domani",
    "Week": "Settimana",
    "Month": "Mese",
    "Year": "Anno",
    "Day": "Giorno",
    "Hour": "Ora",
    "Minute": "Minuto",
    "Second": "Secondo",
    "Morning": "Mattina",
    "Afternoon": "Pomeriggio",
    "Evening": "Sera",
    "Night": "Notte",
    "Midnight": "Mezzanotte",
    "Noon": "Mezzogiorno",
    "Dawn": "Alba",
    "Dusk": "Tramonto",
    "Sunrise": "Alba",
    "Sunset": "Tramonto",
    "Spring": "Primavera",
    "Summer": "Estate",
    "Autumn": "Autunno",
    "Fall": "Autunno",
    "Winter": "Inverno",
    "Season": "Stagione",
    "Weather": "Tempo",
    "Temperature": "Temperatura",
    "Hot": "Caldo",
    "Cold": "Freddo",
    "Warm": "Caldo",
    "Cool": "Fresco",
    "Sunny": "Soleggiato",
    "Cloudy": "Nuvoloso",
    "Rainy": "Piovoso",
    "Snowy": "Nevoso",
    "Windy": "Ventoso",
    "Stormy": "Tempestoso",
    "Clear": "Sereno",
    "Overcast": "Coperto",
    "Humidity": "Umidità",
    "Pressure": "Pressione",
    "Wind": "Vento",
    "Rain": "Pioggia",
    "Snow": "Neve",
    "Ice": "Ghiaccio",
    "Fog": "Nebbia",
    "Mist": "Foschia",
    "Cloud": "Nuvola",
    "Sky": "Cielo",
    "Sun": "Sole",
    "Moon": "Luna",
    "Star": "Stella",
    "Planet": "Pianeta",
    "Earth": "Terra",
    "World": "Mondo",
    "Universe": "Universo",
    "Space": "Spazio",
    "Time": "Tempo",
    "Place": "Luogo",
    "Location": "Posizione",
    "Position": "Posizione",
    "Area": "Area",
    "Region": "Regione",
    "Zone": "Zona",
    "District": "Distretto",
    "Neighborhood": "Quartiere",
    "Street": "Via",
    "Road": "Strada",
    "Avenue": "Viale",
    "Boulevard": "Boulevard",
    "Lane": "Vicolo",
    "Path": "Sentiero",
    "Way": "Via",
    "Route": "Percorso",
    "Direction": "Direzione",
    "North": "Nord",
    "South": "Sud",
    "East": "Est",
    "West": "Ovest",
    "Northeast": "Nordest",
    "Northwest": "Nordovest",
    "Southeast": "Sudest",
    "Southwest": "Sudovest",
    "Latitude": "Latitudine",
    "Longitude": "Longitudine",
    "Altitude": "Altitudine",
    "Elevation": "Elevazione",
    "Depth": "Profondità",
    "Distance": "Distanza",
    "Range": "Intervallo",
    "Radius": "Raggio",
    "Diameter": "Diametro",
    "Circumference": "Circonferenza",
    "Perimeter": "Perimetro",
    "Surface": "Superficie",
    "Edge": "Bordo",
    "Corner": "Angolo",
    "Side": "Lato",
    "Face": "Faccia",
    "Point": "Punto",
    "Line": "Linea",
    "Curve": "Curva",
    "Circle": "Cerchio",
    "Square": "Quadrato",
    "Rectangle": "Rettangolo",
    "Triangle": "Triangolo",
    "Polygon": "Poligono",
    "Shape": "Forma",
    "Form": "Forma",
    "Structure": "Struttura",
    "Building": "Edificio",
    "House": "Casa",
    "Home": "Casa",
    "Office": "Ufficio",
    "Store": "Negozio",
    "Shop": "Negozio",
    "Market": "Mercato",
    "Mall": "Centro commerciale",
    "Center": "Centro",
    "Complex": "Complesso",
    "Facility": "Struttura",
    "Site": "Sito",
    "Property": "Proprietà",
    "Estate": "Patrimonio",
    "Land": "Terreno",
    "Plot": "Lotto",
    "Lot": "Lotto",
    "Parcel": "Parcella",
    "Acre": "Acro",
    "Hectare": "Ettaro",
    "Square Meter": "Metro quadrato",
    "Square Foot": "Piede quadrato",
    "Meter": "Metro",
    "Foot": "Piede",
    "Inch": "Pollice",
    "Centimeter": "Centimetro",
    "Millimeter": "Millimetro",
    "Kilometer": "Chilometro",
    "Mile": "Miglio",
    "Yard": "Iarda",
    "Gram": "Grammo",
    "Kilogram": "Chilogrammo",
    "Pound": "Libbra",
    "Ounce": "Oncia",
    "Ton": "Tonnellata",
    "Liter": "Litro",
    "Milliliter": "Millilitro",
    "Gallon": "Gallone",
    "Quart": "Quarto",
    "Pint": "Pinta",
    "Cup": "Tazza",
    "Tablespoon": "Cucchiaio",
    "Teaspoon": "Cucchiaino",
    "Degree": "Grado",
    "Celsius": "Celsius",
    "Fahrenheit": "Fahrenheit",
    "Kelvin": "Kelvin",
    "Percent": "Percento",
    "Decimal": "Decimale",
    "Fraction": "Frazione",
    "Integer": "Intero",
    "Float": "Float",
    "Double": "Double",
    "String": "Stringa",
    "Boolean": "Booleano",
    "Array": "Array",
    "List": "Lista",
    "Set": "Set",
    "Map": "Mappa",
    "Dictionary": "Dizionario",
    "Collection": "Collezione",
    "Sequence": "Sequenza",
    "Series": "Serie",
    "Range": "Intervallo",
    "Interval": "Intervallo",
    "Span": "Intervallo",
    "Period": "Periodo",
    "Term": "Termine",
    "Phase": "Fase",
    "Stage": "Fase",
    "Step": "Passo",
    "Process": "Processo",
    "Procedure": "Procedura",
    "Method": "Metodo",
    "Approach": "Approccio",
    "Strategy": "Strategia",
    "Plan": "Piano",
    "Scheme": "Schema",
    "System": "Sistema",
    "Framework": "Framework",
    "Architecture": "Architettura",
    "Infrastructure": "Infrastruttura",
    "Network": "Rete",
    "Connection": "Connessione",
    "Link": "Collegamento",
    "Relationship": "Relazione",
    "Association": "Associazione",
    "Dependency": "Dipendenza",
    "Reference": "Riferimento",
    "Pointer": "Puntatore",
    "Index": "Indice",
    "Identifier": "Identificatore",
    "ID": "ID",
    "Code": "Codice",
    "Symbol": "Simbolo",
    "Sign": "Segno",
    "Mark": "Marchio",
    "Logo": "Logo",
    "Brand": "Marca",
    "Trademark": "Marchio registrato",
    "Copyright": "Copyright",
    "License": "Licenza",
    "Agreement": "Accordo",
    "Contract": "Contratto",
    "Terms of Service": "Termini di servizio",
    "Privacy Policy": "Informativa sulla privacy",
    "Legal": "Legale",
    "Law": "Legge",
    "Regulation": "Regolamento",
    "Rule": "Regola",
    "Policy": "Politica",
    "Guideline": "Linea guida",
    "Standard": "Standard",
    "Protocol": "Protocollo",
    "Format": "Formato",
    "Specification": "Specifica",
    "Documentation": "Documentazione",
    "Instruction": "Istruzione",
    "Manual": "Manuale",
    "Guide": "Guida",
    "Tutorial": "Tutorial",
    "Course": "Corso",
    "Lesson": "Lezione",
    "Training": "Formazione",
    "Education": "Educazione",
    "Learning": "Apprendimento",
    "Teaching": "Insegnamento",
    "Study": "Studio",
    "Research": "Ricerca",
    "Investigation": "Indagine",
    "Analysis": "Analisi",
    "Examination": "Esame",
    "Assessment": "Valutazione",
    "Evaluation": "Valutazione",
    "Judgment": "Giudizio",
    "Decision": "Decisione",
    "Choice": "Scelta",
    "Selection": "Selezione",
    "Pick": "Scelta",
    "Preference": "Preferenza",
    "Favorite": "Preferito",
    "Like": "Mi piace",
    "Love": "Amore",
    "Hate": "Odio",
    "Dislike": "Non mi piace",
    "Interest": "Interesse",
    "Hobby": "Hobby",
    "Passion": "Passione",
    "Enthusiasm": "Entusiasmo",
    "Excitement": "Eccitazione",
    "Joy": "Gioia",
    "Happiness": "Felicità",
    "Sadness": "Tristezza",
    "Anger": "Rabbia",
    "Fear": "Paura",
    "Surprise": "Sorpresa",
    "Disgust": "Disgusto",
    "Emotion": "Emozione",
    "Feeling": "Sentimento",
    "Mood": "Umore",
    "Attitude": "Atteggiamento",
    "Behavior": "Comportamento",
    "Action": "Azione",
    "Reaction": "Reazione",
    "Response": "Risposta",
    "Feedback": "Feedback",
    "Input": "Input",
    "Output": "Output",
    "Result": "Risultato",
    "Effect": "Effetto",
    "Consequence": "Conseguenza",
    "Impact": "Impatto",
    "Influence": "Influenza",
    "Power": "Potere",
    "Control": "Controllo",
    "Management": "Gestione",
    "Administration": "Amministrazione",
    "Leadership": "Leadership",
    "Direction": "Direzione",
    "Supervision": "Supervisione",
    "Oversight": "Supervisione",
    "Monitoring": "Monitoraggio",
    "Tracking": "Tracciamento",
    "Recording": "Registrazione",
    "Logging": "Registrazione",
    "Documentation": "Documentazione",
    "Record": "Record",
    "File": "File",
    "Document": "Documento",
    "Paper": "Documento",
    "Form": "Modulo",
    "Application": "Applicazione",
    "Request": "Richiesta",
    "Submission": "Invio",
    "Entry": "Voce",
    "Registration": "Registrazione",
    "Enrollment": "Iscrizione",
    "Membership": "Abbonamento",
    "Subscription": "Abbonamento",
    "Service": "Servizio",
    "Product": "Prodotto",
    "Item": "Articolo",
    "Good": "Bene",
    "Goods": "Beni",
    "Merchandise": "Merce",
    "Commodity": "Merce",
    "Material": "Materiale",
    "Supply": "Fornitura",
    "Resource": "Risorsa",
    "Asset": "Risorsa",
    "Property": "Proprietà",
    "Possession": "Possesso",
    "Belonging": "Appartenenza",
    "Ownership": "Proprietà",
    "Title": "Titolo",
    "Right": "Diritto",
    "Claim": "Richiesta",
    "Interest": "Interesse",
    "Share": "Quota",
    "Stake": "Partecipazione",
    "Investment": "Investimento",
    "Capital": "Capitale",
    "Fund": "Fondo",
    "Money": "Denaro",
    "Cash": "Contanti",
    "Currency": "Valuta",
    "Dollar": "Dollaro",
    "Euro": "Euro",
    "Pound": "Sterlina",
    "Yen": "Yen",
    "Franc": "Franco",
    "Swiss Franc": "Franco svizzero",
    "CHF": "CHF",
    "USD": "USD",
    "EUR": "EUR",
    "GBP": "GBP",
    "JPY": "JPY",
    # Tax-specific terms
    "Tax": "Imposta",
    "Taxes": "Imposte",
    "Tax Return": "Dichiarazione dei redditi",
    "Tax Filing": "Dichiarazione fiscale",
    "Tax Year": "Anno fiscale",
    "Taxable Income": "Reddito imponibile",
    "Tax Deduction": "Deduzione fiscale",
    "Tax Credit": "Credito d'imposta",
    "Tax Rate": "Aliquota fiscale",
    "Tax Bracket": "Scaglione fiscale",
    "Federal Tax": "Imposta federale",
    "State Tax": "Imposta statale",
    "Local Tax": "Imposta locale",
    "Income Tax": "Imposta sul reddito",
    "Property Tax": "Imposta sulla proprietà",
    "Sales Tax": "Imposta sulle vendite",
    "Capital Gains": "Plusvalenze",
    "Withholding": "Ritenuta",
    "Exemption": "Esenzione",
    "Allowance": "Indennità",
    "Refund": "Rimborso",
    "Owed": "Dovuto",
    "Due": "Dovuto",
    "Penalty": "Penalità",
    "Interest": "Interesse",
    "Late Fee": "Mora",
    "Extension": "Proroga",
    "Deadline": "Scadenza",
    "Filing Status": "Stato di presentazione",
    "Single": "Singolo",
    "Married": "Coniugato",
    "Joint": "Congiunto",
    "Separate": "Separato",
    "Head of Household": "Capofamiglia",
    "Widow": "Vedovo",
    "Widower": "Vedovo",
    "Dependent": "Dipendente",
    "Dependents": "Dipendenti",
    "Spouse": "Coniuge",
    "Child": "Figlio",
    "Children": "Figli",
    "Parent": "Genitore",
    "Parents": "Genitori",
    "Guardian": "Tutore",
    "Social Security": "Previdenza sociale",
    "Medicare": "Medicare",
    "Retirement": "Pensione",
    "Pension": "Pensione",
    "IRA": "IRA",
    "401k": "401k",
    "Investment Income": "Reddito da investimenti",
    "Dividend": "Dividendo",
    "Dividends": "Dividendi",
    "Interest Income": "Reddito da interessi",
    "Rental Income": "Reddito da locazione",
    "Business Income": "Reddito d'impresa",
    "Self-Employment": "Lavoro autonomo",
    "Freelance": "Freelance",
    "Contractor": "Appaltatore",
    "Employee": "Dipendente",
    "Employer": "Datore di lavoro",
    "W-2": "W-2",
    "1099": "1099",
    "Schedule": "Prospetto",
    "Form": "Modulo",
    "Worksheet": "Foglio di lavoro",
    "Instruction": "Istruzione",
    "Publication": "Pubblicazione",
    "IRS": "IRS",
    "Tax Authority": "Autorità fiscale",
    "Tax Office": "Ufficio delle imposte",
    "Tax Advisor": "Consulente fiscale",
    "Tax Consultant": "Consulente fiscale",
    "Accountant": "Commercialista",
    "CPA": "Commercialista certificato",
    "Tax Preparer": "Preparatore fiscale",
    "Tax Professional": "Professionista fiscale",
    "E-File": "Presentazione elettronica",
    "Electronic Filing": "Presentazione elettronica",
    "Paper Filing": "Presentazione cartacea",
    "Direct Deposit": "Deposito diretto",
    "Bank Account": "Conto bancario",
    "Routing Number": "Numero di routing",
    "Account Number": "Numero di conto",
    "Check": "Assegno",
    "Money Order": "Vaglia postale",
    "Payment Plan": "Piano di pagamento",
    "Installment": "Rata",
    "Quarterly": "Trimestrale",
    "Estimated Tax": "Imposta stimata",
    "Audit": "Controllo",
    "Examination": "Esame",
    "Notice": "Avviso",
    "Letter": "Lettera",
    "Correspondence": "Corrispondenza",
    "Appeal": "Ricorso",
    "Amendment": "Rettifica",
    "Amended Return": "Dichiarazione rettificata",
    "Prior Year": "Anno precedente",
    "Current Year": "Anno corrente",
    "Previous": "Precedente",
    "Upload Document": "Carica documento",
    "Attach File": "Allega file",
    "Required Document": "Documento obbligatorio",
    "Optional Document": "Documento facoltativo",
    "Proof": "Prova",
    "Evidence": "Prova",
    "Receipt": "Ricevuta",
    "Invoice": "Fattura",
    "Statement": "Estratto conto",
    "Record": "Registro",
    "Documentation": "Documentazione",
    "Swiss Tax": "Imposta svizzera",
    "Canton": "Cantone",
    "Municipal": "Comunale",
    "Federal": "Federale",
    "Direct Federal Tax": "Imposta federale diretta",
    "Wealth Tax": "Imposta sulla sostanza",
    "Value Added Tax": "Imposta sul valore aggiunto",
    "VAT": "IVA",
    "Deduction": "Deduzione",
    "Allowable Expense": "Spesa deducibile",
    "Non-Deductible": "Non deducibile",
    "Taxable": "Imponibile",
    "Non-Taxable": "Non imponibile",
    "Gross Income": "Reddito lordo",
    "Net Income": "Reddito netto",
    "Adjusted Gross Income": "Reddito lordo rettificato",
    "Standard Deduction": "Deduzione standard",
    "Itemized Deduction": "Deduzione dettagliata",
    "Personal Exemption": "Esenzione personale",
    "Charitable Contribution": "Contributo di beneficenza",
    "Medical Expense": "Spesa medica",
    "Education Expense": "Spesa per l'istruzione",
    "Work-Related Expense": "Spesa relativa al lavoro",
    "Home Office": "Ufficio domestico",
    "Business Expense": "Spesa aziendale",
    "Travel Expense": "Spesa di viaggio",
    "Meal Expense": "Spesa per pasti",
    "Entertainment Expense": "Spesa di intrattenimento",
    "Vehicle Expense": "Spesa per veicoli",
    "Mileage": "Chilometraggio",
    "Depreciation": "Ammortamento",
    "Amortization": "Ammortamento",
    "Interest": "Interesse",
    "Mortgage Interest": "Interessi ipotecari",
    "Student Loan Interest": "Interessi sul prestito studentesco",
    "Real Estate": "Immobiliare",
    "Personal Property": "Proprietà personale",
    "Asset": "Bene",
    "Liability": "Passività",
    "Equity": "Patrimonio netto",
    "Balance Sheet": "Bilancio",
    "Income Statement": "Conto economico",
    "Cash Flow": "Flusso di cassa",
    "Financial Statement": "Rendiconto finanziario",
    "Accounting": "Contabilità",
    "Bookkeeping": "Tenuta dei libri contabili",
    "Journal": "Giornale",
    "Ledger": "Libro mastro",
    "Trial Balance": "Bilancio di verifica",
    "Reconciliation": "Riconciliazione",
    "Accrual": "Competenza",
    "Cash Basis": "Base di cassa",
    "Fiscal Year": "Anno fiscale",
    "Calendar Year": "Anno solare",
    "Quarter": "Trimestre",
    "Period": "Periodo",
    "Closing": "Chiusura",
    "Opening": "Apertura",
    "Beginning": "Inizio",
    "Ending": "Fine",
    "Year-End": "Fine anno",
    "Mid-Year": "Metà anno",
    "Interim": "Intermedio",
    "Annual": "Annuale",
    "Monthly": "Mensile",
    "Weekly": "Settimanale",
    "Daily": "Giornaliero",
    "Biweekly": "Bisettimanale",
    "Semiannual": "Semestrale",
    "Biannual": "Biennale",
    "Per Annum": "All'anno",
    "Per Month": "Al mese",
    "Per Week": "A settimana",
    "Per Day": "Al giorno",
    "Per Hour": "All'ora",
    "Hourly": "Orario",
    "Salary": "Stipendio",
    "Wage": "Salario",
    "Compensation": "Compenso",
    "Bonus": "Bonus",
    "Commission": "Commissione",
    "Tip": "Mancia",
    "Tips": "Mance",
    "Gratuity": "Mancia",
    "Benefits": "Benefici",
    "Fringe Benefit": "Beneficio accessorio",
    "Health Insurance": "Assicurazione sanitaria",
    "Life Insurance": "Assicurazione sulla vita",
    "Disability Insurance": "Assicurazione per invalidità",
    "Unemployment": "Disoccupazione",
    "Workers Compensation": "Compenso per i lavoratori",
    "Vacation": "Vacanza",
    "Sick Leave": "Congedo per malattia",
    "Personal Leave": "Congedo personale",
    "Maternity Leave": "Congedo di maternità",
    "Paternity Leave": "Congedo di paternità",
    "Family Leave": "Congedo familiare",
    "Holiday": "Festività",
    "Time Off": "Tempo libero",
    "Paid": "Pagato",
    "Unpaid": "Non pagato",
    "Overtime": "Straordinario",
    "Regular": "Regolare",
    "Full-Time": "Tempo pieno",
    "Part-Time": "Part-time",
    "Temporary": "Temporaneo",
    "Permanent": "Permanente",
    "Contract": "Contratto",
    "Seasonal": "Stagionale",
    "Intern": "Stagista",
    "Apprentice": "Apprendista",
    "Trainee": "Tirocinante",
    "Volunteer": "Volontario",
    "Consultant": "Consulente",
    "Professional": "Professionista",
    "Specialist": "Specialista",
    "Expert": "Esperto",
    "Technician": "Tecnico",
    "Engineer": "Ingegnere",
    "Developer": "Sviluppatore",
    "Designer": "Designer",
    "Analyst": "Analista",
    "Manager": "Manager",
    "Director": "Direttore",
    "Executive": "Dirigente",
    "Officer": "Funzionario",
    "President": "Presidente",
    "Vice President": "Vicepresidente",
    "CEO": "CEO",
    "CFO": "CFO",
    "CTO": "CTO",
    "COO": "COO",
    "Chairman": "Presidente",
    "Board": "Consiglio",
    "Committee": "Comitato",
    "Member": "Membro",
    "Partner": "Partner",
    "Shareholder": "Azionista",
    "Stakeholder": "Parte interessata",
    "Investor": "Investitore",
    "Creditor": "Creditore",
    "Debtor": "Debitore",
    "Vendor": "Fornitore",
    "Supplier": "Fornitore",
    "Customer": "Cliente",
    "Client": "Cliente",
    "Consumer": "Consumatore",
    "Buyer": "Acquirente",
    "Seller": "Venditore",
    "Merchant": "Commerciante",
    "Retailer": "Rivenditore",
    "Wholesaler": "Grossista",
    "Distributor": "Distributore",
    "Manufacturer": "Produttore",
    "Producer": "Produttore",
    "Provider": "Fornitore",
    "Landlord": "Proprietario",
    "Tenant": "Inquilino",
    "Lessee": "Locatario",
    "Lessor": "Locatore",
    "Renter": "Affittuario",
    "Owner": "Proprietario",
    "Occupant": "Occupante",
    "Resident": "Residente",
    "Citizen": "Cittadino",
    "National": "Nazionale",
    "Foreigner": "Straniero",
    "Alien": "Straniero",
    "Immigrant": "Immigrato",
    "Emigrant": "Emigrato",
    "Expatriate": "Espatriato",
    "Refugee": "Rifugiato",
    "Asylum": "Asilo",
    "Visa": "Visto",
    "Passport": "Passaporto",
    "Permit": "Permesso",
    "Authorization": "Autorizzazione",
    "Certification": "Certificazione",
    "Accreditation": "Accreditamento",
    "Qualification": "Qualifica",
    "Credential": "Credenziale",
    "Degree": "Laurea",
    "Diploma": "Diploma",
    "Certificate": "Certificato",
    "License": "Licenza",
    "Registration": "Registrazione",
    "Membership": "Iscrizione",
    "Affiliation": "Affiliazione",
    "Association": "Associazione",
    "Society": "Società",
    "Club": "Club",
    "Union": "Sindacato",
    "Guild": "Corporazione",
    "League": "Lega",
    "Alliance": "Alleanza",
    "Coalition": "Coalizione",
    "Federation": "Federazione",
    "Confederation": "Confederazione",
    "Institution": "Istituzione",
    "Foundation": "Fondazione",
    "Trust": "Trust",
    "Charity": "Carità",
    "Nonprofit": "No profit",
    "NGO": "ONG",
    "Government": "Governo",
    "Agency": "Agenzia",
    "Bureau": "Ufficio",
    "Ministry": "Ministero",
    "Department": "Dipartimento",
    "Division": "Divisione",
    "Branch": "Filiale",
    "Unit": "Unità",
    "Office": "Ufficio",
    "Headquarters": "Sede centrale",
    "Subsidiary": "Filiale",
    "Affiliate": "Affiliato",
    "Related Party": "Parte correlata",
    "Third Party": "Terza parte",
    "Independent": "Indipendente",
    "Objective": "Obiettivo",
    "Neutral": "Neutrale",
    "Impartial": "Imparziale",
    "Fair": "Equo",
    "Equal": "Uguale",
    "Equivalent": "Equivalente",
    "Same": "Stesso",
    "Similar": "Simile",
    "Different": "Diverso",
    "Unique": "Unico",
    "Special": "Speciale",
    "Specific": "Specifico",
    "General": "Generale",
    "Common": "Comune",
    "Rare": "Raro",
    "Unusual": "Insolito",
    "Normal": "Normale",
    "Standard": "Standard",
    "Custom": "Personalizzato",
    "Default": "Predefinito",
    "Automatic": "Automatico",
    "Manual": "Manuale",
    "Simple": "Semplice",
    "Complex": "Complesso",
    "Easy": "Facile",
    "Difficult": "Difficile",
    "Hard": "Difficile",
    "Challenging": "Impegnativo",
    "Advanced": "Avanzato",
    "Basic": "Base",
    "Beginner": "Principiante",
    "Intermediate": "Intermedio",
    "Expert": "Esperto",
    "Professional": "Professionale",
    "Amateur": "Amatoriale",
    "Novice": "Novizio",
    "Experienced": "Esperto",
    "Skilled": "Abile",
    "Qualified": "Qualificato",
    "Certified": "Certificato",
    "Licensed": "Autorizzato",
    "Authorized": "Autorizzato",
    "Approved": "Approvato",
    "Verified": "Verificato",
    "Validated": "Validato",
    "Confirmed": "Confermato",
    "Guaranteed": "Garantito",
    "Assured": "Assicurato",
    "Insured": "Assicurato",
    "Protected": "Protetto",
    "Secured": "Protetto",
    "Safe": "Sicuro",
    "Secure": "Sicuro",
    "Reliable": "Affidabile",
    "Trustworthy": "Affidabile",
    "Dependable": "Affidabile",
    "Consistent": "Coerente",
    "Stable": "Stabile",
    "Steady": "Costante",
    "Constant": "Costante",
    "Continuous": "Continuo",
    "Ongoing": "In corso",
    "Progressive": "Progressivo",
    "Incremental": "Incrementale",
    "Gradual": "Graduale",
    "Sudden": "Improvviso",
    "Immediate": "Immediato",
    "Instant": "Istantaneo",
    "Quick": "Veloce",
    "Fast": "Veloce",
    "Rapid": "Rapido",
    "Swift": "Veloce",
    "Slow": "Lento",
    "Delayed": "Ritardato",
    "Postponed": "Posticipato",
    "Scheduled": "Programmato",
    "Planned": "Pianificato",
    "Expected": "Previsto",
    "Anticipated": "Previsto",
    "Forecast": "Previsione",
    "Predicted": "Previsto",
    "Estimated": "Stimato",
    "Calculated": "Calcolato",
    "Computed": "Calcolato",
    "Determined": "Determinato",
    "Derived": "Derivato",
    "Obtained": "Ottenuto",
    "Acquired": "Acquisito",
    "Received": "Ricevuto",
    "Collected": "Raccolto",
    "Gathered": "Raccolto",
    "Compiled": "Compilato",
    "Assembled": "Assemblato",
    "Combined": "Combinato",
    "Integrated": "Integrato",
    "Unified": "Unificato",
    "Consolidated": "Consolidato",
    "Aggregated": "Aggregato",
    "Total": "Totale",
    "Overall": "Complessivo",
    "Complete": "Completo",
    "Full": "Completo",
    "Entire": "Intero",
    "Whole": "Intero",
    "Partial": "Parziale",
    "Incomplete": "Incompleto",
    "Missing": "Mancante",
    "Absent": "Assente",
    "Present": "Presente",
    "Existing": "Esistente",
    "Current": "Corrente",
    "Actual": "Effettivo",
    "Real": "Reale",
    "Virtual": "Virtuale",
    "Digital": "Digitale",
    "Electronic": "Elettronico",
    "Online": "Online",
    "Offline": "Offline",
    "Remote": "Remoto",
    "Local": "Locale",
    "Global": "Globale",
    "International": "Internazionale",
    "Domestic": "Nazionale",
    "Foreign": "Estero",
    "Abroad": "All'estero",
    "Overseas": "Oltremare",
    "Cross-Border": "Transfrontaliero",
    "Import": "Importazione",
    "Export": "Esportazione",
    "Trade": "Commercio",
    "Commerce": "Commercio",
    "Business": "Affari",
    "Enterprise": "Impresa",
    "Corporation": "Società",
    "Company": "Azienda",
    "Firm": "Ditta",
    "Partnership": "Società di persone",
    "LLC": "SRL",
    "LTD": "SRL",
    "Inc": "Inc",
    "Incorporated": "Incorporata",
    "Limited": "Limitata",
    "Private": "Privata",
    "Public": "Pubblica",
    "Listed": "Quotata",
    "Unlisted": "Non quotata",
    "Stock": "Azione",
    "Share": "Azione",
    "Equity": "Capitale proprio",
    "Security": "Titolo",
    "Bond": "Obbligazione",
    "Debt": "Debito",
    "Loan": "Prestito",
    "Credit": "Credito",
    "Financing": "Finanziamento",
    "Funding": "Finanziamento",
    "Grant": "Sovvenzione",
    "Subsidy": "Sussidio",
    "Allowance": "Indennità",
    "Stipend": "Stipendio",
    "Scholarship": "Borsa di studio",
    "Fellowship": "Borsa di studio",
    "Award": "Premio",
    "Prize": "Premio",
    "Reward": "Ricompensa",
    "Incentive": "Incentivo",
    "Bonus": "Bonus",
    "Premium": "Premio",
    "Surcharge": "Supplemento",
    "Fee": "Tariffa",
    "Charge": "Addebito",
    "Rate": "Tariffa",
    "Fare": "Tariffa",
    "Toll": "Pedaggio",
    "Duty": "Dazio",
    "Tariff": "Tariffa",
    "Levy": "Prelievo",
    "Assessment": "Accertamento",
    "Fine": "Multa",
    "Penalty": "Penalità",
    "Forfeiture": "Decadenza",
    "Confiscation": "Confisca",
    "Seizure": "Sequestro",
    "Attachment": "Sequestro",
    "Lien": "Vincolo",
    "Encumbrance": "Gravame",
    "Burden": "Onere",
    "Obligation": "Obbligo",
    "Duty": "Dovere",
    "Responsibility": "Responsabilità",
    "Liability": "Responsabilità",
    "Accountability": "Responsabilità",
    "Answer": "Risposta",
    "Solution": "Soluzione",
    "Resolution": "Risoluzione",
    "Settlement": "Accordo",
    "Compromise": "Compromesso",
    "Negotiation": "Negoziazione",
    "Discussion": "Discussione",
    "Debate": "Dibattito",
    "Argument": "Argomento",
    "Dispute": "Controversia",
    "Conflict": "Conflitto",
    "Disagreement": "Disaccordo",
    "Controversy": "Controversia",
    "Issue": "Questione",
    "Matter": "Questione",
    "Subject": "Argomento",
    "Topic": "Argomento",
    "Theme": "Tema",
    "Focus": "Focus",
    "Emphasis": "Enfasi",
    "Highlight": "Evidenziazione",
    "Priority": "Priorità",
    "Main": "Principale",
    "Primary": "Primario",
    "Secondary": "Secondario",
    "Tertiary": "Terziario",
    "Major": "Maggiore",
    "Minor": "Minore",
    "Significant": "Significativo",
    "Insignificant": "Insignificante",
    "Important": "Importante",
    "Unimportant": "Non importante",
    "Critical": "Critico",
    "Essential": "Essenziale",
    "Necessary": "Necessario",
    "Vital": "Vitale",
    "Crucial": "Cruciale",
    "Key": "Chiave",
    "Central": "Centrale",
    "Core": "Fondamentale",
    "Fundamental": "Fondamentale",
    "Basic": "Base",
    "Elementary": "Elementare",
    "Rudimentary": "Rudimentale",
    "Preliminary": "Preliminare",
    "Introductory": "Introduttivo",
    "Initial": "Iniziale",
    "Final": "Finale",
    "Ultimate": "Finale",
    "Conclusive": "Conclusivo",
    "Definitive": "Definitivo",
    "Absolute": "Assoluto",
    "Relative": "Relativo",
    "Comparative": "Comparativo",
    "Superlative": "Superlativo",
    "Positive": "Positivo",
    "Negative": "Negativo",
    "Neutral": "Neutrale",
    "Favorable": "Favorevole",
    "Unfavorable": "Sfavorevole",
    "Advantageous": "Vantaggioso",
    "Disadvantageous": "Svantaggioso",
    "Beneficial": "Benefico",
    "Detrimental": "Dannoso",
    "Harmful": "Dannoso",
    "Useful": "Utile",
    "Useless": "Inutile",
    "Valuable": "Prezioso",
    "Worthless": "Senza valore",
    "Priceless": "Inestimabile",
    "Invaluable": "Inestimabile",
    "Precious": "Prezioso",
    "Cheap": "Economico",
    "Expensive": "Costoso",
    "Costly": "Costoso",
    "Affordable": "Accessibile",
    "Reasonable": "Ragionevole",
    "Unreasonable": "Irragionevole",
    "Excessive": "Eccessivo",
    "Moderate": "Moderato",
    "Substantial": "Sostanziale",
    "Considerable": "Considerevole",
    "Significant": "Significativo",
    "Notable": "Notevole",
    "Remarkable": "Notevole",
    "Outstanding": "Eccezionale",
    "Exceptional": "Eccezionale",
    "Extraordinary": "Straordinario",
    "Ordinary": "Ordinario",
    "Regular": "Regolare",
    "Typical": "Tipico",
    "Usual": "Usuale",
    "Unusual": "Insolito",
    "Atypical": "Atipico",
    "Abnormal": "Anormale",
    "Normal": "Normale",
    "Average": "Medio",
    "Median": "Mediano",
    "Mean": "Media",
    "Mode": "Moda",
    "Standard Deviation": "Deviazione standard",
    "Variance": "Varianza",
    "Distribution": "Distribuzione",
    "Probability": "Probabilità",
    "Statistics": "Statistiche",
    "Data": "Dati",
    "Information": "Informazioni",
    "Knowledge": "Conoscenza",
    "Wisdom": "Saggezza",
    "Intelligence": "Intelligenza",
    "Understanding": "Comprensione",
    "Comprehension": "Comprensione",
    "Awareness": "Consapevolezza",
    "Consciousness": "Coscienza",
    "Recognition": "Riconoscimento",
    "Acknowledgment": "Riconoscimento",
    "Appreciation": "Apprezzamento",
    "Gratitude": "Gratitudine",
    "Thanks": "Grazie",
    "Thank You": "Grazie",
    "Welcome": "Benvenuto",
    "Hello": "Ciao",
    "Hi": "Ciao",
    "Goodbye": "Arrivederci",
    "Bye": "Ciao",
    "Farewell": "Addio",
    "See You": "Ci vediamo",
    "Take Care": "Abbi cura di te",
    "Good Luck": "Buona fortuna",
    "Congratulations": "Congratulazioni",
    "Well Done": "Ben fatto",
    "Excellent": "Eccellente",
    "Great Job": "Ottimo lavoro",
    "Nice Work": "Bel lavoro",
    "Good Work": "Buon lavoro",
    "Keep It Up": "Continua così",
    "Please": "Per favore",
    "Excuse Me": "Mi scusi",
    "Pardon": "Scusa",
    "Sorry": "Scusa",
    "Apology": "Scuse",
    "Forgive": "Perdona",
    "Forgiveness": "Perdono",
    "Mercy": "Pietà",
    "Compassion": "Compassione",
    "Sympathy": "Simpatia",
    "Empathy": "Empatia",
    "Understanding": "Comprensione",
    "Patience": "Pazienza",
    "Tolerance": "Tolleranza",
    "Respect": "Rispetto",
    "Honor": "Onore",
    "Dignity": "Dignità",
    "Pride": "Orgoglio",
    "Humility": "Umiltà",
    "Modesty": "Modestia",
    "Arrogance": "Arroganza",
    "Confidence": "Fiducia",
    "Trust": "Fiducia",
    "Faith": "Fede",
    "Belief": "Credenza",
    "Hope": "Speranza",
    "Optimism": "Ottimismo",
    "Pessimism": "Pessimismo",
    "Realism": "Realismo",
    "Idealism": "Idealismo",
    "Pragmatism": "Pragmatismo",
    "Philosophy": "Filosofia",
    "Principle": "Principio",
    "Value": "Valore",
    "Ethic": "Etica",
    "Moral": "Morale",
    "Ethics": "Etica",
    "Morality": "Moralità",
    "Integrity": "Integrità",
    "Honesty": "Onestà",
    "Truth": "Verità",
    "Truthfulness": "Veridicità",
    "Sincerity": "Sincerità",
    "Authenticity": "Autenticità",
    "Genuineness": "Genuinità",
    "Legitimacy": "Legittimità",
    "Legality": "Legalità",
    "Validity": "Validità",
    "Effectiveness": "Efficacia",
    "Efficiency": "Efficienza",
    "Productivity": "Produttività",
    "Performance": "Prestazioni",
    "Achievement": "Risultato",
    "Accomplishment": "Realizzazione",
    "Success": "Successo",
    "Failure": "Fallimento",
    "Victory": "Vittoria",
    "Defeat": "Sconfitta",
    "Win": "Vittoria",
    "Loss": "Perdita",
    "Gain": "Guadagno",
    "Profit": "Profitto",
    "Benefit": "Beneficio",
    "Advantage": "Vantaggio",
    "Strength": "Forza",
    "Weakness": "Debolezza",
    "Opportunity": "Opportunità",
    "Threat": "Minaccia",
    "SWOT": "SWOT",
    "Analysis": "Analisi",
    "Evaluation": "Valutazione",
    "Assessment": "Valutazione",
    "Appraisal": "Valutazione",
    "Judgment": "Giudizio",
    "Opinion": "Opinione",
    "View": "Vista",
    "Perspective": "Prospettiva",
    "Viewpoint": "Punto di vista",
    "Standpoint": "Punto di vista",
    "Angle": "Angolo",
    "Approach": "Approccio",
    "Method": "Metodo",
    "Technique": "Tecnica",
    "Procedure": "Procedura",
    "Process": "Processo",
    "Practice": "Pratica",
    "Custom": "Costume",
    "Tradition": "Tradizione",
    "Convention": "Convenzione",
    "Norm": "Norma",
    "Standard": "Standard",
    "Benchmark": "Benchmark",
    "Criterion": "Criterio",
    "Measure": "Misura",
    "Metric": "Metrica",
    "Indicator": "Indicatore",
    "Signal": "Segnale",
    "Sign": "Segno",
    "Symptom": "Sintomo",
    "Evidence": "Prova",
    "Proof": "Prova",
    "Demonstration": "Dimostrazione",
    "Illustration": "Illustrazione",
    "Example": "Esempio",
    "Model": "Modello",
    "Prototype": "Prototipo",
    "Blueprint": "Progetto",
    "Sketch": "Schizzo",
    "Draft": "Bozza",
    "Outline": "Contorno",
    "Summary": "Riepilogo",
    "Overview": "Panoramica",
    "Synopsis": "Sinossi",
    "Abstract": "Astratto",
    "Brief": "Breve",
    "Concise": "Conciso",
    "Short": "Breve",
    "Long": "Lungo",
    "Lengthy": "Lungo",
    "Extended": "Esteso",
    "Expanded": "Espanso",
    "Detailed": "Dettagliato",
    "Comprehensive": "Completo",
    "Thorough": "Approfondito",
    "In-Depth": "Approfondito",
    "Extensive": "Esteso",
    "Broad": "Ampio",
    "Wide": "Largo",
    "Narrow": "Stretto",
    "Limited": "Limitato",
    "Restricted": "Ristretto",
    "Confined": "Confinato",
    "Bound": "Vincolato",
    "Unlimited": "Illimitato",
    "Unrestricted": "Senza restrizioni",
    "Free": "Libero",
    "Open": "Aperto",
    "Closed": "Chiuso",
    "Shut": "Chiuso",
    "Locked": "Bloccato",
    "Unlocked": "Sbloccato",
    "Accessible": "Accessibile",
    "Inaccessible": "Inaccessibile",
    "Available": "Disponibile",
    "Unavailable": "Non disponibile",
    "Ready": "Pronto",
    "Prepared": "Preparato",
    "Set": "Impostato",
    "Complete": "Completo",
    "Finished": "Finito",
    "Done": "Fatto",
    "Over": "Finito",
    "Ended": "Terminato",
    "Concluded": "Concluso",
    "Closed": "Chiuso",
    "Settled": "Risolto",
    "Resolved": "Risolto",
    "Fixed": "Risolto",
    "Repaired": "Riparato",
    "Restored": "Ripristinato",
    "Renewed": "Rinnovato",
    "Refreshed": "Aggiornato",
    "Updated": "Aggiornato",
    "Revised": "Rivisto",
    "Amended": "Modificato",
    "Modified": "Modificato",
    "Changed": "Cambiato",
    "Altered": "Alterato",
    "Adjusted": "Adattato",
    "Adapted": "Adattato",
    "Customized": "Personalizzato",
    "Tailored": "Su misura",
    "Personalized": "Personalizzato",
    "Individual": "Individuale",
    "Personal": "Personale",
    "Own": "Proprio",
    "Self": "Sé",
    "Me": "Io",
    "You": "Tu",
    "We": "Noi",
    "They": "Loro",
    "Us": "Noi",
    "Them": "Loro",
    "Our": "Nostro",
    "Your": "Tuo",
    "Their": "Loro",
    "His": "Suo",
    "Her": "Suo",
    "Its": "Suo",
    "My": "Mio",
    "Mine": "Mio",
    "Yours": "Tuo",
    "Ours": "Nostro",
    "Theirs": "Loro",
    "Hers": "Suo",
    "This": "Questo",
    "That": "Quello",
    "These": "Questi",
    "Those": "Quelli",
    "Here": "Qui",
    "There": "Là",
    "Everywhere": "Ovunque",
    "Nowhere": "Nessun luogo",
    "Somewhere": "Da qualche parte",
    "Anywhere": "Ovunque",
    "Always": "Sempre",
    "Never": "Mai",
    "Sometimes": "A volte",
    "Often": "Spesso",
    "Rarely": "Raramente",
    "Seldom": "Raramente",
    "Frequently": "Frequentemente",
    "Occasionally": "Occasionalmente",
    "Usually": "Di solito",
    "Normally": "Normalmente",
    "Typically": "Tipicamente",
    "Generally": "Generalmente",
    "Commonly": "Comunemente",
    "Regularly": "Regolarmente",
    "Consistently": "Costantemente",
    "Constantly": "Costantemente",
    "Perpetually": "Perpetuamente",
    "Eternally": "Eternamente",
    "Forever": "Per sempre",
    "Permanently": "Permanentemente",
    "Temporarily": "Temporaneamente",
    "Briefly": "Brevemente",
    "Momentarily": "Momentaneamente",
    "Instantly": "Istantaneamente",
    "Immediately": "Immediatamente",
    "Shortly": "A breve",
    "Eventually": "Alla fine",
    "Finally": "Finalmente",
    "Ultimately": "Alla fine",
    "Lastly": "Infine",
    "Firstly": "In primo luogo",
    "Secondly": "In secondo luogo",
    "Thirdly": "In terzo luogo",
    "Additionally": "Inoltre",
    "Furthermore": "Inoltre",
    "Moreover": "Inoltre",
    "Besides": "Inoltre",
    "Also": "Anche",
    "Too": "Anche",
    "As Well": "Anche",
    "Either": "Anche",
    "Neither": "Nemmeno",
    "Both": "Entrambi",
    "All": "Tutti",
    "Every": "Ogni",
    "Each": "Ciascuno",
    "Some": "Alcuni",
    "Any": "Qualsiasi",
    "Many": "Molti",
    "Much": "Molto",
    "Few": "Pochi",
    "Little": "Poco",
    "Several": "Diversi",
    "Various": "Vari",
    "Different": "Diversi",
    "Multiple": "Multipli",
    "Numerous": "Numerosi",
    "Countless": "Innumerevoli",
    "Infinite": "Infinito",
    "Unlimited": "Illimitato",
    "Limited": "Limitato",
    "Finite": "Finito",
    "Specific": "Specifico",
    "Particular": "Particolare",
    "Certain": "Certo",
    "Definite": "Definito",
    "Indefinite": "Indefinito",
    "Vague": "Vago",
    "Unclear": "Poco chiaro",
    "Ambiguous": "Ambiguo",
    "Clear": "Chiaro",
    "Obvious": "Ovvio",
    "Evident": "Evidente",
    "Apparent": "Apparente",
    "Visible": "Visibile",
    "Invisible": "Invisibile",
    "Transparent": "Trasparente",
    "Opaque": "Opaco",
    "Translucent": "Traslucido",
    "Solid": "Solido",
    "Liquid": "Liquido",
    "Gas": "Gas",
    "Vapor": "Vapore",
    "Steam": "Vapore",
    "Smoke": "Fumo",
    "Fire": "Fuoco",
    "Water": "Acqua",
    "Air": "Aria",
    "Earth": "Terra",
    "Metal": "Metallo",
    "Wood": "Legno",
    "Stone": "Pietra",
    "Rock": "Roccia",
    "Sand": "Sabbia",
    "Soil": "Suolo",
    "Dirt": "Sporco",
    "Dust": "Polvere",
    "Mud": "Fango",
    "Clay": "Argilla",
    "Cement": "Cemento",
    "Concrete": "Calcestruzzo",
    "Brick": "Mattone",
    "Tile": "Piastrella",
    "Glass": "Vetro",
    "Plastic": "Plastica",
    "Rubber": "Gomma",
    "Leather": "Pelle",
    "Fabric": "Tessuto",
    "Cloth": "Stoffa",
    "Cotton": "Cotone",
    "Wool": "Lana",
    "Silk": "Seta",
    "Synthetic": "Sintetico",
    "Natural": "Naturale",
    "Organic": "Organico",
    "Inorganic": "Inorganico",
    "Chemical": "Chimico",
    "Physical": "Fisico",
    "Biological": "Biologico",
    "Mechanical": "Meccanico",
    "Electrical": "Elettrico",
    "Electronic": "Elettronico",
    "Digital": "Digitale",
    "Analog": "Analogico",
    "Binary": "Binario",
    "Decimal": "Decimale",
    "Hexadecimal": "Esadecimale",
    "Octal": "Ottale",
    "Base": "Base",
    "Radix": "Base",
    "Bit": "Bit",
    "Byte": "Byte",
    "Kilobyte": "Kilobyte",
    "Megabyte": "Megabyte",
    "Gigabyte": "Gigabyte",
    "Terabyte": "Terabyte",
    "Petabyte": "Petabyte",
    "Bandwidth": "Larghezza di banda",
    "Speed": "Velocità",
    "Latency": "Latenza",
    "Throughput": "Throughput",
    "Capacity": "Capacità",
    "Limit": "Limite",
    "Threshold": "Soglia",
    "Maximum": "Massimo",
    "Minimum": "Minimo",
    "Optimal": "Ottimale",
    "Suboptimal": "Subottimale",
    "Ideal": "Ideale",
    "Perfect": "Perfetto",
    "Imperfect": "Imperfetto",
    "Flawed": "Difettoso",
    "Defective": "Difettoso",
    "Broken": "Rotto",
    "Damaged": "Danneggiato",
    "Intact": "Intatto",
    "Whole": "Intero",
    "Complete": "Completo",
    "Incomplete": "Incompleto",
    "Partial": "Parziale",
    "Total": "Totale",
    "Grand Total": "Totale complessivo",
    "Subtotal": "Subtotale",
    "Sum": "Somma",
    "Total Amount": "Importo totale",
    "Net Amount": "Importo netto",
    "Gross Amount": "Importo lordo",
    "Before Tax": "Prima delle imposte",
    "After Tax": "Dopo le imposte",
    "Including Tax": "Inclusa l'imposta",
    "Excluding Tax": "Esclusa l'imposta",
    "Plus Tax": "Più imposta",
    "Less Tax": "Meno imposta",
    "Tax Included": "Imposta inclusa",
    "Tax Excluded": "Imposta esclusa",
    "VAT Included": "IVA inclusa",
    "VAT Excluded": "IVA esclusa",
    "All Taxes": "Tutte le imposte",
    "No Tax": "Nessuna imposta",
    "Zero Tax": "Imposta zero",
    "Exempt": "Esente",
    "Non-Exempt": "Non esente",
    "Applicable": "Applicabile",
    "Not Applicable": "Non applicabile",
    "N/A": "N/D",
    "TBD": "Da definire",
    "To Be Determined": "Da determinare",
    "To Be Confirmed": "Da confermare",
    "Pending": "In attesa",
    "In Progress": "In corso",
    "Ongoing": "In corso",
    "Active": "Attivo",
    "Inactive": "Inattivo",
    "Dormant": "Dormiente",
    "Suspended": "Sospeso",
    "Terminated": "Terminato",
    "Expired": "Scaduto",
    "Valid": "Valido",
    "Invalid": "Non valido",
    "Current": "Corrente",
    "Outdated": "Obsoleto",
    "Old": "Vecchio",
    "New": "Nuovo",
    "Latest": "Ultimo",
    "Newest": "Più recente",
    "Oldest": "Più vecchio",
    "Recent": "Recente",
    "Past": "Passato",
    "Present": "Presente",
    "Future": "Futuro",
    "Upcoming": "Prossimo",
    "Coming": "In arrivo",
    "Approaching": "In avvicinamento",
    "Imminent": "Imminente",
    "Distant": "Lontano",
    "Near": "Vicino",
    "Close": "Vicino",
    "Far": "Lontano",
    "Remote": "Remoto",
    "Adjacent": "Adiacente",
    "Next To": "Accanto a",
    "Beside": "Accanto",
    "Nearby": "Nelle vicinanze",
    "Around": "Intorno",
    "Surrounding": "Circostante",
    "Within": "Entro",
    "Beyond": "Oltre",
    "Between": "Tra",
    "Among": "Tra",
    "Amongst": "Fra",
    "Through": "Attraverso",
    "Throughout": "In tutto",
    "Across": "Attraverso",
    "Along": "Lungo",
    "Against": "Contro",
    "Versus": "Contro",
    "Compared To": "Rispetto a",
    "Relative To": "Relativo a",
    "With Respect To": "Rispetto a",
    "Regarding": "Riguardo a",
    "Concerning": "Riguardo a",
    "About": "Circa",
    "Approximately": "Approssimativamente",
    "Around": "Circa",
    "Roughly": "Approssimativamente",
    "Nearly": "Quasi",
    "Almost": "Quasi",
    "Barely": "A malapena",
    "Hardly": "A malapena",
    "Scarcely": "A malapena",
    "Just": "Solo",
    "Only": "Solo",
    "Merely": "Semplicemente",
    "Simply": "Semplicemente",
    "Purely": "Puramente",
    "Solely": "Solamente",
    "Exclusively": "Esclusivamente",
    "Entirely": "Interamente",
    "Completely": "Completamente",
    "Totally": "Totalmente",
    "Absolutely": "Assolutamente",
    "Perfectly": "Perfettamente",
    "Exactly": "Esattamente",
    "Precisely": "Precisamente",
    "Accurately": "Accuratamente",
    "Correctly": "Correttamente",
    "Properly": "Correttamente",
    "Appropriately": "Appropriatamente",
    "Suitably": "Adeguatamente",
    "Adequately": "Adeguatamente",
    "Sufficiently": "Sufficientemente",
    "Enough": "Abbastanza",
    "Insufficient": "Insufficiente",
    "Inadequate": "Inadeguato",
    "Lacking": "Mancante",
    "Short": "Corto",
    "Excess": "Eccesso",
    "Surplus": "Surplus",
    "Extra": "Extra",
    "Additional": "Aggiuntivo",
    "Supplementary": "Supplementare",
    "Complementary": "Complementare",
    "Alternative": "Alternativo",
    "Substitute": "Sostituto",
    "Replacement": "Sostituzione",
    "Backup": "Backup",
    "Reserve": "Riserva",
    "Spare": "Di riserva",
    "Emergency": "Emergenza",
    "Urgent": "Urgente",
    "Critical": "Critico",
    "Important": "Importante",
    "Essential": "Essenziale",
    "Necessary": "Necessario",
    "Required": "Richiesto",
    "Mandatory": "Obbligatorio",
    "Compulsory": "Obbligatorio",
    "Obligatory": "Obbligatorio",
    "Voluntary": "Volontario",
    "Optional": "Facoltativo",
    "Elective": "Elettivo",
    "Discretionary": "Discrezionale",
    "Recommended": "Raccomandato",
    "Suggested": "Suggerito",
    "Advised": "Consigliato",
    "Preferred": "Preferito",
    "Best": "Migliore",
    "Optimal": "Ottimale",
    "Ideal": "Ideale",
    "Perfect": "Perfetto",
    "Flawless": "Perfetto",
    "Impeccable": "Impeccabile",
    "Excellent": "Eccellente",
    "Superior": "Superiore",
    "Premium": "Premium",
    "Deluxe": "Deluxe",
    "Luxury": "Lusso",
    "Standard": "Standard",
    "Basic": "Base",
    "Economy": "Economico",
    "Budget": "Budget",
    "Low-Cost": "Basso costo",
    "Affordable": "Accessibile",
    "Economical": "Economico",
    "Cost-Effective": "Conveniente",
    "Efficient": "Efficiente",
    "Effective": "Efficace",
    "Productive": "Produttivo",
    "Successful": "Di successo",
    "Profitable": "Redditizio",
    "Lucrative": "Lucrativo",
    "Rewarding": "Gratificante",
    "Satisfying": "Soddisfacente",
    "Fulfilling": "Appagante",
    "Gratifying": "Gratificante",
    "Pleasing": "Piacevole",
    "Enjoyable": "Piacevole",
    "Pleasant": "Piacevole",
    "Delightful": "Delizioso",
    "Wonderful": "Meraviglioso",
    "Marvelous": "Meraviglioso",
    "Magnificent": "Magnifico",
    "Splendid": "Splendido",
    "Superb": "Superbo",
    "Outstanding": "Eccezionale",
    "Exceptional": "Eccezionale",
    "Remarkable": "Notevole",
    "Notable": "Notevole",
    "Noteworthy": "Degno di nota",
    "Significant": "Significativo",
    "Meaningful": "Significativo",
    "Important": "Importante",
    "Valuable": "Prezioso",
    "Useful": "Utile",
    "Helpful": "Utile",
    "Beneficial": "Benefico",
    "Advantageous": "Vantaggioso",
    "Favorable": "Favorevole",
    "Positive": "Positivo",
    "Constructive": "Costruttivo",
    "Productive": "Produttivo",
    "Fruitful": "Fruttuoso",
    "Successful": "Di successo",
    "Victorious": "Vittorioso",
    "Triumphant": "Trionfante",
    "Winning": "Vincente",
    "Champion": "Campione",
    "Winner": "Vincitore",
    "Loser": "Perdente",
    "Participant": "Partecipante",
    "Competitor": "Concorrente",
    "Contestant": "Concorrente",
    "Candidate": "Candidato",
    "Applicant": "Richiedente",
    "Nominee": "Candidato",
    "Finalist": "Finalista",
    "Semifinalist": "Semifinalista",
    "Qualifier": "Qualificato",
    "Entrant": "Partecipante",
    "Player": "Giocatore",
    "Athlete": "Atleta",
    "Performer": "Esecutore",
    "Artist": "Artista",
    "Creator": "Creatore",
    "Maker": "Creatore",
    "Builder": "Costruttore",
    "Developer": "Sviluppatore",
    "Designer": "Designer",
    "Architect": "Architetto",
    "Planner": "Pianificatore",
    "Strategist": "Stratega",
    "Thinker": "Pensatore",
    "Innovator": "Innovatore",
    "Pioneer": "Pioniere",
    "Leader": "Leader",
    "Follower": "Seguace",
    "Supporter": "Sostenitore",
    "Advocate": "Sostenitore",
    "Promoter": "Promotore",
    "Sponsor": "Sponsor",
    "Patron": "Patrono",
    "Donor": "Donatore",
    "Contributor": "Contributore",
    "Participant": "Partecipante",
    "Member": "Membro",
    "Associate": "Associato",
    "Colleague": "Collega",
    "Coworker": "Collega",
    "Teammate": "Compagno di squadra",
    "Partner": "Partner",
    "Collaborator": "Collaboratore",
    "Ally": "Alleato",
    "Friend": "Amico",
    "Companion": "Compagno",
    "Buddy": "Amico",
    "Pal": "Amico",
    "Mate": "Compagno",
    "Associate": "Socio",
    "Acquaintance": "Conoscente",
    "Contact": "Contatto",
    "Connection": "Connessione",
    "Relation": "Relazione",
    "Relative": "Parente",
    "Family": "Famiglia",
    "Kin": "Parente",
    "Kinship": "Parentela",
    "Ancestry": "Antenati",
    "Heritage": "Patrimonio",
    "Legacy": "Eredità",
    "Inheritance": "Eredità",
    "Succession": "Successione",
    "Generation": "Generazione",
    "Lineage": "Lignaggio",
    "Bloodline": "Stirpe",
    "Descent": "Discendenza",
    "Origin": "Origine",
    "Source": "Fonte",
    "Root": "Radice",
    "Foundation": "Fondazione",
    "Basis": "Base",
    "Ground": "Base",
    "Reason": "Motivo",
    "Cause": "Causa",
    "Motive": "Motivo",
    "Purpose": "Scopo",
    "Intention": "Intenzione",
    "Intent": "Intento",
    "Aim": "Obiettivo",
    "Goal": "Obiettivo",
    "Objective": "Obiettivo",
    "Target": "Obiettivo",
    "Destination": "Destinazione",
    "End": "Fine",
    "Conclusion": "Conclusione",
    "Termination": "Conclusione",
    "Completion": "Completamento",
    "Finalization": "Finalizzazione",
    "Closure": "Chiusura",
    "Settlement": "Risoluzione",
    "Resolution": "Risoluzione",
    "Solution": "Soluzione",
    "Answer": "Risposta",
    "Reply": "Risposta",
    "Response": "Risposta",
    "Reaction": "Reazione",
    "Feedback": "Feedback",
    "Comment": "Commento",
    "Remark": "Osservazione",
    "Statement": "Dichiarazione",
    "Declaration": "Dichiarazione",
    "Announcement": "Annuncio",
    "Proclamation": "Proclamazione",
    "Notice": "Avviso",
    "Notification": "Notifica",
    "Alert": "Avviso",
    "Alarm": "Allarme",
    "Signal": "Segnale",
    "Indication": "Indicazione",
    "Sign": "Segno",
    "Mark": "Segno",
    "Symbol": "Simbolo",
    "Icon": "Icona",
    "Emblem": "Emblema",
    "Badge": "Badge",
    "Insignia": "Insegna",
    "Crest": "Stemma",
    "Coat of Arms": "Stemma",
    "Flag": "Bandiera",
    "Banner": "Striscione",
    "Standard": "Stendardo",
    "Ensign": "Insegna",
    "Pennant": "Fiamma",
    "Colors": "Colori",
}

def flatten_dict(d, parent_key='', sep='.'):
    """Flatten nested dictionary."""
    items = []
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        else:
            items.append((new_key, v))
    return dict(items)

def unflatten_dict(d, sep='.'):
    """Unflatten dictionary."""
    result = {}
    for key, value in d.items():
        parts = key.split(sep)
        current = result
        for part in parts[:-1]:
            if part not in current:
                current[part] = {}
            current = current[part]
        current[parts[-1]] = value
    return result

def translate_text(text):
    """Translate text to Italian using the translation dictionary."""
    # Direct match
    if text in TRANSLATIONS:
        return TRANSLATIONS[text]

    # Case-insensitive match
    for key, value in TRANSLATIONS.items():
        if key.lower() == text.lower():
            # Preserve case
            if text.isupper():
                return value.upper()
            elif text[0].isupper():
                return value.capitalize()
            return value

    # Common patterns
    patterns = {
        # Questions
        r'^What is (.+)\?$': lambda m: f"Cos'è {translate_text(m.group(1))}?",
        r'^How (.+)\?$': lambda m: f"Come {translate_text(m.group(1))}?",
        r'^Why (.+)\?$': lambda m: f"Perché {translate_text(m.group(1))}?",
        r'^When (.+)\?$': lambda m: f"Quando {translate_text(m.group(1))}?",
        r'^Where (.+)\?$': lambda m: f"Dove {translate_text(m.group(1))}?",
        r'^Who (.+)\?$': lambda m: f"Chi {translate_text(m.group(1))}?",

        # Actions
        r'^Click (.+)$': lambda m: f"Clicca su {translate_text(m.group(1))}",
        r'^Select (.+)$': lambda m: f"Seleziona {translate_text(m.group(1))}",
        r'^Enter (.+)$': lambda m: f"Inserisci {translate_text(m.group(1))}",
        r'^Choose (.+)$': lambda m: f"Scegli {translate_text(m.group(1))}",
        r'^Add (.+)$': lambda m: f"Aggiungi {translate_text(m.group(1))}",
        r'^Remove (.+)$': lambda m: f"Rimuovi {translate_text(m.group(1))}",
        r'^Delete (.+)$': lambda m: f"Elimina {translate_text(m.group(1))}",
        r'^Edit (.+)$': lambda m: f"Modifica {translate_text(m.group(1))}",
        r'^Save (.+)$': lambda m: f"Salva {translate_text(m.group(1))}",
        r'^Upload (.+)$': lambda m: f"Carica {translate_text(m.group(1))}",
        r'^Download (.+)$': lambda m: f"Scarica {translate_text(m.group(1))}",
        r'^View (.+)$': lambda m: f"Visualizza {translate_text(m.group(1))}",

        # Plurals
        r'^(.+)s$': lambda m: translate_text(m.group(1)),
    }

    import re
    for pattern, func in patterns.items():
        match = re.match(pattern, text, re.IGNORECASE)
        if match:
            try:
                return func(match)
            except:
                pass

    # If no translation found, return the original text
    # This is better than returning [TODO] or English
    return text

def compare_and_add_translations(en_file, it_file):
    """Compare English and Italian files and add missing translations."""
    # Read files
    with open(en_file, 'r', encoding='utf-8') as f:
        en_data = json.load(f)

    with open(it_file, 'r', encoding='utf-8') as f:
        it_data = json.load(f)

    # Flatten dictionaries
    en_flat = flatten_dict(en_data)
    it_flat = flatten_dict(it_data)

    # Find missing keys
    missing_keys = set(en_flat.keys()) - set(it_flat.keys())

    if not missing_keys:
        print("No missing keys found. Italian translation is complete.")
        return 0

    print(f"Found {len(missing_keys)} missing keys in Italian translation.")

    # Add missing translations
    translations_added = 0
    for key in sorted(missing_keys):
        en_value = en_flat[key]

        # Translate the value
        if isinstance(en_value, str):
            it_value = translate_text(en_value)
            it_flat[key] = it_value
            translations_added += 1
            print(f"Added: {key} = {it_value}")
        else:
            # For non-string values, keep the same value
            it_flat[key] = en_value
            print(f"Added (non-string): {key} = {en_value}")

    # Unflatten and save
    it_data_updated = unflatten_dict(it_flat)

    with open(it_file, 'w', encoding='utf-8') as f:
        json.dump(it_data_updated, f, ensure_ascii=False, indent=2)

    return translations_added

if __name__ == "__main__":
    en_file = "/home/cn/Desktop/HomeAiCode/swissai-tax/src/locales/en/translation.json"
    it_file = "/home/cn/Desktop/HomeAiCode/swissai-tax/src/locales/it/translation.json"

    count = compare_and_add_translations(en_file, it_file)
    print(f"\nDone. {count} keys translated to Italian.")
