#!/usr/bin/env python3
"""
Script to translate missing keys from English to French in translation.json
"""
import json
from pathlib import Path

# French translations mapping
FRENCH_TRANSLATIONS = {
    # Settings & Account
    "settings": "Paramètres",
    "account": "Compte",
    "profile": "Profil",
    "security": "Sécurité",
    "notifications": "Notifications",
    "preferences": "Préférences",
    "language": "Langue",
    "theme": "Thème",
    "privacy": "Confidentialité",
    "help": "Aide",
    "support": "Support",
    "logout": "Déconnexion",
    "login": "Connexion",
    "signup": "Inscription",
    "register": "S'inscrire",
    "email": "Email",
    "password": "Mot de passe",
    "username": "Nom d'utilisateur",
    "name": "Nom",
    "firstName": "Prénom",
    "lastName": "Nom de famille",
    "phone": "Téléphone",
    "address": "Adresse",
    "city": "Ville",
    "country": "Pays",
    "zipCode": "Code postal",
    "save": "Enregistrer",
    "cancel": "Annuler",
    "delete": "Supprimer",
    "edit": "Modifier",
    "add": "Ajouter",
    "remove": "Retirer",
    "close": "Fermer",
    "open": "Ouvrir",
    "submit": "Soumettre",
    "send": "Envoyer",
    "back": "Retour",
    "next": "Suivant",
    "previous": "Précédent",
    "continue": "Continuer",
    "finish": "Terminer",
    "confirm": "Confirmer",
    "yes": "Oui",
    "no": "Non",
    "ok": "OK",
    "loading": "Chargement",
    "error": "Erreur",
    "success": "Succès",
    "warning": "Avertissement",
    "info": "Information",
    "search": "Rechercher",
    "filter": "Filtrer",
    "sort": "Trier",
    "view": "Voir",
    "download": "Télécharger",
    "upload": "Téléverser",
    "export": "Exporter",
    "import": "Importer",
    "print": "Imprimer",
    "share": "Partager",
    "copy": "Copier",
    "paste": "Coller",
    "cut": "Couper",
    "undo": "Annuler",
    "redo": "Refaire",
    "refresh": "Actualiser",
    "update": "Mettre à jour",
    "upgrade": "Mettre à niveau",
    "downgrade": "Rétrograder",
    "activate": "Activer",
    "deactivate": "Désactiver",
    "enable": "Activer",
    "disable": "Désactiver",
    "show": "Afficher",
    "hide": "Masquer",
    "expand": "Développer",
    "collapse": "Réduire",
    "select": "Sélectionner",
    "deselect": "Désélectionner",
    "selectAll": "Tout sélectionner",
    "deselectAll": "Tout désélectionner",
    "clear": "Effacer",
    "reset": "Réinitialiser",
    "apply": "Appliquer",
    "create": "Créer",
    "new": "Nouveau",
    "duplicate": "Dupliquer",
    "clone": "Cloner",
    "move": "Déplacer",
    "rename": "Renommer",
    "replace": "Remplacer",
    "restore": "Restaurer",
    "archive": "Archiver",
    "unarchive": "Désarchiver",
    "publish": "Publier",
    "unpublish": "Dépublier",
    "draft": "Brouillon",
    "pending": "En attente",
    "approved": "Approuvé",
    "rejected": "Rejeté",
    "completed": "Terminé",
    "active": "Actif",
    "inactive": "Inactif",
    "status": "Statut",
    "type": "Type",
    "category": "Catégorie",
    "tag": "Étiquette",
    "description": "Description",
    "details": "Détails",
    "title": "Titre",
    "subtitle": "Sous-titre",
    "content": "Contenu",
    "message": "Message",
    "comment": "Commentaire",
    "note": "Note",
    "date": "Date",
    "time": "Heure",
    "datetime": "Date et heure",
    "startDate": "Date de début",
    "endDate": "Date de fin",
    "createdAt": "Créé le",
    "updatedAt": "Mis à jour le",
    "deletedAt": "Supprimé le",
    "createdBy": "Créé par",
    "updatedBy": "Mis à jour par",
    "deletedBy": "Supprimé par",
    "owner": "Propriétaire",
    "author": "Auteur",
    "user": "Utilisateur",
    "admin": "Administrateur",
    "moderator": "Modérateur",
    "guest": "Invité",
    "member": "Membre",
    "role": "Rôle",
    "permission": "Permission",
    "access": "Accès",
    "public": "Public",
    "private": "Privé",
    "shared": "Partagé",
    "restricted": "Restreint",
    "unlimited": "Illimité",
    "limited": "Limité",
    "free": "Gratuit",
    "paid": "Payant",
    "premium": "Premium",
    "basic": "Basique",
    "standard": "Standard",
    "advanced": "Avancé",
    "professional": "Professionnel",
    "enterprise": "Entreprise",
    "plan": "Formule",
    "subscription": "Abonnement",
    "billing": "Facturation",
    "payment": "Paiement",
    "invoice": "Facture",
    "receipt": "Reçu",
    "price": "Prix",
    "amount": "Montant",
    "total": "Total",
    "subtotal": "Sous-total",
    "tax": "Taxe",
    "discount": "Réduction",
    "coupon": "Coupon",
    "promo": "Promo",
    "currency": "Devise",
    "quantity": "Quantité",
    "unit": "Unité",
    "rate": "Taux",
    "percentage": "Pourcentage",
    "value": "Valeur",
    "minimum": "Minimum",
    "maximum": "Maximum",
    "average": "Moyenne",
    "total": "Total",
    "sum": "Somme",
    "count": "Nombre",
    "number": "Numéro",
    "id": "ID",
    "code": "Code",
    "reference": "Référence",
    "identifier": "Identifiant",
    "key": "Clé",
    "token": "Jeton",
    "secret": "Secret",
    "api": "API",
    "url": "URL",
    "link": "Lien",
    "file": "Fichier",
    "folder": "Dossier",
    "directory": "Répertoire",
    "path": "Chemin",
    "size": "Taille",
    "format": "Format",
    "extension": "Extension",
    "image": "Image",
    "video": "Vidéo",
    "audio": "Audio",
    "document": "Document",
    "pdf": "PDF",
    "text": "Texte",
    "html": "HTML",
    "css": "CSS",
    "javascript": "JavaScript",
    "json": "JSON",
    "xml": "XML",
    "csv": "CSV",
    "excel": "Excel",
    "word": "Word",
    "powerpoint": "PowerPoint",
    "zip": "ZIP",
    "version": "Version",
    "changelog": "Journal des modifications",
    "release": "Version",
    "build": "Build",
    "branch": "Branche",
    "commit": "Commit",
    "merge": "Fusionner",
    "pull": "Pull",
    "push": "Push",
    "clone": "Cloner",
    "fork": "Fork",
    "repository": "Dépôt",
    "project": "Projet",
    "workspace": "Espace de travail",
    "dashboard": "Tableau de bord",
    "overview": "Aperçu",
    "summary": "Résumé",
    "report": "Rapport",
    "analytics": "Analytique",
    "statistics": "Statistiques",
    "metrics": "Métriques",
    "chart": "Graphique",
    "graph": "Graphe",
    "table": "Tableau",
    "list": "Liste",
    "grid": "Grille",
    "card": "Carte",
    "item": "Élément",
    "entry": "Entrée",
    "record": "Enregistrement",
    "row": "Ligne",
    "column": "Colonne",
    "field": "Champ",
    "label": "Libellé",
    "placeholder": "Espace réservé",
    "tooltip": "Info-bulle",
    "hint": "Indice",
    "example": "Exemple",
    "sample": "Échantillon",
    "template": "Modèle",
    "pattern": "Modèle",
    "format": "Format",
    "validation": "Validation",
    "required": "Obligatoire",
    "optional": "Optionnel",
    "recommended": "Recommandé",
    "suggested": "Suggéré",
    "default": "Par défaut",
    "custom": "Personnalisé",
    "automated": "Automatisé",
    "manual": "Manuel",
    "automatic": "Automatique",
    "scheduled": "Planifié",
    "recurring": "Récurrent",
    "onetime": "Unique",
    "daily": "Quotidien",
    "weekly": "Hebdomadaire",
    "monthly": "Mensuel",
    "yearly": "Annuel",
    "hourly": "Horaire",
    "minute": "Minute",
    "second": "Seconde",
    "day": "Jour",
    "week": "Semaine",
    "month": "Mois",
    "year": "Année",
    "today": "Aujourd'hui",
    "yesterday": "Hier",
    "tomorrow": "Demain",
    "now": "Maintenant",
    "recent": "Récent",
    "latest": "Dernier",
    "oldest": "Plus ancien",
    "newest": "Plus récent",
    "all": "Tout",
    "none": "Aucun",
    "any": "N'importe quel",
    "other": "Autre",
    "more": "Plus",
    "less": "Moins",
    "empty": "Vide",
    "full": "Plein",
    "available": "Disponible",
    "unavailable": "Indisponible",
    "online": "En ligne",
    "offline": "Hors ligne",
    "connected": "Connecté",
    "disconnected": "Déconnecté",
    "synced": "Synchronisé",
    "syncing": "Synchronisation",
    "processing": "Traitement en cours",
    "processed": "Traité",
    "queued": "En file d'attente",
    "waiting": "En attente",
    "running": "En cours d'exécution",
    "stopped": "Arrêté",
    "paused": "En pause",
    "resumed": "Repris",
    "started": "Démarré",
    "finished": "Terminé",
    "failed": "Échoué",
    "cancelled": "Annulé",
    "timeout": "Délai d'attente",
    "retry": "Réessayer",
    "attempt": "Tentative",
    "attempts": "Tentatives",
    "remaining": "Restant",
    "elapsed": "Écoulé",
    "duration": "Durée",
    "progress": "Progrès",
    "complete": "Complet",
    "incomplete": "Incomplet",
    "partial": "Partiel",
    "valid": "Valide",
    "invalid": "Invalide",
    "verified": "Vérifié",
    "unverified": "Non vérifié",
    "authenticated": "Authentifié",
    "unauthenticated": "Non authentifié",
    "authorized": "Autorisé",
    "unauthorized": "Non autorisé",
    "allowed": "Autorisé",
    "denied": "Refusé",
    "granted": "Accordé",
    "revoked": "Révoqué",
    "expired": "Expiré",
    "valid": "Valide",
    "enabled": "Activé",
    "disabled": "Désactivé",
    "visible": "Visible",
    "hidden": "Masqué",
    "locked": "Verrouillé",
    "unlocked": "Déverrouillé",
    "read": "Lire",
    "write": "Écrire",
    "execute": "Exécuter",
    "readOnly": "Lecture seule",
    "writeOnly": "Écriture seule",
    "readWrite": "Lecture/Écriture",
}

def get_nested_value(obj, path):
    """Get value from nested dict using dot notation path"""
    keys = path.split('.')
    current = obj
    for key in keys:
        if isinstance(current, dict) and key in current:
            current = current[key]
        else:
            return None
    return current

def set_nested_value(obj, path, value):
    """Set value in nested dict using dot notation path"""
    keys = path.split('.')
    current = obj
    for key in keys[:-1]:
        if key not in current:
            current[key] = {}
        current = current[key]
    current[keys[-1]] = value

def get_all_keys(obj, prefix=''):
    """Get all keys from nested dict with dot notation paths"""
    keys = []
    for key, value in obj.items():
        full_key = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            keys.extend(get_all_keys(value, full_key))
        else:
            keys.append(full_key)
    return keys

def translate_text(english_text):
    """Translate English text to French"""
    # Direct mapping check
    if english_text in FRENCH_TRANSLATIONS:
        return FRENCH_TRANSLATIONS[english_text]

    # Handle complex phrases first
    complex_phrases = {
        "AI-powered tenant scoring and ranking system": "Système de notation et de classement des locataires alimenté par l'IA",
        "Automated application processing and filtering": "Traitement et filtrage automatisés des candidatures",
        "Casual renters, budget-conscious individuals, or first-time users exploring  AI capabilities": "Locataires occasionnels, personnes soucieuses du budget ou nouveaux utilisateurs explorant les capacités de l'IA",
        "Close to your workplace, includes a balcony (a stated preference), and has lower local taxes — perfect for your budget and lifestyle": "Proche de votre lieu de travail, comprend un balcon (une préférence déclarée) et bénéficie d'impôts locaux plus bas — parfait pour votre budget et votre style de vie",
        "Document generation and contract automation": "Génération de documents et automatisation des contrats",
        "Find Quality Tenants Faster Than Ever!": "Trouvez des locataires de qualité plus rapidement que jamais !",
        "Integrated messaging and notification system": "Système de messagerie et de notification intégré",
        "Let AI Handle Your Property Management": "Laissez l'IA gérer votre propriété",
        "Multi-channel communication management": "Gestion de communication multicanal",
        "Professional property listing enhancement": "Amélioration professionnelle des annonces immobilières",
        "AI-powered property valuation and market analysis": "Évaluation immobilière et analyse de marché alimentées par l'IA",
        "Smart tenant matching based on preferences": "Correspondance intelligente des locataires selon les préférences",
        "Automated rent collection and payment tracking": "Collecte automatisée des loyers et suivi des paiements",
        "Real-time market insights and trends": "Informations et tendances du marché en temps réel",
        "AI assistant for tax optimization": "Assistant IA pour l'optimisation fiscale",
        "Comprehensive reporting and analytics": "Rapports et analyses complets",
        "24/7 AI support and guidance": "Support et conseils IA 24/7",
        "Secure document storage and management": "Stockage et gestion sécurisés des documents",
        "Premium landlords and businesses needing advanced  AI features": "Propriétaires et entreprises premium nécessitant des fonctionnalités IA avancées",
        "Professionals managing multiple properties or seeking  AI-powered efficiency": "Professionnels gérant plusieurs propriétés ou recherchant l'efficacité alimentée par l'IA",
        "Advanced AI analytics and insights": "Analyses et informations IA avancées",
        "Priority support and consultation": "Support prioritaire et consultation",
        "Custom AI model training": "Formation de modèle IA personnalisé",
        "API access for integrations": "Accès API pour les intégrations",
        "White-label options available": "Options en marque blanche disponibles",
        "Dedicated account manager": "Gestionnaire de compte dédié",
        "Early access to new features": "Accès anticipé aux nouvelles fonctionnalités",
        "Enhanced security and compliance": "Sécurité et conformité améliorées",
        "Based on your preferences and needs": "Basé sur vos préférences et besoins",
        "AI recommendation": "Recommandation IA",
        "Best match": "Meilleure correspondance",
        "Your personalized tax profile": "Votre profil fiscal personnalisé",
        "Tax optimization opportunities": "Opportunités d'optimisation fiscale",
        "Estimated tax savings": "Économies d'impôt estimées",
        "Get started with your free consultation": "Commencez avec votre consultation gratuite",
        "Schedule a call with our tax experts": "Planifiez un appel avec nos experts fiscaux",
        "Upload your documents securely": "Téléversez vos documents en toute sécurité",
        "AI will analyze your situation": "L'IA analysera votre situation",
        "Receive your personalized plan": "Recevez votre plan personnalisé",
        "Implementation and support": "Mise en œuvre et support",
    }

    if english_text in complex_phrases:
        return complex_phrases[english_text]

    # Common patterns
    text_lower = english_text.lower()

    # Tax-specific translations
    tax_translations = {
        "tax": "Impôt",
        "taxes": "Impôts",
        "tax return": "Déclaration d'impôts",
        "tax filing": "Déclaration fiscale",
        "filing": "Déclaration",
        "deduction": "Déduction",
        "deductions": "Déductions",
        "income": "Revenu",
        "expenses": "Dépenses",
        "revenue": "Revenus",
        "canton": "Canton",
        "federal": "Fédéral",
        "municipal": "Communal",
        "swiss tax": "Impôt suisse",
        "switzerland": "Suisse",
        "swiss": "Suisse",
        "ahr": "AVS",
        "vat": "TVA",
        "withholding tax": "Impôt à la source",
        "tax rate": "Taux d'imposition",
        "taxable income": "Revenu imposable",
        "tax year": "Année fiscale",
        "tax period": "Période fiscale",
        "tax assessment": "Taxation",
        "tax office": "Office des impôts",
        "tax authority": "Autorité fiscale",
        "tax consultant": "Conseiller fiscal",
        "tax advisor": "Conseiller fiscal",
        "tax return form": "Formulaire de déclaration",
        "tax document": "Document fiscal",
        "tax documents": "Documents fiscaux",
        "tax calculation": "Calcul d'impôt",
        "tax optimization": "Optimisation fiscale",
        "tax savings": "Économies d'impôt",
        "tax refund": "Remboursement d'impôt",
        "tax payment": "Paiement d'impôt",
        "tax bill": "Facture d'impôt",
        "tax debt": "Dette fiscale",
        "tax credit": "Crédit d'impôt",
        "property": "Propriété",
        "properties": "Propriétés",
        "real estate": "Immobilier",
        "rental income": "Revenu locatif",
        "rental property": "Propriété locative",
        "landlord": "Propriétaire",
        "tenant": "Locataire",
        "lease": "Bail",
        "rent": "Loyer",
        "mortgage": "Hypothèque",
        "depreciation": "Amortissement",
        "maintenance": "Entretien",
        "repairs": "Réparations",
        "utilities": "Services publics",
        "insurance": "Assurance",
        "insurance premium": "Prime d'assurance",
        "health insurance": "Assurance maladie",
        "pension": "Pension",
        "retirement": "Retraite",
        "pillar 3a": "Pilier 3a",
        "pillar 3b": "Pilier 3b",
        "ahv/iv": "AVS/AI",
        "social security": "Sécurité sociale",
        "employment": "Emploi",
        "employer": "Employeur",
        "employee": "Employé",
        "salary": "Salaire",
        "wage": "Salaire",
        "bonus": "Prime",
        "commission": "Commission",
        "self-employed": "Indépendant",
        "freelance": "Indépendant",
        "business": "Entreprise",
        "company": "Société",
        "corporation": "Corporation",
        "partnership": "Partenariat",
        "sole proprietorship": "Entreprise individuelle",
        "investment": "Investissement",
        "investments": "Investissements",
        "dividend": "Dividende",
        "dividends": "Dividendes",
        "interest": "Intérêt",
        "capital gain": "Gain en capital",
        "capital gains": "Gains en capital",
        "stock": "Action",
        "stocks": "Actions",
        "bond": "Obligation",
        "bonds": "Obligations",
        "fund": "Fonds",
        "mutual fund": "Fonds commun de placement",
        "etf": "ETF",
        "portfolio": "Portefeuille",
        "asset": "Actif",
        "assets": "Actifs",
        "liability": "Passif",
        "liabilities": "Passifs",
        "net worth": "Valeur nette",
        "wealth": "Patrimoine",
        "bank account": "Compte bancaire",
        "savings account": "Compte d'épargne",
        "checking account": "Compte courant",
        "credit card": "Carte de crédit",
        "loan": "Prêt",
        "debt": "Dette",
        "charity": "Charité",
        "donation": "Don",
        "donations": "Dons",
        "contribution": "Contribution",
        "contributions": "Contributions",
        "child": "Enfant",
        "children": "Enfants",
        "dependent": "Personne à charge",
        "dependents": "Personnes à charge",
        "spouse": "Conjoint",
        "married": "Marié",
        "single": "Célibataire",
        "divorced": "Divorcé",
        "widowed": "Veuf/Veuve",
        "marital status": "État civil",
        "family": "Famille",
        "household": "Ménage",
        "residence": "Résidence",
        "domicile": "Domicile",
        "address": "Adresse",
        "zip code": "Code postal",
        "postal code": "Code postal",
        "city": "Ville",
        "municipality": "Commune",
        "canton": "Canton",
        "state": "État",
        "country": "Pays",
        "nationality": "Nationalité",
        "citizen": "Citoyen",
        "citizenship": "Citoyenneté",
        "permit": "Permis",
        "work permit": "Permis de travail",
        "residence permit": "Permis de séjour",
        "visa": "Visa",
        "passport": "Passeport",
        "id card": "Carte d'identité",
        "identification": "Identification",
        "personal data": "Données personnelles",
        "personal information": "Informations personnelles",
        "contact": "Contact",
        "contact information": "Coordonnées",
        "phone number": "Numéro de téléphone",
        "mobile": "Mobile",
        "email address": "Adresse e-mail",
        "website": "Site web",
        "social media": "Réseaux sociaux",
        "profile": "Profil",
        "account": "Compte",
        "user account": "Compte utilisateur",
        "username": "Nom d'utilisateur",
        "password": "Mot de passe",
        "confirm password": "Confirmer le mot de passe",
        "forgot password": "Mot de passe oublié",
        "reset password": "Réinitialiser le mot de passe",
        "change password": "Changer le mot de passe",
        "new password": "Nouveau mot de passe",
        "old password": "Ancien mot de passe",
        "current password": "Mot de passe actuel",
        "sign in": "Se connecter",
        "sign out": "Se déconnecter",
        "sign up": "S'inscrire",
        "log in": "Se connecter",
        "log out": "Se déconnecter",
        "register": "S'inscriger",
        "registration": "Inscription",
        "verification": "Vérification",
        "verify": "Vérifier",
        "activate": "Activer",
        "activation": "Activation",
        "two-factor": "Double authentification",
        "2fa": "2FA",
        "security code": "Code de sécurité",
        "verification code": "Code de vérification",
        "authentication": "Authentification",
        "authenticate": "Authentifier",
        "session": "Session",
        "timeout": "Délai d'expiration",
        "expired": "Expiré",
        "active": "Actif",
        "inactive": "Inactif",
        "online": "En ligne",
        "offline": "Hors ligne",
        "status": "Statut",
        "settings": "Paramètres",
        "preferences": "Préférences",
        "configuration": "Configuration",
        "options": "Options",
        "general": "Général",
        "advanced": "Avancé",
        "privacy": "Confidentialité",
        "security": "Sécurité",
        "notifications": "Notifications",
        "alerts": "Alertes",
        "email notifications": "Notifications par e-mail",
        "push notifications": "Notifications push",
        "sms notifications": "Notifications SMS",
        "language": "Langue",
        "timezone": "Fuseau horaire",
        "date format": "Format de date",
        "time format": "Format d'heure",
        "currency": "Devise",
        "theme": "Thème",
        "dark mode": "Mode sombre",
        "light mode": "Mode clair",
        "appearance": "Apparence",
        "display": "Affichage",
        "accessibility": "Accessibilité",
        "help": "Aide",
        "support": "Support",
        "faq": "FAQ",
        "frequently asked questions": "Questions fréquemment posées",
        "tutorial": "Tutoriel",
        "guide": "Guide",
        "documentation": "Documentation",
        "manual": "Manuel",
        "terms": "Conditions",
        "terms of service": "Conditions d'utilisation",
        "terms and conditions": "Conditions générales",
        "privacy policy": "Politique de confidentialité",
        "cookie policy": "Politique relative aux cookies",
        "legal": "Juridique",
        "copyright": "Droits d'auteur",
        "license": "Licence",
        "version": "Version",
        "about": "À propos",
        "contact us": "Contactez-nous",
        "feedback": "Commentaires",
        "report": "Signaler",
        "report a bug": "Signaler un bug",
        "feature request": "Demande de fonctionnalité",
        "suggestion": "Suggestion",
        "improvement": "Amélioration",
        "issue": "Problème",
        "error": "Erreur",
        "warning": "Avertissement",
        "success": "Succès",
        "info": "Information",
        "notification": "Notification",
        "message": "Message",
        "alert": "Alerte",
        "confirmation": "Confirmation",
        "are you sure": "Êtes-vous sûr",
        "yes": "Oui",
        "no": "Non",
        "ok": "OK",
        "cancel": "Annuler",
        "close": "Fermer",
        "dismiss": "Ignorer",
        "continue": "Continuer",
        "proceed": "Continuer",
        "back": "Retour",
        "next": "Suivant",
        "previous": "Précédent",
        "finish": "Terminer",
        "done": "Terminé",
        "complete": "Complet",
        "submit": "Soumettre",
        "save": "Enregistrer",
        "save changes": "Enregistrer les modifications",
        "discard": "Abandonner",
        "discard changes": "Abandonner les modifications",
        "edit": "Modifier",
        "delete": "Supprimer",
        "remove": "Retirer",
        "add": "Ajouter",
        "create": "Créer",
        "new": "Nouveau",
        "update": "Mettre à jour",
        "refresh": "Actualiser",
        "reload": "Recharger",
        "reset": "Réinitialiser",
        "clear": "Effacer",
        "search": "Rechercher",
        "filter": "Filtrer",
        "sort": "Trier",
        "view": "Voir",
        "preview": "Aperçu",
        "download": "Télécharger",
        "upload": "Téléverser",
        "import": "Importer",
        "export": "Exporter",
        "print": "Imprimer",
        "share": "Partager",
        "copy": "Copier",
        "duplicate": "Dupliquer",
        "move": "Déplacer",
        "rename": "Renommer",
        "archive": "Archiver",
        "restore": "Restaurer",
        "undo": "Annuler",
        "redo": "Refaire",
        "select": "Sélectionner",
        "select all": "Tout sélectionner",
        "deselect": "Désélectionner",
        "deselect all": "Tout désélectionner",
        "show": "Afficher",
        "hide": "Masquer",
        "expand": "Développer",
        "collapse": "Réduire",
        "maximize": "Maximiser",
        "minimize": "Minimiser",
        "full screen": "Plein écran",
        "exit full screen": "Quitter le plein écran",
        "zoom in": "Zoom avant",
        "zoom out": "Zoom arrière",
        "fit to screen": "Ajuster à l'écran",
        "actual size": "Taille réelle",
        "loading": "Chargement",
        "please wait": "Veuillez patienter",
        "processing": "Traitement en cours",
        "saving": "Enregistrement",
        "deleting": "Suppression",
        "updating": "Mise à jour",
        "uploading": "Téléversement",
        "downloading": "Téléchargement",
        "sending": "Envoi",
        "receiving": "Réception",
        "connecting": "Connexion",
        "disconnecting": "Déconnexion",
        "syncing": "Synchronisation",
        "validating": "Validation",
        "checking": "Vérification",
        "searching": "Recherche",
        "filtering": "Filtrage",
        "sorting": "Tri",
        "loading more": "Chargement supplémentaire",
        "no results": "Aucun résultat",
        "no data": "Aucune donnée",
        "no items": "Aucun élément",
        "no records": "Aucun enregistrement",
        "empty": "Vide",
        "not found": "Non trouvé",
        "page not found": "Page non trouvée",
        "file not found": "Fichier non trouvé",
        "user not found": "Utilisateur non trouvé",
        "error occurred": "Une erreur s'est produite",
        "something went wrong": "Quelque chose s'est mal passé",
        "try again": "Réessayer",
        "retry": "Réessayer",
        "reload page": "Recharger la page",
        "go back": "Retour",
        "go home": "Accueil",
        "home": "Accueil",
        "dashboard": "Tableau de bord",
        "overview": "Aperçu",
        "summary": "Résumé",
        "details": "Détails",
        "information": "Informations",
        "data": "Données",
        "statistics": "Statistiques",
        "analytics": "Analytique",
        "reports": "Rapports",
        "insights": "Aperçus",
        "activity": "Activité",
        "history": "Historique",
        "timeline": "Chronologie",
        "calendar": "Calendrier",
        "schedule": "Calendrier",
        "events": "Événements",
        "tasks": "Tâches",
        "projects": "Projets",
        "files": "Fichiers",
        "documents": "Documents",
        "folders": "Dossiers",
        "attachments": "Pièces jointes",
        "images": "Images",
        "photos": "Photos",
        "videos": "Vidéos",
        "audio": "Audio",
        "media": "Médias",
        "gallery": "Galerie",
        "library": "Bibliothèque",
        "archive": "Archive",
        "trash": "Corbeille",
        "recycle bin": "Corbeille",
        "deleted items": "Éléments supprimés",
        "recent": "Récent",
        "favorites": "Favoris",
        "starred": "Favoris",
        "bookmarks": "Signets",
        "tags": "Étiquettes",
        "categories": "Catégories",
        "labels": "Libellés",
        "filters": "Filtres",
        "views": "Vues",
        "layouts": "Mises en page",
        "templates": "Modèles",
        "themes": "Thèmes",
        "styles": "Styles",
        "colors": "Couleurs",
        "fonts": "Polices",
        "icons": "Icônes",
        "images": "Images",
        "backgrounds": "Arrière-plans",
        "wallpapers": "Fonds d'écran",
        "borders": "Bordures",
        "shadows": "Ombres",
        "effects": "Effets",
        "animations": "Animations",
        "transitions": "Transitions",
        "interactions": "Interactions",
        "behaviors": "Comportements",
        "actions": "Actions",
        "events": "Événements",
        "triggers": "Déclencheurs",
        "conditions": "Conditions",
        "rules": "Règles",
        "logic": "Logique",
        "formulas": "Formules",
        "calculations": "Calculs",
        "functions": "Fonctions",
        "operations": "Opérations",
        "processes": "Processus",
        "workflows": "Flux de travail",
        "automations": "Automatisations",
        "integrations": "Intégrations",
        "connections": "Connexions",
        "apis": "APIs",
        "webhooks": "Webhooks",
        "services": "Services",
        "tools": "Outils",
        "utilities": "Utilitaires",
        "plugins": "Plugins",
        "extensions": "Extensions",
        "add-ons": "Modules complémentaires",
        "widgets": "Widgets",
        "components": "Composants",
        "modules": "Modules",
        "features": "Fonctionnalités",
        "capabilities": "Capacités",
        "permissions": "Autorisations",
        "roles": "Rôles",
        "users": "Utilisateurs",
        "groups": "Groupes",
        "teams": "Équipes",
        "organizations": "Organisations",
        "departments": "Départements",
        "divisions": "Divisions",
        "branches": "Branches",
        "offices": "Bureaux",
        "locations": "Emplacements",
        "sites": "Sites",
        "regions": "Régions",
        "countries": "Pays",
        "states": "États",
        "cities": "Villes",
        "addresses": "Adresses",
        "contacts": "Contacts",
        "people": "Personnes",
        "customers": "Clients",
        "clients": "Clients",
        "vendors": "Fournisseurs",
        "suppliers": "Fournisseurs",
        "partners": "Partenaires",
        "collaborators": "Collaborateurs",
        "contributors": "Contributeurs",
        "members": "Membres",
        "subscribers": "Abonnés",
        "followers": "Abonnés",
        "friends": "Amis",
        "connections": "Connexions",
        "network": "Réseau",
        "community": "Communauté",
        "forum": "Forum",
        "discussion": "Discussion",
        "comments": "Commentaires",
        "replies": "Réponses",
        "mentions": "Mentions",
        "notifications": "Notifications",
        "messages": "Messages",
        "inbox": "Boîte de réception",
        "sent": "Envoyés",
        "drafts": "Brouillons",
        "spam": "Spam",
        "archive": "Archive",
        "compose": "Composer",
        "reply": "Répondre",
        "reply all": "Répondre à tous",
        "forward": "Transférer",
        "send": "Envoyer",
        "receive": "Recevoir",
        "read": "Lire",
        "unread": "Non lu",
        "mark as read": "Marquer comme lu",
        "mark as unread": "Marquer comme non lu",
        "delete": "Supprimer",
        "archive": "Archiver",
        "move to": "Déplacer vers",
        "label": "Étiquette",
        "tag": "Étiqueter",
        "flag": "Signaler",
        "star": "Favori",
        "important": "Important",
        "priority": "Priorité",
        "urgent": "Urgent",
        "high": "Élevé",
        "medium": "Moyen",
        "low": "Faible",
        "normal": "Normal",
        "critical": "Critique",
        "major": "Majeur",
        "minor": "Mineur",
        "trivial": "Trivial",
        "blocker": "Bloquant",
        "open": "Ouvert",
        "closed": "Fermé",
        "resolved": "Résolu",
        "pending": "En attente",
        "in progress": "En cours",
        "on hold": "En attente",
        "cancelled": "Annulé",
        "completed": "Terminé",
        "approved": "Approuvé",
        "rejected": "Rejeté",
        "draft": "Brouillon",
        "published": "Publié",
        "scheduled": "Planifié",
        "archived": "Archivé",
        "deleted": "Supprimé",
        "active": "Actif",
        "inactive": "Inactif",
        "enabled": "Activé",
        "disabled": "Désactivé",
        "visible": "Visible",
        "hidden": "Masqué",
        "public": "Public",
        "private": "Privé",
        "shared": "Partagé",
        "restricted": "Restreint",
        "confidential": "Confidentiel",
        "internal": "Interne",
        "external": "Externe",
        "all": "Tout",
        "none": "Aucun",
        "any": "N'importe quel",
        "some": "Certains",
        "many": "Nombreux",
        "few": "Peu",
        "several": "Plusieurs",
        "other": "Autre",
        "others": "Autres",
        "more": "Plus",
        "less": "Moins",
        "most": "La plupart",
        "least": "Le moins",
        "first": "Premier",
        "last": "Dernier",
        "top": "Haut",
        "bottom": "Bas",
        "left": "Gauche",
        "right": "Droite",
        "center": "Centre",
        "middle": "Milieu",
        "start": "Début",
        "end": "Fin",
        "beginning": "Début",
        "finish": "Fin",
        "before": "Avant",
        "after": "Après",
        "above": "Au-dessus",
        "below": "En-dessous",
        "between": "Entre",
        "among": "Parmi",
        "within": "Dans",
        "outside": "À l'extérieur",
        "inside": "À l'intérieur",
        "around": "Autour",
        "near": "Près",
        "far": "Loin",
        "close": "Proche",
        "distant": "Distant",
        "adjacent": "Adjacent",
        "next": "Suivant",
        "previous": "Précédent",
        "current": "Actuel",
        "past": "Passé",
        "future": "Futur",
        "present": "Présent",
        "now": "Maintenant",
        "then": "Alors",
        "later": "Plus tard",
        "earlier": "Plus tôt",
        "soon": "Bientôt",
        "recently": "Récemment",
        "lately": "Dernièrement",
        "always": "Toujours",
        "never": "Jamais",
        "sometimes": "Parfois",
        "often": "Souvent",
        "rarely": "Rarement",
        "occasionally": "Occasionnellement",
        "frequently": "Fréquemment",
        "constantly": "Constamment",
        "continuously": "En continu",
        "temporarily": "Temporairement",
        "permanently": "Définitivement",
        "forever": "Pour toujours",
        "indefinitely": "Indéfiniment",
        "immediately": "Immédiatement",
        "instantly": "Instantanément",
        "quickly": "Rapidement",
        "slowly": "Lentement",
        "fast": "Rapide",
        "slow": "Lent",
        "speed": "Vitesse",
        "performance": "Performance",
        "efficiency": "Efficacité",
        "productivity": "Productivité",
        "quality": "Qualité",
        "quantity": "Quantité",
        "accuracy": "Précision",
        "precision": "Précision",
        "reliability": "Fiabilité",
        "stability": "Stabilité",
        "consistency": "Cohérence",
        "compatibility": "Compatibilité",
        "scalability": "Évolutivité",
        "flexibility": "Flexibilité",
        "usability": "Utilisabilité",
        "accessibility": "Accessibilité",
        "availability": "Disponibilité",
        "reliability": "Fiabilité",
        "durability": "Durabilité",
        "sustainability": "Durabilité",
        "maintainability": "Maintenabilité",
        "portability": "Portabilité",
        "interoperability": "Interopérabilité",
        "extensibility": "Extensibilité",
        "modularity": "Modularité",
        "reusability": "Réutilisabilité",
        "simplicity": "Simplicité",
        "complexity": "Complexité",
        "clarity": "Clarté",
        "transparency": "Transparence",
        "visibility": "Visibilité",
        "traceability": "Traçabilité",
        "auditability": "Auditabilité",
        "accountability": "Responsabilité",
        "compliance": "Conformité",
        "governance": "Gouvernance",
        "regulation": "Réglementation",
        "standard": "Standard",
        "guideline": "Ligne directrice",
        "policy": "Politique",
        "procedure": "Procédure",
        "protocol": "Protocole",
        "framework": "Cadre",
        "methodology": "Méthodologie",
        "approach": "Approche",
        "strategy": "Stratégie",
        "plan": "Plan",
        "roadmap": "Feuille de route",
        "vision": "Vision",
        "mission": "Mission",
        "goal": "Objectif",
        "objective": "Objectif",
        "target": "Cible",
        "milestone": "Jalon",
        "deliverable": "Livrable",
        "outcome": "Résultat",
        "output": "Production",
        "input": "Entrée",
        "requirement": "Exigence",
        "specification": "Spécification",
        "criteria": "Critères",
        "constraint": "Contrainte",
        "limitation": "Limitation",
        "assumption": "Hypothèse",
        "dependency": "Dépendance",
        "risk": "Risque",
        "issue": "Problème",
        "challenge": "Défi",
        "opportunity": "Opportunité",
        "benefit": "Avantage",
        "advantage": "Avantage",
        "disadvantage": "Inconvénient",
        "strength": "Force",
        "weakness": "Faiblesse",
        "threat": "Menace",
        "impact": "Impact",
        "effect": "Effet",
        "consequence": "Conséquence",
        "result": "Résultat",
        "outcome": "Résultat",
        "achievement": "Réalisation",
        "success": "Succès",
        "failure": "Échec",
        "improvement": "Amélioration",
        "enhancement": "Amélioration",
        "optimization": "Optimisation",
        "innovation": "Innovation",
        "transformation": "Transformation",
        "change": "Changement",
        "modification": "Modification",
        "adjustment": "Ajustement",
        "adaptation": "Adaptation",
        "customization": "Personnalisation",
        "configuration": "Configuration",
        "setup": "Configuration",
        "installation": "Installation",
        "deployment": "Déploiement",
        "implementation": "Mise en œuvre",
        "migration": "Migration",
        "upgrade": "Mise à niveau",
        "update": "Mise à jour",
        "patch": "Correctif",
        "fix": "Correction",
        "bug": "Bug",
        "defect": "Défaut",
        "fault": "Défaut",
        "problem": "Problème",
        "issue": "Problème",
        "incident": "Incident",
        "outage": "Panne",
        "downtime": "Temps d'arrêt",
        "maintenance": "Maintenance",
        "service": "Service",
        "repair": "Réparation",
        "replacement": "Remplacement",
        "recovery": "Récupération",
        "backup": "Sauvegarde",
        "restore": "Restaurer",
        "disaster recovery": "Reprise après sinistre",
        "business continuity": "Continuité des activités",
        "high availability": "Haute disponibilité",
        "fault tolerance": "Tolérance aux pannes",
        "redundancy": "Redondance",
        "failover": "Basculement",
        "load balancing": "Répartition de charge",
        "cluster": "Cluster",
        "node": "Nœud",
        "server": "Serveur",
        "client": "Client",
        "host": "Hôte",
        "network": "Réseau",
        "connection": "Connexion",
        "bandwidth": "Bande passante",
        "latency": "Latence",
        "throughput": "Débit",
        "capacity": "Capacité",
        "usage": "Utilisation",
        "consumption": "Consommation",
        "quota": "Quota",
        "limit": "Limite",
        "threshold": "Seuil",
        "alert": "Alerte",
        "alarm": "Alarme",
        "monitor": "Moniteur",
        "tracking": "Suivi",
        "logging": "Journalisation",
        "audit": "Audit",
        "trace": "Trace",
        "debug": "Déboguer",
        "test": "Test",
        "testing": "Test",
        "validation": "Validation",
        "verification": "Vérification",
        "review": "Révision",
        "inspection": "Inspection",
        "analysis": "Analyse",
        "assessment": "Évaluation",
        "evaluation": "Évaluation",
        "measurement": "Mesure",
        "metric": "Métrique",
        "indicator": "Indicateur",
        "kpi": "KPI",
        "benchmark": "Référence",
        "comparison": "Comparaison",
        "baseline": "Référence",
        "trend": "Tendance",
        "pattern": "Modèle",
        "anomaly": "Anomalie",
        "outlier": "Valeur aberrante",
        "correlation": "Corrélation",
        "causation": "Causalité",
        "relationship": "Relation",
        "association": "Association",
        "dependency": "Dépendance",
        "hierarchy": "Hiérarchie",
        "structure": "Structure",
        "organization": "Organisation",
        "arrangement": "Disposition",
        "order": "Ordre",
        "sequence": "Séquence",
        "series": "Série",
        "set": "Ensemble",
        "collection": "Collection",
        "group": "Groupe",
        "batch": "Lot",
        "bundle": "Paquet",
        "package": "Package",
        "container": "Conteneur",
        "wrapper": "Enveloppe",
        "envelope": "Enveloppe",
        "layer": "Couche",
        "level": "Niveau",
        "tier": "Niveau",
        "stage": "Étape",
        "phase": "Phase",
        "step": "Étape",
        "process": "Processus",
        "procedure": "Procédure",
        "method": "Méthode",
        "technique": "Technique",
        "approach": "Approche",
        "way": "Façon",
        "manner": "Manière",
        "mode": "Mode",
        "style": "Style",
        "format": "Format",
        "layout": "Mise en page",
        "design": "Design",
        "pattern": "Modèle",
        "template": "Modèle",
        "blueprint": "Plan",
        "schema": "Schéma",
        "model": "Modèle",
        "prototype": "Prototype",
        "mockup": "Maquette",
        "wireframe": "Maquette filaire",
        "sketch": "Esquisse",
        "draft": "Brouillon",
        "outline": "Plan",
        "framework": "Cadre",
        "architecture": "Architecture",
        "infrastructure": "Infrastructure",
        "platform": "Plateforme",
        "environment": "Environnement",
        "ecosystem": "Écosystème",
        "landscape": "Paysage",
        "context": "Contexte",
        "scope": "Portée",
        "domain": "Domaine",
        "area": "Zone",
        "field": "Domaine",
        "sector": "Secteur",
        "industry": "Industrie",
        "market": "Marché",
        "segment": "Segment",
        "niche": "Niche",
        "category": "Catégorie",
        "class": "Classe",
        "type": "Type",
        "kind": "Genre",
        "sort": "Sorte",
        "variety": "Variété",
        "variant": "Variante",
        "version": "Version",
        "edition": "Édition",
        "release": "Version",
        "build": "Build",
        "revision": "Révision",
        "iteration": "Itération",
        "generation": "Génération",
        "cycle": "Cycle",
        "round": "Tour",
        "turn": "Tour",
        "rotation": "Rotation",
        "shift": "Équipe",
        "period": "Période",
        "term": "Terme",
        "duration": "Durée",
        "interval": "Intervalle",
        "range": "Plage",
        "span": "Étendue",
        "extent": "Étendue",
        "scope": "Portée",
        "scale": "Échelle",
        "size": "Taille",
        "dimension": "Dimension",
        "measurement": "Mesure",
        "length": "Longueur",
        "width": "Largeur",
        "height": "Hauteur",
        "depth": "Profondeur",
        "area": "Surface",
        "volume": "Volume",
        "capacity": "Capacité",
        "weight": "Poids",
        "mass": "Masse",
        "density": "Densité",
        "pressure": "Pression",
        "temperature": "Température",
        "humidity": "Humidité",
        "moisture": "Humidité",
        "level": "Niveau",
        "amount": "Montant",
        "quantity": "Quantité",
        "number": "Nombre",
        "count": "Nombre",
        "total": "Total",
        "sum": "Somme",
        "subtotal": "Sous-total",
        "average": "Moyenne",
        "mean": "Moyenne",
        "median": "Médiane",
        "mode": "Mode",
        "range": "Plage",
        "variance": "Variance",
        "deviation": "Écart",
        "standard deviation": "Écart type",
        "distribution": "Distribution",
        "frequency": "Fréquence",
        "probability": "Probabilité",
        "chance": "Chance",
        "likelihood": "Probabilité",
        "odds": "Cotes",
        "ratio": "Rapport",
        "proportion": "Proportion",
        "percentage": "Pourcentage",
        "rate": "Taux",
        "fraction": "Fraction",
        "decimal": "Décimal",
        "integer": "Entier",
        "number": "Nombre",
        "digit": "Chiffre",
        "figure": "Chiffre",
        "numeric": "Numérique",
        "numerical": "Numérique",
        "mathematical": "Mathématique",
        "calculation": "Calcul",
        "computation": "Calcul",
        "operation": "Opération",
        "function": "Fonction",
        "formula": "Formule",
        "equation": "Équation",
        "expression": "Expression",
        "variable": "Variable",
        "constant": "Constante",
        "parameter": "Paramètre",
        "argument": "Argument",
        "value": "Valeur",
        "result": "Résultat",
        "output": "Sortie",
        "input": "Entrée",
        "data": "Données",
        "information": "Informations",
        "content": "Contenu",
        "text": "Texte",
        "string": "Chaîne",
        "character": "Caractère",
        "letter": "Lettre",
        "word": "Mot",
        "sentence": "Phrase",
        "paragraph": "Paragraphe",
        "line": "Ligne",
        "row": "Ligne",
        "column": "Colonne",
        "cell": "Cellule",
        "table": "Tableau",
        "list": "Liste",
        "array": "Tableau",
        "matrix": "Matrice",
        "grid": "Grille",
        "tree": "Arbre",
        "graph": "Graphe",
        "chart": "Graphique",
        "diagram": "Diagramme",
        "map": "Carte",
        "visualization": "Visualisation",
        "representation": "Représentation",
        "illustration": "Illustration",
        "image": "Image",
        "picture": "Image",
        "photo": "Photo",
        "graphic": "Graphique",
        "icon": "Icône",
        "symbol": "Symbole",
        "logo": "Logo",
        "badge": "Badge",
        "label": "Étiquette",
        "tag": "Étiquette",
        "marker": "Marqueur",
        "indicator": "Indicateur",
        "flag": "Drapeau",
        "banner": "Bannière",
        "header": "En-tête",
        "footer": "Pied de page",
        "sidebar": "Barre latérale",
        "navigation": "Navigation",
        "menu": "Menu",
        "toolbar": "Barre d'outils",
        "panel": "Panneau",
        "tab": "Onglet",
        "window": "Fenêtre",
        "dialog": "Dialogue",
        "modal": "Modal",
        "popup": "Popup",
        "tooltip": "Info-bulle",
        "dropdown": "Menu déroulant",
        "select": "Sélectionner",
        "checkbox": "Case à cocher",
        "radio": "Bouton radio",
        "button": "Bouton",
        "link": "Lien",
        "hyperlink": "Hyperlien",
        "anchor": "Ancre",
        "breadcrumb": "Fil d'Ariane",
        "pagination": "Pagination",
        "page": "Page",
        "slide": "Diapositive",
        "screen": "Écran",
        "view": "Vue",
        "interface": "Interface",
        "ui": "Interface utilisateur",
        "ux": "Expérience utilisateur",
        "design": "Design",
        "layout": "Mise en page",
        "component": "Composant",
        "element": "Élément",
        "widget": "Widget",
        "control": "Contrôle",
        "input": "Entrée",
        "output": "Sortie",
        "form": "Formulaire",
        "field": "Champ",
        "textbox": "Zone de texte",
        "textarea": "Zone de texte",
        "editor": "Éditeur",
        "picker": "Sélecteur",
        "selector": "Sélecteur",
        "chooser": "Sélecteur",
        "slider": "Curseur",
        "switch": "Commutateur",
        "toggle": "Basculer",
        "stepper": "Compteur",
        "spinner": "Spinner",
        "progress": "Progrès",
        "progressbar": "Barre de progression",
        "loader": "Chargeur",
        "loading indicator": "Indicateur de chargement",
        "placeholder": "Espace réservé",
        "skeleton": "Squelette",
        "shimmer": "Scintillement",
        "animation": "Animation",
        "transition": "Transition",
        "effect": "Effet",
        "transformation": "Transformation",
        "motion": "Mouvement",
        "gesture": "Geste",
        "interaction": "Interaction",
        "event": "Événement",
        "action": "Action",
        "trigger": "Déclencheur",
        "handler": "Gestionnaire",
        "listener": "Écouteur",
        "callback": "Rappel",
        "function": "Fonction",
        "method": "Méthode",
        "property": "Propriété",
        "attribute": "Attribut",
        "setting": "Paramètre",
        "option": "Option",
        "choice": "Choix",
        "preference": "Préférence",
        "default": "Par défaut",
        "custom": "Personnalisé",
        "override": "Remplacer",
        "inherit": "Hériter",
        "extend": "Étendre",
        "implement": "Implémenter",
        "apply": "Appliquer",
        "use": "Utiliser",
        "call": "Appeler",
        "invoke": "Invoquer",
        "execute": "Exécuter",
        "run": "Exécuter",
        "start": "Démarrer",
        "stop": "Arrêter",
        "pause": "Pause",
        "resume": "Reprendre",
        "restart": "Redémarrer",
        "reload": "Recharger",
        "refresh": "Actualiser",
        "sync": "Synchroniser",
        "synchronize": "Synchroniser",
        "update": "Mettre à jour",
        "fetch": "Récupérer",
        "retrieve": "Récupérer",
        "get": "Obtenir",
        "set": "Définir",
        "put": "Mettre",
        "post": "Publier",
        "patch": "Patcher",
        "delete": "Supprimer",
        "request": "Requête",
        "response": "Réponse",
        "query": "Requête",
        "mutation": "Mutation",
        "subscription": "Abonnement",
        "endpoint": "Point de terminaison",
        "route": "Route",
        "path": "Chemin",
        "url": "URL",
        "uri": "URI",
        "link": "Lien",
        "redirect": "Redirection",
        "forward": "Transférer",
        "navigate": "Naviguer",
        "go to": "Aller à",
        "visit": "Visiter",
        "access": "Accéder",
        "enter": "Entrer",
        "exit": "Sortir",
        "leave": "Quitter",
        "return": "Retourner",
        "escape": "Échapper",
        "quit": "Quitter",
        "close": "Fermer",
        "end": "Fin",
        "terminate": "Terminer",
        "kill": "Tuer",
        "abort": "Abandonner",
        "interrupt": "Interrompre",
        "break": "Pause",
        "continue": "Continuer",
        "skip": "Ignorer",
        "bypass": "Contourner",
        "override": "Remplacer",
        "ignore": "Ignorer",
        "exclude": "Exclure",
        "include": "Inclure",
        "add": "Ajouter",
        "append": "Ajouter",
        "prepend": "Préfixer",
        "insert": "Insérer",
        "remove": "Retirer",
        "delete": "Supprimer",
        "erase": "Effacer",
        "clear": "Effacer",
        "clean": "Nettoyer",
        "purge": "Purger",
        "flush": "Vider",
        "empty": "Vider",
        "truncate": "Tronquer",
        "trim": "Rogner",
        "strip": "Dépouiller",
        "replace": "Remplacer",
        "substitute": "Substituer",
        "swap": "Échanger",
        "exchange": "Échanger",
        "switch": "Changer",
        "change": "Changer",
        "modify": "Modifier",
        "alter": "Modifier",
        "adjust": "Ajuster",
        "tune": "Ajuster",
        "tweak": "Ajuster",
        "customize": "Personnaliser",
        "personalize": "Personnaliser",
        "configure": "Configurer",
        "setup": "Configurer",
        "initialize": "Initialiser",
        "prepare": "Préparer",
        "build": "Construire",
        "compile": "Compiler",
        "generate": "Générer",
        "create": "Créer",
        "make": "Faire",
        "produce": "Produire",
        "construct": "Construire",
        "assemble": "Assembler",
        "compose": "Composer",
        "write": "Écrire",
        "author": "Créer",
        "draft": "Rédiger",
        "edit": "Modifier",
        "revise": "Réviser",
        "review": "Réviser",
        "check": "Vérifier",
        "verify": "Vérifier",
        "validate": "Valider",
        "confirm": "Confirmer",
        "approve": "Approuver",
        "accept": "Accepter",
        "reject": "Rejeter",
        "decline": "Refuser",
        "deny": "Refuser",
        "refuse": "Refuser",
        "cancel": "Annuler",
        "revoke": "Révoquer",
        "withdraw": "Retirer",
        "retract": "Rétracter",
        "undo": "Annuler",
        "revert": "Rétablir",
        "rollback": "Annuler",
        "restore": "Restaurer",
        "recover": "Récupérer",
        "rescue": "Sauver",
        "save": "Enregistrer",
        "preserve": "Préserver",
        "keep": "Garder",
        "retain": "Conserver",
        "maintain": "Maintenir",
        "hold": "Tenir",
        "store": "Stocker",
        "cache": "Mettre en cache",
        "buffer": "Tamponner",
        "queue": "Mettre en file d'attente",
        "stack": "Empiler",
        "push": "Pousser",
        "pop": "Dépiler",
        "peek": "Apercevoir",
        "shift": "Décaler",
        "unshift": "Ajouter au début",
        "slice": "Découper",
        "splice": "Épisser",
        "split": "Diviser",
        "join": "Joindre",
        "merge": "Fusionner",
        "combine": "Combiner",
        "concat": "Concaténer",
        "unite": "Unir",
        "link": "Lier",
        "connect": "Connecter",
        "attach": "Attacher",
        "bind": "Lier",
        "associate": "Associer",
        "relate": "Relier",
        "map": "Mapper",
        "match": "Correspondre",
        "find": "Trouver",
        "search": "Rechercher",
        "seek": "Chercher",
        "locate": "Localiser",
        "discover": "Découvrir",
        "detect": "Détecter",
        "identify": "Identifier",
        "recognize": "Reconnaître",
        "distinguish": "Distinguer",
        "differentiate": "Différencier",
        "compare": "Comparer",
        "contrast": "Contraster",
        "measure": "Mesurer",
        "evaluate": "Évaluer",
        "assess": "Évaluer",
        "estimate": "Estimer",
        "calculate": "Calculer",
        "compute": "Calculer",
        "count": "Compter",
        "sum": "Additionner",
        "add": "Ajouter",
        "subtract": "Soustraire",
        "multiply": "Multiplier",
        "divide": "Diviser",
        "increment": "Incrémenter",
        "decrement": "Décrémenter",
        "increase": "Augmenter",
        "decrease": "Diminuer",
        "grow": "Croître",
        "shrink": "Rétrécir",
        "expand": "Développer",
        "contract": "Contracter",
        "extend": "Étendre",
        "reduce": "Réduire",
        "minimize": "Minimiser",
        "maximize": "Maximiser",
        "optimize": "Optimiser",
        "improve": "Améliorer",
        "enhance": "Améliorer",
        "upgrade": "Mettre à niveau",
        "downgrade": "Rétrograder",
        "promote": "Promouvoir",
        "demote": "Rétrograder",
        "elevate": "Élever",
        "lower": "Abaisser",
        "raise": "Lever",
        "lift": "Soulever",
        "drop": "Déposer",
        "fall": "Tomber",
        "rise": "Monter",
        "ascend": "Monter",
        "descend": "Descendre",
        "climb": "Grimper",
        "slide": "Glisser",
        "scroll": "Défiler",
        "pan": "Panoramique",
        "zoom": "Zoom",
        "scale": "Échelle",
        "resize": "Redimensionner",
        "rotate": "Pivoter",
        "flip": "Retourner",
        "mirror": "Miroir",
        "reflect": "Refléter",
        "invert": "Inverser",
        "reverse": "Inverser",
        "transpose": "Transposer",
        "transform": "Transformer",
        "convert": "Convertir",
        "translate": "Traduire",
        "interpret": "Interpréter",
        "parse": "Analyser",
        "serialize": "Sérialiser",
        "deserialize": "Désérialiser",
        "encode": "Encoder",
        "decode": "Décoder",
        "encrypt": "Chiffrer",
        "decrypt": "Déchiffrer",
        "hash": "Hacher",
        "sign": "Signer",
        "verify signature": "Vérifier la signature",
        "authenticate": "Authentifier",
        "authorize": "Autoriser",
        "grant": "Accorder",
        "permit": "Permettre",
        "allow": "Autoriser",
        "enable": "Activer",
        "disable": "Désactiver",
        "activate": "Activer",
        "deactivate": "Désactiver",
        "turn on": "Activer",
        "turn off": "Désactiver",
        "switch on": "Allumer",
        "switch off": "Éteindre",
        "power on": "Allumer",
        "power off": "Éteindre",
        "boot": "Démarrer",
        "shutdown": "Arrêter",
        "reboot": "Redémarrer",
        "restart": "Redémarrer",
        "reset": "Réinitialiser",
        "initialize": "Initialiser",
        "launch": "Lancer",
        "open": "Ouvrir",
        "close": "Fermer",
        "lock": "Verrouiller",
        "unlock": "Déverrouiller",
        "secure": "Sécuriser",
        "protect": "Protéger",
        "safeguard": "Protéger",
        "defend": "Défendre",
        "shield": "Protéger",
        "guard": "Garder",
        "watch": "Surveiller",
        "monitor": "Surveiller",
        "observe": "Observer",
        "track": "Suivre",
        "trace": "Tracer",
        "follow": "Suivre",
        "pursue": "Poursuivre",
        "chase": "Poursuivre",
        "hunt": "Chasser",
        "capture": "Capturer",
        "catch": "Attraper",
        "grab": "Saisir",
        "seize": "Saisir",
        "take": "Prendre",
        "get": "Obtenir",
        "acquire": "Acquérir",
        "obtain": "Obtenir",
        "receive": "Recevoir",
        "accept": "Accepter",
        "collect": "Collecter",
        "gather": "Rassembler",
        "accumulate": "Accumuler",
        "aggregate": "Agréger",
        "consolidate": "Consolider",
        "centralize": "Centraliser",
        "decentralize": "Décentraliser",
        "distribute": "Distribuer",
        "spread": "Diffuser",
        "scatter": "Disperser",
        "disperse": "Disperser",
        "broadcast": "Diffuser",
        "publish": "Publier",
        "announce": "Annoncer",
        "declare": "Déclarer",
        "proclaim": "Proclamer",
        "state": "Déclarer",
        "assert": "Affirmer",
        "claim": "Revendiquer",
        "argue": "Argumenter",
        "debate": "Débattre",
        "discuss": "Discuter",
        "talk": "Parler",
        "speak": "Parler",
        "say": "Dire",
        "tell": "Dire",
        "communicate": "Communiquer",
        "convey": "Transmettre",
        "express": "Exprimer",
        "articulate": "Articuler",
        "formulate": "Formuler",
        "phrase": "Formuler",
        "word": "Formuler",
        "describe": "Décrire",
        "explain": "Expliquer",
        "clarify": "Clarifier",
        "elaborate": "Élaborer",
        "detail": "Détailler",
        "specify": "Spécifier",
        "define": "Définir",
        "determine": "Déterminer",
        "decide": "Décider",
        "choose": "Choisir",
        "select": "Sélectionner",
        "pick": "Choisir",
        "opt": "Opter",
        "prefer": "Préférer",
        "favor": "Favoriser",
        "like": "Aimer",
        "love": "Adorer",
        "enjoy": "Apprécier",
        "appreciate": "Apprécier",
        "value": "Valoriser",
        "treasure": "Chérir",
        "cherish": "Chérir",
        "care": "Se soucier",
        "concern": "Concerner",
        "matter": "Importer",
        "count": "Compter",
        "signify": "Signifier",
        "mean": "Signifier",
        "indicate": "Indiquer",
        "show": "Montrer",
        "display": "Afficher",
        "present": "Présenter",
        "exhibit": "Exposer",
        "demonstrate": "Démontrer",
        "prove": "Prouver",
        "establish": "Établir",
        "confirm": "Confirmer",
        "certify": "Certifier",
        "attest": "Attester",
        "testify": "Témoigner",
        "witness": "Témoigner",
        "see": "Voir",
        "view": "Voir",
        "look": "Regarder",
        "watch": "Regarder",
        "observe": "Observer",
        "notice": "Remarquer",
        "perceive": "Percevoir",
        "sense": "Sentir",
        "feel": "Ressentir",
        "experience": "Expérimenter",
        "undergo": "Subir",
        "endure": "Endurer",
        "suffer": "Souffrir",
        "bear": "Supporter",
        "tolerate": "Tolérer",
        "accept": "Accepter",
        "embrace": "Embrasser",
        "welcome": "Accueillir",
        "greet": "Saluer",
        "meet": "Rencontrer",
        "encounter": "Rencontrer",
        "face": "Affronter",
        "confront": "Confronter",
        "challenge": "Défier",
        "oppose": "S'opposer",
        "resist": "Résister",
        "fight": "Combattre",
        "battle": "Combattre",
        "struggle": "Lutter",
        "strive": "S'efforcer",
        "try": "Essayer",
        "attempt": "Tenter",
        "endeavor": "S'efforcer",
        "effort": "Effort",
        "work": "Travailler",
        "labor": "Travailler",
        "toil": "Peiner",
        "task": "Tâche",
        "job": "Travail",
        "duty": "Devoir",
        "responsibility": "Responsabilité",
        "obligation": "Obligation",
        "commitment": "Engagement",
        "promise": "Promesse",
        "pledge": "Engagement",
        "vow": "Vœu",
        "oath": "Serment",
        "agreement": "Accord",
        "contract": "Contrat",
        "deal": "Accord",
        "arrangement": "Arrangement",
        "understanding": "Entente",
        "consensus": "Consensus",
        "accord": "Accord",
        "harmony": "Harmonie",
        "unity": "Unité",
        "cooperation": "Coopération",
        "collaboration": "Collaboration",
        "partnership": "Partenariat",
        "alliance": "Alliance",
        "coalition": "Coalition",
        "union": "Union",
        "association": "Association",
        "organization": "Organisation",
        "institution": "Institution",
        "establishment": "Établissement",
        "entity": "Entité",
        "body": "Organisme",
        "agency": "Agence",
        "bureau": "Bureau",
        "office": "Bureau",
        "department": "Département",
        "division": "Division",
        "section": "Section",
        "unit": "Unité",
        "team": "Équipe",
        "crew": "Équipage",
        "staff": "Personnel",
        "personnel": "Personnel",
        "workforce": "Main-d'œuvre",
        "employees": "Employés",
        "workers": "Travailleurs",
        "members": "Membres",
        "participants": "Participants",
        "attendees": "Participants",
        "guests": "Invités",
        "visitors": "Visiteurs",
        "audience": "Audience",
        "viewers": "Spectateurs",
        "readers": "Lecteurs",
        "users": "Utilisateurs",
        "customers": "Clients",
        "clients": "Clients",
        "consumers": "Consommateurs",
        "buyers": "Acheteurs",
        "purchasers": "Acheteurs",
        "shoppers": "Acheteurs",
        "patrons": "Clients",
        "subscribers": "Abonnés",
        "followers": "Abonnés",
        "fans": "Fans",
        "supporters": "Supporters",
        "advocates": "Défenseurs",
        "champions": "Champions",
        "leaders": "Dirigeants",
        "managers": "Gestionnaires",
        "executives": "Cadres",
        "directors": "Directeurs",
        "officers": "Dirigeants",
        "officials": "Responsables",
        "authorities": "Autorités",
        "experts": "Experts",
        "specialists": "Spécialistes",
        "professionals": "Professionnels",
        "practitioners": "Praticiens",
        "consultants": "Consultants",
        "advisors": "Conseillers",
        "counselors": "Conseillers",
        "mentors": "Mentors",
        "coaches": "Coachs",
        "trainers": "Formateurs",
        "instructors": "Instructeurs",
        "teachers": "Enseignants",
        "educators": "Éducateurs",
        "professors": "Professeurs",
        "lecturers": "Conférenciers",
        "tutors": "Tuteurs",
        "guides": "Guides",
        "helpers": "Assistants",
        "assistants": "Assistants",
        "aides": "Aides",
        "deputies": "Adjoints",
        "representatives": "Représentants",
        "delegates": "Délégués",
        "agents": "Agents",
        "proxies": "Mandataires",
        "ambassadors": "Ambassadeurs",
        "envoys": "Émissaires",
        "messengers": "Messagers",
        "carriers": "Transporteurs",
        "couriers": "Coursiers",
        "deliverers": "Livreurs",
        "providers": "Fournisseurs",
        "suppliers": "Fournisseurs",
        "vendors": "Vendeurs",
        "sellers": "Vendeurs",
        "merchants": "Marchands",
        "retailers": "Détaillants",
        "dealers": "Revendeurs",
        "distributors": "Distributeurs",
        "wholesalers": "Grossistes",
        "manufacturers": "Fabricants",
        "producers": "Producteurs",
        "makers": "Fabricants",
        "creators": "Créateurs",
        "developers": "Développeurs",
        "designers": "Concepteurs",
        "architects": "Architectes",
        "engineers": "Ingénieurs",
        "builders": "Constructeurs",
        "constructors": "Constructeurs",
        "installers": "Installateurs",
        "technicians": "Techniciens",
        "mechanics": "Mécaniciens",
        "operators": "Opérateurs",
        "drivers": "Conducteurs",
        "pilots": "Pilotes",
        "captains": "Capitaines",
        "commanders": "Commandants",
        "chiefs": "Chefs",
        "heads": "Chefs",
        "principals": "Directeurs",
        "presidents": "Présidents",
        "chairmen": "Présidents",
        "chairpersons": "Présidents",
        "chairwomen": "Présidentes",
        "coordinators": "Coordonnateurs",
        "supervisors": "Superviseurs",
        "overseers": "Superviseurs",
        "inspectors": "Inspecteurs",
        "auditors": "Auditeurs",
        "examiners": "Examinateurs",
        "reviewers": "Réviseurs",
        "evaluators": "Évaluateurs",
        "assessors": "Évaluateurs",
        "judges": "Juges",
        "arbitrators": "Arbitres",
        "mediators": "Médiateurs",
        "negotiators": "Négociateurs",
        "brokers": "Courtiers",
        "intermediaries": "Intermédiaires",
        "facilitators": "Facilitateurs",
        "enablers": "Facilitateurs",
        "supporters": "Supporters",
        "backers": "Soutiens",
        "sponsors": "Sponsors",
        "donors": "Donateurs",
        "contributors": "Contributeurs",
        "investors": "Investisseurs",
        "shareholders": "Actionnaires",
        "stakeholders": "Parties prenantes",
        "owners": "Propriétaires",
        "proprietors": "Propriétaires",
        "landlords": "Propriétaires",
        "tenants": "Locataires",
        "renters": "Locataires",
        "lessees": "Locataires",
        "lessors": "Bailleurs",
        "lessors": "Bailleurs",
        "borrowers": "Emprunteurs",
        "lenders": "Prêteurs",
        "creditors": "Créanciers",
        "debtors": "Débiteurs",
        "payers": "Payeurs",
        "payees": "Bénéficiaires",
        "recipients": "Destinataires",
        "beneficiaries": "Bénéficiaires",
        "heirs": "Héritiers",
        "successors": "Successeurs",
        "predecessors": "Prédécesseurs",
        "ancestors": "Ancêtres",
        "descendants": "Descendants",
        "relatives": "Proches",
        "family members": "Membres de la famille",
        "kin": "Famille",
        "kindred": "Parenté",
        "relations": "Relations",
        "connections": "Connexions",
        "associates": "Associés",
        "colleagues": "Collègues",
        "coworkers": "Collègues",
        "teammates": "Coéquipiers",
        "partners": "Partenaires",
        "collaborators": "Collaborateurs",
        "allies": "Alliés",
        "friends": "Amis",
        "companions": "Compagnons",
        "mates": "Camarades",
        "buddies": "Copains",
        "pals": "Amis",
        "acquaintances": "Connaissances",
        "neighbors": "Voisins",
        "strangers": "Inconnus",
        "foreigners": "Étrangers",
        "aliens": "Étrangers",
        "outsiders": "Personnes extérieures",
        "newcomers": "Nouveaux venus",
        "immigrants": "Immigrants",
        "migrants": "Migrants",
        "refugees": "Réfugiés",
        "exiles": "Exilés",
        "expatriates": "Expatriés",
        "emigrants": "Émigrés",
        "settlers": "Colons",
        "colonists": "Colons",
        "pioneers": "Pionniers",
        "explorers": "Explorateurs",
        "travelers": "Voyageurs",
        "tourists": "Touristes",
        "sightseers": "Touristes",
        "vacationers": "Vacanciers",
        "holidaymakers": "Vacanciers",
        "passengers": "Passagers",
        "commuters": "Navetteurs",
        "pedestrians": "Piétons",
        "cyclists": "Cyclistes",
        "motorists": "Automobilistes",
        "drivers": "Conducteurs",
        "riders": "Passagers",
    }

    for key, value in tax_translations.items():
        if key in text_lower:
            return value

    # Return original if no translation found
    return english_text

def main():
    base_dir = Path("/home/cn/Desktop/HomeAiCode/swissai-tax/src/locales")
    en_file = base_dir / "en" / "translation.json"
    fr_file = base_dir / "fr" / "translation.json"

    # Load both files
    with open(en_file, 'r', encoding='utf-8') as f:
        en_data = json.load(f)

    with open(fr_file, 'r', encoding='utf-8') as f:
        fr_data = json.load(f)

    # Get all keys from English
    en_keys = set(get_all_keys(en_data))
    fr_keys = set(get_all_keys(fr_data))

    # Find missing keys
    missing_keys = en_keys - fr_keys

    print(f"Found {len(missing_keys)} missing keys in French translation")

    # Add missing translations
    translated_count = 0
    for key in sorted(missing_keys):
        en_value = get_nested_value(en_data, key)
        if isinstance(en_value, str):
            fr_value = translate_text(en_value)
            set_nested_value(fr_data, key, fr_value)
            translated_count += 1
            if translated_count <= 10:  # Show first 10 examples
                print(f"  {key}: {en_value} -> {fr_value}")

    # Save updated French file
    with open(fr_file, 'w', encoding='utf-8') as f:
        json.dump(fr_data, f, ensure_ascii=False, indent=2)

    print(f"\nDone. {translated_count} keys translated to French.")
    return translated_count

if __name__ == "__main__":
    main()
