-- Seed interview questions for SwissAI Tax
-- Based on the Q01-Q14 interview flow

SET search_path TO swisstax;

-- Clear existing questions
TRUNCATE questions CASCADE;

-- Insert interview questions
INSERT INTO questions (id, category, question_text_de, question_text_en, question_text_fr, question_text_it,
                       question_type, options, validation_rules, depends_on, depends_on_value, sort_order, is_active)
VALUES
-- Basic Information
('Q01', 'personal',
 'Was ist Ihr Zivilstand?',
 'What is your marital status?',
 'Quel est votre état civil?',
 'Qual è il suo stato civile?',
 'select',
 '{"options": ["single", "married", "divorced", "widowed", "separated", "registered_partnership"]}',
 '{"required": true}',
 NULL, NULL, 1, true),

('Q02', 'personal',
 'Haben Sie Kinder?',
 'Do you have children?',
 'Avez-vous des enfants?',
 'Ha dei figli?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 2, true),

('Q02a', 'personal',
 'Wie viele Kinder haben Sie?',
 'How many children do you have?',
 'Combien d''enfants avez-vous?',
 'Quanti figli hai?',
 'number',
 NULL,
 '{"required": true, "min": 1, "max": 20}',
 'Q02', '{"answer": true}', 3, true),

('Q02b', 'personal',
 'Alter der Kinder (kommasepariert)',
 'Ages of children (comma-separated)',
 'Âge des enfants (séparés par des virgules)',
 'Età dei bambini (separati da virgole)',
 'text',
 NULL,
 '{"required": true, "pattern": "^[0-9, ]+$"}',
 'Q02', '{"answer": true}', 4, true),

-- Income Information
('Q03', 'income',
 'Haben Sie Einkommen aus unselbständiger Arbeit?',
 'Do you have income from employment?',
 'Avez-vous des revenus d''activité salariée?',
 'Hai reddito da lavoro dipendente?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 5, true),

('Q04', 'income',
 'Haben Sie Einkommen aus selbständiger Arbeit?',
 'Do you have income from self-employment?',
 'Avez-vous des revenus d''activité indépendante?',
 'Hai reddito da lavoro autonomo?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 6, true),

('Q05', 'income',
 'Haben Sie Kapitaleinkommen (Zinsen, Dividenden)?',
 'Do you have capital income (interest, dividends)?',
 'Avez-vous des revenus du capital (intérêts, dividendes)?',
 'Hai reddito da capitale (interessi, dividendi)?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 7, true),

('Q06', 'property',
 'Besitzen Sie Immobilien?',
 'Do you own real estate?',
 'Possédez-vous des biens immobiliers?',
 'Possiedi immobili?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 8, true),

('Q06a', 'property',
 'Art der Immobilie',
 'Type of property',
 'Type de propriété',
 'Tipo di proprietà',
 'multiselect',
 '{"options": ["primary_residence", "rental_property", "vacation_home", "commercial", "land"]}',
 '{"required": true}',
 'Q06', '{"answer": true}', 9, true),

-- Deductions
('Q07', 'deductions',
 'Haben Sie Beiträge an die Säule 3a geleistet?',
 'Did you contribute to Pillar 3a?',
 'Avez-vous cotisé au pilier 3a?',
 'Hai contribuito al pilastro 3a?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 10, true),

('Q08', 'deductions',
 'Haben Sie berufliche Aus- und Weiterbildungskosten?',
 'Do you have professional training expenses?',
 'Avez-vous des frais de formation professionnelle?',
 'Hai spese di formazione professionale?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 11, true),

('Q09', 'deductions',
 'Haben Sie Krankheits- und Unfallkosten?',
 'Do you have medical and accident expenses?',
 'Avez-vous des frais de maladie et d''accident?',
 'Hai spese mediche e di infortunio?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 12, true),

('Q10', 'deductions',
 'Leisten Sie Unterhaltszahlungen?',
 'Do you pay alimony?',
 'Payez-vous une pension alimentaire?',
 'Paghi gli alimenti?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 13, true),

-- Special Situations
('Q11', 'special',
 'Haben Sie Einkommen aus dem Ausland?',
 'Do you have foreign income?',
 'Avez-vous des revenus de l''étranger?',
 'Hai reddito dall''estero?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 14, true),

('Q12', 'special',
 'Haben Sie Vermögen im Ausland?',
 'Do you have foreign assets?',
 'Avez-vous des actifs à l''étranger?',
 'Hai patrimonio all''estero?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 15, true),

('Q13', 'residence',
 'Sind Sie das ganze Jahr in der Schweiz steuerpflichtig?',
 'Were you tax resident in Switzerland for the full year?',
 'Avez-vous été résident fiscal en Suisse toute l''année?',
 'Sei stato residente fiscale in Svizzera per tutto l''anno?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 16, true),

('Q14', 'crypto',
 'Besitzen oder handeln Sie mit Kryptowährungen?',
 'Do you own or trade cryptocurrencies?',
 'Possédez-vous ou négociez-vous des crypto-monnaies?',
 'Possiedi o scambi criptovalute?',
 'boolean',
 NULL,
 '{"required": true}',
 NULL, NULL, 17, true);